Apdc\ApdcBundle\Entity\Payout:
    type: entity
    table: null
    repositoryClass: Apdc\ApdcBundle\Repository\PayoutRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: float
        iban:
            type: string
            length: 255
        ownerName:
            type: string
            length: 255
        reference:
            type: string
            length: 255
        shopperEmail:
            type: string
            length: 255
        shopperReference:
            type: string
            length: 255
        date:
            type: datetime
    lifecycleCallbacks: {  }
