Apdc\ApdcBundle\Entity\PayoutChoice:
    type: entity
    table: null
    repositoryClass: Apdc\ApdcBundle\Repository\PayoutChoiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        choice:
            type: string
            length: 255
    lifecycleCallbacks: {  }
