Apdc\ApdcBundle\Entity\Refund:
    type: entity
    table: null
    repositoryClass: Apdc\ApdcBundle\Repository\RefundRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        originalReference:
            type: string
        value:
            type: float
            nullable: true
    lifecycleCallbacks: {  }
