Apdc\ApdcBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Apdc\ApdcBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        shopId:
            type: integer
            length: 11
            nullable: true
            column: shop_id
    lifecycleCallbacks: {  }
