<script type="text/javascript">
    <?php 
        $quartiers = Mage::helper('apdc_neighborhood')->getAllZipCode();
        echo "var zipcodes=".json_encode($quartiers).";";
        $websites = Mage::helper('apdc_neighborhood')->getAllWebsites();
    ?>
</script>
<div id='address-bar' class="input-box apdc-form container-fluid">
    <input id="GoogleAutoCompleteInput" class='input-text' placeholder='Entrez votre adresse' type='text' name='input_address' autocomplete="off" />
    <button data-ajax-url="<?php echo $this->getUrl('customhome/index/redirectAjax'); ?>" class="button button-green" type="submit" style="display:none;margin:0;">OK</button>
    <input id="GoogleAutoCompleteZipcode" name="input_zipcode" type="hidden"/>
    <p class="separator" style="margin: 10px 0;">ou</p>
    <select name="website-list">
        <option selected="true" disabled="disabled">Sélectionnez votre quartier</option>
      <?php foreach($websites as $order => $data):?>
        <option value="<?=$data['website_id']?>"><?=$data['name']?></option>
    <?php endforeach;?>
    </select>
    <div class="row text-center" name="messages" style="margin-top: 15px;"></div>
    <a class='button button-green' href='#' id='newsletter-popup' data-newsletter-view="<?php echo $this->getUrl('apdc-front/newsletter/ajaxPopupView');?>" role='button' title='Inscrivez-vous à notre newsletter' style="display:none;">Inscrivez-vous à notre newsletter !</a>
</div>
<script type='text/javascript' src='/js/apdc/address.js'></script>
<script type="text/javascript">
    jQuery('document').on('GmapsLoaded', function() {
        GoogleApiLandingpage();
    });
</script>
