<script type="text/javascript">
    <?php 
        $key = Mage::getStoreConfig('api_key/google/google_nav');
        $quartiers = Mage::helper('apdc_neighborhood')->getAllZipCode();
        echo "var zipcodes=".json_encode($quartiers).";";
        $websites = Mage::helper('apdc_neighborhood')->getAllWebsites();
    ?>
</script>
<div id='address-bar' class="input-box apdc-form">
    <input id="GoogleAutoCompleteInput" class='input-text' placeholder='Entrez votre adresse' type='text' name='input_address' />
    <button id="disambiguation-neighborhood" data-disambiguation-view="<?php echo $this->getUrl('customhome/index/ajaxPopupView');?>" data-ajax-url="<?php echo $this->getUrl('customhome/index/redirectAjax'); ?>" class="button button-green" type="submit" style="display:none;margin:0;">OK</button>
    <input id="GoogleAutoCompleteZipcode" name="input_zipcode" type="hidden"/>
    <p class="separator" style="margin: 10px 0;">ou</p>
    <select name="website-list" style='width:60%;font-size: 1.1rem;color: rgba(0, 0, 0, .62);text-align-last: center;'>
        <option selected="true" disabled="disabled">Sélectionnez votre quartier</option>
      <?php foreach($websites as $order => $data):?>
        <option value="<?=$data['website_id']?>"><?=$data['name']?></option>
    <?php endforeach;?>
    </select>
    <div class="row text-center" name="messages" style="margin-top: 15px;"></div>
    <a class='button button-green' href='#' id='newsletter-popup' data-newsletter-view="<?php echo $this->getUrl('apdc-front/newsletter/ajaxPopupView');?>" role='button' title='Inscrivez-vous à notre newsletter' style="display:none;">Inscrivez-vous à notre newsletter !</a>
</div>
<script type='text/javascript' src='/js/apdc/address.js'></script>
<script type='text/javascript' src='/js/GoogleApi/GoogleApi.js'></script>
<script src='https://maps.googleapis.com/maps/api/js?key=<?= $key ?>&libraries=places&callback=GoogleApiLandingpage'></script>