<?php
	$orders = $this->getLastOrdersByCustomer();
?>
<div class="block-lastorder">
	<?php if(count($orders) > 0) { ?>
		<h2>Mes dernières commandes</h2>
		<div class="row">
			<?php foreach($orders as $order) { ?>
				<?php
					$date = new Zend_Date(Mage::getModel('core/date')->timestamp(strtotime($order->getCreatedAt()), false, Mage::app()->getLocale()->getLocaleCode()));
				?>
				<article class="col-md-4 col-sm-4">
					<h3><strong>Ma commande </strong>du <?php echo $date->toString("d MMMM YYYY"); ?></h3>
					<p><?php echo Mage::helper('core')->currency($order->getGrandTotal(), true, false); ?></p>
					<a class="link" href="<?php echo Mage::getUrl('sales/order/view', array('order_id' => $order->getId())); ?>">Voir la commande</a>
					<a class="button button-green" href="<?php echo Mage::getUrl('sales/order/reorder', array('order_id' => $order->getId())); ?>">Recommander</a>
				</article>
			<?php } ?>
		</div>
	<?php } else { ?>
		<h2>Passez dès maitenant votre première commande</h2>
	<?php } ?>
</div>