<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$_socials = $this->getPromotions();
if(empty($_socials)) return;
//printr($_socials);
?>



<style>
.aworewardsblock ul.promo { list-style:none !important; }
.aworewardsblock ul.promo li{ padding: 10px !important; border-bottom:1px solid #dfdfdf !important; list-style: none !important; font-style:normal !important; }
.aworewardsblock ul.promo li:hover { background-color: #F2F5A9; cursor:pointer;}

.aworewardsblock ul.promo li.inactive { background-color: #cccccc; opacity: .5;-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=50);}
.aworewardsblock ul.promo li.inactive:hover { background-color: #cccccc; cursor:default; }

.aworewardsblock div.promo {position:relative;clear:both;width:100%;overflow:hidden;}
.aworewardsblock div.promo .colright, div.promo .colmid, div.promo .colleft {float:left;width:100%;position:relative;}
.aworewardsblock div.promo .col1, div.promo .col2, div.promo .col3 {float:left;position:relative;padding:0 0 1em 0;overflow:hidden;}

.aworewardsblock div.promo .colmid {right:15%;}
.aworewardsblock div.promo .colleft {right:70%;}
.aworewardsblock div.promo .col1 {width:11%;left:21%;}
.aworewardsblock div.promo .col2 {width:66%;left:102%;}
.aworewardsblock div.promo .col3 {width:11%;left:95%;}
.aworewardsblock div.promo  .col1 img { width:60px; }

.aworewardsblock div.promo .col2 .h {font-size:1.4em; padding-bottom:5px; color:#06C; }
.aworewardsblock div.promo .col2 .desc {}

.aworewardsblock div.promo .col3 {text-align:center;}
.aworewardsblock div.promo .col3 .h {font-size:2.3em; line-height:30px; }
.aworewardsblock div.promo .col3 .desc {font-size:.7em;}
.clear { clear:both; }
</style>



<div class="aworewardsblock">

	<?php if($this->is_js_facebook()) { ?>
		<script type="text/javascript">
		(function (d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) { return; }
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
			fjs.parentNode.insertBefore(js, fjs);
		} (document, "script", "facebook-jssdk"));
		window.fbAsyncInit = function () {
			FB.init({
				appId: "<?php echo $this->getFacebookAppID(); ?>",
				status: true, // Check login status.
				cookie: true, // Enable cookies to allow the server to access the session.
				xfbml: true  // Parse XFBML.
			});
		}
		window.fbAsyncInit = function () {
			FB.Event.subscribe("edge.create",
				function (response,elem) {
					widget_id = elem.getAttribute('id');
					if(widget_id!=undefined) {
						item_id = widget_id.substr(15);
						document.getElementById("fb_like_"+item_id).innerHTML = "<img src='<?php echo $this->getSkinUrl('images/awodev/aworewards/loading.gif'); ?>' />";
						document.getElementById("frm"+item_id).submit();
					}
					//alert("You liked the URL: " + response);
			});
		}
		</script>
	<?php } ?>

	<br />						
						

	<ul class="promo">
	<?php foreach($_socials as $_social) :
			$_rule_identifier = $_social->id.'_'.rand();
	?>
		<li class="promo <?php if(!$_social->is_active) echo 'inactive'; ?>" onclick="<?php if($_social->is_active  && !$_social->is_facebook_like) echo 'document.getElementById(\'frm'.$_rule_identifier.'\').submit();'; ?>return false;">
			<div class="promo">
				<div class="colmid">
					<div class="colleft">
						<div class="col2">
							<!-- Column 2 start -->
							<div class="h"><?php echo $_social->promo_headline; ?></div>
							<div class="desc"><?php echo $_social->promo_description; ?></div>
							<!-- Column 2 end -->
						</div>
						<div class="col1">
							<!-- Column 1 start -->
							<?php if(!$_social->is_facebook_like) { ?>
								<img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/'.$_social->image); ?>" />
							<?php }
							else { ?>
								<div id="fb_like_<?php echo $_rule_identifier?>">
									<fb:like 
										id="fb_like_widget_<?php echo $_rule_identifier; ?>" 
										href="http://www.facebook.com/<?php echo $_social->params->username; ?>" 
										layout="box_count"
										action="like"
										show_faces="false"
										share="false"
									></fb:like></div>
							<?php } ?>
							<!-- Column 1 end -->
						</div>
						<div class="col3">
							<!-- Column 3 start -->
							<div class="h"><?php echo $_social->reward; ?></div>
							<div class="desc"><?php if($_social->credit_type=='points') echo $this->__('Points'); ?></div>
							<!-- Column 3 end -->
						</div>
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<?php if($_social->is_active) : ?>
				<form id="frm<?php echo $_rule_identifier; ?>" name="frm<?php echo $_rule_identifier; ?>" method="post" action="<?php echo $this->getUrl('awodev_aworewards/promotion/socialpost') ?>" >
					<noscript><div style="text-align:right;"><input type="submit" value="<?php echo $this->__('Submit'); ?>" /></div></noscript>
						<input type="hidden" name="return" value="<?php echo Mage::helper('core/url')->getCurrentBase64Url(); ?>" />
						<input type="hidden" name="rule" value="<?php echo $_social->id; ?>" />
						<?php foreach($_social->hidden as $k=>$v) { ?>
							<input type="hidden" name="<?php echo $k; ?>" value="<?php echo $v; ?>" />
						<?php } ?>
					</form>
			<?php endif; ?>
		</li>
	<?php endforeach; ?>
	</ul>
</div>
