<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$_socials = $this->getPromotions();
if(empty($_socials)) return;
?>

<style>
.aworewardsblock div.promoblock {  }
.aworewardsblock div.promoblock .c1_1 { float: left; vertical-align:middle; }
.aworewardsblock div.promoblock .c1 img { float:left; width:60px; padding: 0 7px 0 0;}

.aworewardsblock div.promoblock .c1_2 { float: left; padding:0 10px 0 10px; }
.aworewardsblock div.promoblock .c1 .h {font-size:1.4em; padding-bottom:5px; color:#06C; }

.aworewardsblock div.promoblock .c2_1 {float:left; padding-top:8px; }
.aworewardsblock div.promoblock .c2_1 input {padding: 0 40px; }
.aworewardsblock div.promoblock .c2_2 { float: right; vertical-align:top; text-align:center;  }
.aworewardsblock div.promoblock .c2_2 .h {font-size:2.3em;}
.aworewardsblock div.promoblock .c2_2 .desc {font-size:.7em;}
.clear { clear:both; }

</style>

<div class="aworewardsblock">

	<?php if($this->is_js_facebook()) { ?>
		<script type="text/javascript">
		(function (d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) { return; }
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
			fjs.parentNode.insertBefore(js, fjs);
		} (document, "script", "facebook-jssdk"));
		window.fbAsyncInit = function () {
			FB.init({
				appId: "<?php echo $this->getFacebookAppID(); ?>",
				status: true, // Check login status.
				cookie: true, // Enable cookies to allow the server to access the session.
				xfbml: true  // Parse XFBML.
			});
		}
		window.fbAsyncInit = function () {
			FB.Event.subscribe("edge.create",
				function (response,elem) {
					widget_id = elem.getAttribute('id');
					if(widget_id!=undefined) {
						item_id = widget_id.substr(15);
						document.getElementById("fb_like_"+item_id).innerHTML = "<img src='<?php echo $this->getSkinUrl('images/awodev/aworewards/loading.gif'); ?>' />";
						document.getElementById("frm"+item_id).submit();
					}
					//alert("You liked the URL: " + response);
			});
		}
		</script>
	<?php } ?>

	<?php foreach($_socials as $_social) { 
			if(!$_social->is_active) continue;
			$_rule_identifier = $_social->id.'_'.rand();
	?>
	<div class="aworewardspromoblock">

		<div class="promoblock">
			<div class="c1">
				<?php if(!$_social->is_facebook_like) { ?>
					<img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/'.$_social->image); ?>" />
				<?php } ?>
				<span class="h"><?php echo $_social->promo_headline; ?></span>
				<br /><br />
				<span class="desc"><?php echo $_social->promo_description; ?></span>
			</div>
			<div>
				<div class="c2_1">
					<?php if($_social->is_facebook_like) { ?>
						<div id="fb_like_<?php echo $_rule_identifier; ?>">
							<fb:like 
								id="fb_like_widget_<?php echo $_rule_identifier;?>" 
								href="http://www.facebook.com/<?php echo $_social->params->username; ?>" 
								layout="box_count" 
								action="like" 
								show_faces="false"
								share="false"
							></fb:like></div>
					<?php } ?>
					<form id="frm<?php echo $_rule_identifier; ?>" name="frm<?php echo $_rule_identifier; ?>" method="post" action="<?php echo $this->getUrl('awodev_aworewards/promotion/socialpost') ?>" >
						<?php if(!$_social->is_facebook_like) { ?>
							<input type="submit" value="<?php echo $this->__('Submit'); ?>" />
						<?php } ?>
						<input type="hidden" name="return" value="<?php echo Mage::helper('core/url')->getCurrentBase64Url(); ?>" />
						<?php foreach($_social->hidden as $k=>$v) { ?>
							<input type="hidden" name="<?php echo $k; ?>" value="<?php echo $v; ?>" />
						<?php } ?>
						<input type="hidden" name="rule" value="<?php echo $_social->id; ?>" />
					</form>
				</div>
				<div class="c2_2">
					<div class="h"><?php echo $_social->reward; ?></div>
					<div class="desc"><?php if($_social->credit_type=='points') echo $this->__('Points'); ?></div>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<?php } ?>
</div>
