<div class="col-sm-8">
	<?php if ($this->getAgreements()): ?>
	<form action="" id="checkout-agreements" onsubmit="return false;">
	<ol class="checkout-agreements">
	<?php foreach ($this->getAgreements() as $_a): ?>
	    <li style="margin:0px;">
	        <p class="agree">
	            <input type="checkbox" id="cgv-checkbox" value="1" title="<?php echo $this->escapeHtml($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>">J'ai lu et j'accepte les <a href="<?= Mage::getUrl('mentions-legales-cgv')?>" target="_blank">Conditions Générales de Vente</a></label>
	        </p>
	    </li>
	<?php endforeach ?>
	</ol>
	</form>
	<?php endif;?>
</div>
<div class="hipay_infobox_headline col-sm-4" style="    padding: 10px 0;">
    <a style="color:#000;opacity:0.84;font-weight:bold;" href="https://www.hipaywallet.com/" target="_blank"><i class="fa fa-lock" aria-hidden="true"></i> Paiement 100% sécurisé en ligne</a>
</div>