<?php
/**
 * Inchoo is not affiliated with or in any way responsible for this code.
 *
 * Commercial support is available directly from the [extension author](http://www.techytalk.info/contact/).
 *
 * @category Marko-M
 * @package SocialConnect
 * @author Marko Martinović <marko@techytalk.info>
 * @copyright Copyright (c) Marko Martinović (http://www.techytalk.info)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div class="inchoo-socialconnect-login">
    <div class="account-login row">
        <?php if($this->_facebookEnabled()): ?>
        <div class="col-xs-12 col-md-6">
            <?php echo $this->getChildHtml('inchoo_socialconnect_facebook_login_button'); ?>
        </div>
        <?php endif; ?>

        <?php if($this->_googleEnabled()): ?>
        <div class="col-xs-12 col-md-6">
            <?php echo $this->getChildHtml('inchoo_socialconnect_google_login_button'); ?>
        </div>
        <?php endif; ?>
    </div>
</div>
