<?php
	$i = rand(1, 17); // generate random number size of the array
	$url = "images/header/".$i.".jpg"; // set variable equal to which random filename was chosen
	$angledown= $this->getSkinUrl("images/angle-down.png");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
	<?php echo $this->getChildHtml('head') ?>
</head>
<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
	<?php echo $this->getChildHtml('after_body_start') ?>
	<header class="header" id="faites-vos-courses">
	<div class="color-overlay">
		<div id="background_video_container" class="container">
			<video id="background_video_video" autoplay muted loop poster="<?php echo $this->getSkinUrl($url);?>">		
				<source src="<?php echo $this->getSkinUrl('media/demo.mp4');?>" type="video/mp4" />
				<source src="<?php echo $this->getSkinUrl('media/demo.ogv');?>" type="video/ogg" />
				<source src="<?php echo $this->getSkinUrl('media/demo.webm');?>" type="video/webm" />
			</video>
			<div class="intro-section">
				<img src="<?php echo $this->getSkinUrl('images/logo@2x.png')?>" alt="Logo Au Pas De Courses">
				<h1 class="intro">Les meilleurs produits de votre quartier,</br>sans vous déplacer</h1>
					<form id='form-quartier' role="form" class="col-xs-12 col-md-12 form-inline contact-form form_zipcode" method="post" action="<?php echo $this->getUrl('customhome/index/redirect'); ?>">
						<div id="input-group-intro">
							<input id='GoogleAutoCompleteInput' class='form-control input-quartier' placeholder='Entrez votre adresse' type='text' name='input_addr' />
							<input id='GoogleAutoCompleteZipcode' class='form-control input-quartier' type='hidden' name="zipcode" />
							<button id='GoogleAutoCompleteSubmit' class="btn btn-default standard-button input-quartier" type="submit">Voir mes commerçants</button>
						</div>
					</form>
				<div class="col-xs-12 col-md-12"></div>
				<div class="col-xs-12 col-md-12">
					<div id="scroll-button" >
						<p id="small-header">Plus d'infos</p>
						<div class="arrow bounce"></div>
					</div>
				</div>
				<div class="col-md-5"></div>
			</div>
		</div>
	</div>
	</header>
<section class="packages" id="quartiers">
	<div class="container">
		<div class="section-header">
			<h2 class="dark-text">Cliquez sur votre quartier</h2>
			<div class="section-description" style="margin-bottom:20px;">
				 Au Pas De Courses est aujourd'hui actif dans les arrondissements suivants à Paris.
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12 col-md-4">
				<a href="<?php echo Mage::getBaseUrl().'../batignolles';?>" style="display:block;width:100%">
					<img src="<?php echo $this->getSkinUrl('images/monceau_batignolles.jpg');?>" alt="Monceau - Batignolles, 17e-18e-9e-8e arrondissements de Paris" class="img-circle" style="width:100%;max-width:200px;"/>
					<h3 class="package-heading main-color">Monceau - Batignolles</h3>
					<p>17e-18e-9e-8e</p>
				</a>
			</div>
			<div class="col-sm-12 col-md-4">
				<a href="<?php echo Mage::getBaseUrl().'../commerce';?>" style="display:block;width:100%">
					<img src="<?php echo $this->getSkinUrl('images/commerce.jpg');?>" alt="Commerce, 15e arrondissement de Paris" class="img-circle" style="width:100%;max-width:200px;"/>
					<h3 class="package-heading main-color">Commerce</h3>
					<p>15e</p>
				</a>
			</div>
			<div class="col-sm-12 col-md-4">
				<a href="<?php echo Mage::getBaseUrl().'../batignolles';?>" style="display:block;width:100%">
					<img src="<?php echo $this->getSkinUrl('images/saintmartin_marais.jpg');?>" alt="Saint Martin - Marais 10e-3e-11e arrondissements de Paris" class="img-circle" style="width:100%;max-width:200px;"/>
					<h3 class="package-heading main-color">Saint Martin - Marais</h3>
					<p>10e-3e-11e</p>
				</a>
			</div>
		</div>
	</div>
</section>
<section class="packages grey-bg" id="concept">
	<div class="container">
		<div class="section-header">
			<h2 class="dark-text">Comment cela fonctionne ?</h2>
			<div class="colored-line"></div>
			<div class="section-description" >
				 Une plateforme pour commander et se faire livrer des produits frais et artisanaux de commerces de bouche locaux.
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 col-sm-12"></div>
			<div id="carousel-how" class="owl-carousel col-sm-12 col-md-4">
				<div class="item">
					<div class="single-package">
						<img src="<?php echo $this->getSkinUrl('images/online.png')?>" alt="Commandez en ligne vos produits frais et artisanaux">
						<ul class="package-feature">
							<li>1 - Commandez en ligne chez les commerçants de votre quartier.</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="single-package">
						<img src="<?php echo $this->getSkinUrl('images/shops.png')?>" alt="Les commerçants préparent votre commande">
						<ul class="package-feature">
							<li>2 - Les commerçants préparent votre commande</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="single-package">
						<img src="<?php echo $this->getSkinUrl('images/cargobike.png')?>" alt="On vous livre le tout chez vous, en une fois">
						<ul class="package-feature">
							<li>3 - On vous livre le tout chez vous, en une fois</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-12"></div>
		</div>
	</div>
</section>
<section class="packages" id="nos-tarifs">
	<div class="container">
		<div class="section-header">
			<h2 class="dark-text">Combien cela coûte ?</h2>
			<div class="colored-line"></div>
			<div class="section-description" >
				Les mêmes prix qu'en magasin, première livraison gratuite avec le code "PANIER"
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 col-sm-12"></div>
			<div id="carousel-price" class="owl-carousel col-sm-12 col-md-4">
				<div class="item">
					<div class="single-package">	
						<img src="<?php echo $this->getSkinUrl('images/bagx1.png')?>" alt="En dessous de 45€ d'achat">
						<ul class="package-feature">
							<li>En dessous de 45€ d'achat</li>
							<li class="price">9€ la livraison</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="single-package">
						<img src="<?php echo $this->getSkinUrl('images/bagx2.png')?>" alt="Entre 45 et 90€ d'achat">	
						<ul class="package-feature">
							<li>Entre 45 et 90€ d'achat</li>
							<li class="price">6€ la livraison</li>
						</ul>
					</div>
				</div>
				<div class="item">
					<div class="single-package">
						<img src="<?php echo $this->getSkinUrl('images/bagx3.png')?>" alt="Au-dessus de 90€ d'achat">	
						<ul class="package-feature">
							<li>Au-dessus de 90€ d'achat</li>
							<li class="price">3€ la livraison</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-12"></div>
		</div>
	</div>
</section>
<section class="app-brief grey-bg" id="brief1">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="" data-src="https://www.youtube.com/embed/gb75gUhl5bM" allowfullscreen></iframe>	
				</div>
			</div>
			<div class="col-md-6 left-align">
				<h2 class="dark-text">Simple, pratique et local</h2>
				<div class="colored-line-left">
				</div>
				<ul class="feature-list">
					<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Des commerçants locaux sélectionnés,</li>
					<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Des créneaux de livraison de 45 minutes,</li>
					<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Une livraison douce en triporteur électrique.</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<section class="avis" id="avis">
	<div class="container">
		<div class="section-header">
			<h2>Lauréat des <a href="http://www.cci-paris-idf.fr/presse/communiques/7eme-edition-des-palmes-du-e-commerce-2015-neuf-laureats-recompenses-pour-des-projets-de-commerce-innovants-presse" target="_blank" >Palmes du eCommerce 2015</a>!</h2>
			<div class="colored-line"></div>
			<div class="section-description" style="margin-bottom:50px;">
				 Une belle récompense pour notre équipe, nos clients et nos partenaires.
			</div>
		</div>
		<div class="col-md-3 col-sm-12"></div>
		<div id="carousel-comments" class="owl-carousel col-sm-12 col-md-4">
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">	Très belle initiative. Merci Au Pas de Courses et aux commerçants partenaires :-)</span>
					  </span>
					</div>
					<div class="avis-author">
					  Nadine G., Cliente fidèle.
					</div>
				</div>
			</div>
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">C'est extraordinaire d'avoir des produits faits par des artisans et livrés par Au Pas De Courses. On ne peut pas faire plus court que ce circuit là.</span>
					  </span>
					</div>
					<div class="avis-author">
					  Francis Ramon, La Fille du Boulanger.
					</div>
				</div>
			</div>
			<div class="item">	
				<div class="one-avis single-service" style="width:100%;display: block;height: auto;">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">"C'est désormais toute la semaine que vous aurez les meilleurs produits dans votre assiette"</span>
					  </span>
					</div>
					<div class="avis-author">
					  <a href="http://issuu.com/le-bonbon/docs/ouest_9dd7a5e8a951a4/26" target="_blank"><img src="<?php echo $this->getSkinUrl('images/lebonbon.png');?>" alt="Cliquez pour voir l'article du Bonbon"/></a>
					</div>
				</div>
			</div>
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">"Excellents produits, service ponctuel.</br>Je recommande !"</span>
					  </span>
					</div>
					<div class="avis-author">
					  Margot P., cliente de la première heure
					</div>
				</div>
			</div>
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">Ce service existe chez les grandes enseignes, nous pouvons maintenant faire la même chose avec Au Pas De Courses!</span>
					  </span>
					</div>
					<div class="avis-author">
					  Michel Vaidie, Boucherie des Moines.
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-12"></div>
	</div>
</section>
<section class="packages grey-bg" id="evenements">
	<div class="container">
		<div class="section-header">
			<h2 class="dark-text">Un évènement à organiser ?</h2>
			<div class="colored-line"></div>
			<div class="section-description" style="margin-bottom:50px;">
				 Au Pas De Courses et vos commerçants de quartier vous proposent des plateaux et des prestations sur mesure pour vos évènements, en famille ou au travail.
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<a id="contact-button" class="btn btn-default standard-button" href="javascript:void(Tawk_API.toggle());">Contactez nous !</a>
			</div> 
		</div> 
	</div>
</section>
<footer id="contact-section">
	<div class="container">
		<ul class="social-icons">
			<p>Suivez nous sur</p>
			<li><a href="https://www.facebook.com/aupasdecourses"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
			<li><a href="https://twitter.com/aupasdecourses"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
			<li><a href="https://plus.google.com/114890137995721785465/about"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
			<li><a href="https://instagram.com/aupasdecourses/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
		</ul>
		<p class="copyright">
			©<?php echo date("Y");?> Au Pas De Courses, tous droits réservés.</br> Crédit Photos: Pierre Mainguet, <a href="https://flic.kr/p/mJNxaB">David Fleg</a> et besopha <a href="https://commons.wikimedia.org/wiki/File%3ARue_de_Bretagne%2C_75003_Paris%2C_2015.jpg">Rue de Bretagne</a> / <a href="https://flic.kr/p/xifWho">Parc Georges Brassens</a>
		</p>
	</div>
	<a href="#" class="back-to-top">Haut de page</a>
</footer>
	<?php echo $this->getChildHtml('footer') ?>
	<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>
