<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>

<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>

<!-- =========================
     HEADER   
============================== -->
<header class="header" data-stellar-background-ratio="0.5" id="faites-vos-courses">

<!-- COLOR OVER IMAGE -->
<div class="color-overlay"> <!-- To make header full screen. Use .full-screen class with color overlay. Example: <div class="color-overlay full-screen">  -->
	<!-- CONTAINER -->
	<div class="container">
		<!-- ONLY LOGO ON HEADER -->
		<div class="only-logo">
			<div class="navbar">
				<div class="navbar-header">
					<img src="<?php echo $this->getSkinUrl('images/logo.png')?>" alt="Logo Au Pas De Courses">
				</div>
			</div>
		</div> <!-- /END ONLY LOGO ON HEADER -->
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<!-- HEADING AND BUTTONS -->
				<div class="intro-section">
					<!-- WELCOM MESSAGE -->
					<h1 class="intro">Faites vous livrer les meilleurs produits de votre quartier</h1>
				        <div class="col-md-12">
				        <form role="form" class="contact-form form_zipcode" method="post" action="<?php echo $this->getUrl('customhome/index/redirect'); ?>">
						    <div class="input-groupe-center">
							    <h3>Sélectionnez votre quartier pour commencer</h3>
							    <div class="input-group" style="margin: auto;">
							      <select class="form-control select-quartier" placeholder="Code postal" name="zipcode">
						    		<option disabled>Quartier Batignolles</option>
						    		<option selected>Paris 17e</option>
						      		<option>Paris 18e</option>
						      		<option>Paris 9e</option>
						      		<option>Paris 8e</option>
						      		<option disabled>──────────</option>
						      		<option disabled>Quartier Saint Martin</option>
					      			<option>Paris 10e</option>
					      			<option>Paris 3e</option>
					      			<option>Paris 11e</option>
					      			<option>Paris 2e</option>
					      			<option disabled>──────────</option>
					      			<option>Paris 1er</option>
					      			<option>Paris 4e</option>
					      			<option>Paris 5e</option>
					      			<option>Paris 6e</option>
					      			<option>Paris 7e</option>
					      			<option>Paris 12e</option>
					      			<option>Paris 13e</option>
					      			<option>Paris 14e</option>
					      			<option>Paris 15e</option>
					      			<option>Paris 16e</option>
					      			<option>Paris 19e</option>
					      			<option>Paris 20e</option>
					      			<option>Boulogne</option>
					      			<option>Levallois Perret</option>
					      			<option>Issy Les Moulineaux</option>
					      			<option>Vincennes</option>
					      			<option>Montrouge</option>
							      </select>	
									<button class="btn btn-default standard-button select-quartier" type="submit">OK</button>
							    </div><!-- /input-group -->
						    </div>
					    </form>
					</div>
					<div class="col-md-12">
						<div id="scroll-button" >
							<h3 class="small-header">Plus d'infos</h3>
							<div class="arrow bounce"></div>
						</div>
					</div>
					
				</div>
				<!-- /END HEADNING AND BUTTONS -->
			</div>
		</div>
		<!-- /END ROW -->
	</div>
	<!-- /END CONTAINER -->
</div>
<!-- /END COLOR OVERLAY -->
</header>
<!-- /END HEADER -->
<!-- =========================
     VIDEO 
============================== -->
<section class="video-youtube grey-bg" id="video-presentation">
<div class="container">
	<!-- SECTION HEADER -->
	<div class="section-header">
		<!-- SECTION TITLE -->
		<h2 class="dark-text">Se faire livrer le meilleur des artisans locaux ?</h2>
		<div class="colored-line"></div>
		<div class="section-description">
			C'est facile avec Au Pas De Courses!
		</div>
	</div>
	<!-- /END SECTION HEADER -->	
	<div class="row">
		<div class="col-sm-12">
			<div class="embed-responsive embed-responsive-16by9">
				<iframe class="embed-responsive-item" src="" data-src="https://www.youtube.com/embed/gb75gUhl5bM" allowfullscreen></iframe>	
			</div>
		</div>
	</div>
</div>
</section>
<!-- =========================
     TESTIMONIALS 
============================== -->
<section class="testimonials" id="le-service">

<div class="color-overlay">
	
	<div class="container">

	<div class="row">
		<div class="col-md-6 left-align" style="color:#333;">
			
			<!-- SECTION TITLE -->
			<h2 class="dark-text">Nous avons sélectionné la qualité au plus près de chez vous</h2>
			<div class="colored-line"></div>
			<div class="left-align">
				<p>
					Ils sont l'âme de votre quartier et détiennent des secrets d'artisans pour sélectionner les produits qui ont du goût et du caractère.
				</p>
				<!-- FEATURE LIST -->
				<ul class="feature-list">
					<li><i class="icon_lock_alt"></i> Ils choisissent des produits français en priorité,</li>
					<li><i class="icon_check_alt2"></i> Ils sont à l'écoute de vos envies,</li>
					<li><i class="icon_adjust-vert"></i> Ils préparent vos commandes avec soin,</li>
					<li><i class="icon_lock_alt"></i> Vous pouvez les retrouver en magasin quand vous le souhaitez.</li>
				</ul>
			</div>
		</div>
	</div>

		
	</div>
	<!-- /END CONTAINER -->
	
</div>
<!-- /END COLOR OVERLAY -->

</section>
<!-- /END TESTIMONIALS SECTION -->


<!-- =========================
     BRIEF LEFT SECTION 
============================== -->
<section class="app-brief grey-bg" id="brief1">

<div class="container">
	
	<div class="row">
		
		<!-- PHONES IMAGE -->
		<div class="col-md-6">
			<div class="phone-image">
				<img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $this->getSkinUrl('images/screens.png')?>" alt="Au Pas De Courses sur ordinateur, tablette et smartphone.">

			</div>
		</div>
		
		<!-- RIGHT SIDE WITH BRIEF -->
		<div class="col-md-6 left-align">
			
			<!-- SECTION TITLE -->
			<h2 class="dark-text">Un service simple</h2>
			
			<div class="colored-line-left">
			</div>
			
			<p>Commandez en quelques clics seulement.</p>
			
			<!-- FEATURE LIST -->
			<ul class="feature-list">
				<li><i class="icon_lock_alt"></i> Les mêmes produits qu'en magasin</li>
				<li><i class="icon_check_alt2"></i> Commandez sur votre ordinateur, votre tablette ou votre mobile</li>
				<li><i class="icon_adjust-vert"></i> Des créneaux de livraison de moins d'une heure, de 18h00 à 21h00</li>
				<li><i class="icon_lock_alt"></i> Un paiement en une seule fois, en toute sécurité</li>
			</ul>
			
		</div>
		<!-- /END RIGHT BRIEF -->
		
	</div>
	<!-- /END ROW -->
	
</div>
<!-- /END CONTAINER -->

</section>
<!-- /END SECTION -->


<!-- =========================
     BRIEF RIGHT SECTION 
============================== -->
<section class="app-brief" id="brief2">

<div class="container">
	
	<div class="row">
		
		<!-- BRIEF -->
		<div class="col-md-6 left-align">
			
			<!-- SECTION TITLE -->
			<h2 class="dark-text">Une livraison en douceur</h2>
			
			<div class="colored-line-left">
			</div>
			<p>
				La qualité de notre service est primordiale.
			</p>
			<!-- FEATURE LIST -->
			<ul class="feature-list">
				<li><i class="icon_lock_alt"></i> Nous utilisons des vélos triporteurs: pas de pollution, pas de bruit, pas de camions en double file.</li>
				<li><i class="icon_check_alt2"></i> Nos livreurs sont souriants et vous aideront à ranger vos courses si vous leur demandez.</li>
				<li><i class="icon_adjust-vert"></i>  Vous pourriez bien être livré par l'un des fondateurs, l'occasion de lui faire part de vos remarques et suggestions.</li>
			</ul>			
		</div>
		<!-- /ENDBRIEF -->
		
		<!-- PHONES IMAGE -->
		<div class="col-md-6">
			<div class="phone-image">
				<img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $this->getSkinUrl('images/livraison.jpg')?>" alt="La livraison douce en vélo électrique avec Au Pas De Courses">
			</div>
		</div>
		<!-- /END PHONES IMAGE -->
		
	</div>
	<!-- /END ROW -->
	
</div>
<!-- /END CONTAINER -->

</section>
<!-- /END SECTION -->

<!-- =========================
     PRICING TABLE | Added on version 1.7   
============================== -->
<section class="packages grey-bg" id="nos-tarifs">

<div class="container">
	
	<!-- SECTION HEADER -->
	<div class="section-header">
		
		<!-- SECTION TITLE -->
		<h2 class="dark-text">Combien cela coûte ?</h2>
		<div class="colored-line"></div>
		<div class="section-description" style="margin-bottom:50px;">
			 Nous sommes là dans toutes les situations!
			 <!--Soyez fidèle aux commerçants de votre quartier, et ils vous le rendront bien!-->
		</div>
	</div>
	<!-- /END SECTION HEADER -->
	
    <div class="row">
		
		<!-- SINGLE PACKACGE -->
		<div class="col-md-3 col-sm-3 single-service">
			
			<div class="single-package">
				
				<h3 class="package-heading main-color">Express</h3>
				
				<div class="price">
					<h2><span class="sign"></span>9€<span class="month">/commande</span></h2>
				</div>

				<span class="package-subheading">Disponible à tout moment.</span>
				
				<ul class="package-feature">
					<li><span class="main-color icon_check_alt2"></span>Moins de 45€ d'achat</li>
				</ul>
				
			</div>
		</div>
		<!-- /END SINGLE PACKACGE -->
		
		<!-- SINGLE PACKACGE -->
		<div class="col-md-3 col-sm-3 single-service">
			
			<div class="single-package">
				
				<h3 class="package-heading main-color">Gourmand</h3>
				
				<div class="price">
					<h2><span class="sign"></span>6€<span class="month">/commande</span></h2>
				</div>

				<span class="package-subheading">Pour se faire plaisir en semaine.</span>
				
				<ul class="package-feature">
					<li><span class="main-color icon_check_alt2"></span>De 45 à 90€ d'achat</li>
				</ul>
			</div>
		</div>
		<!-- /END SINGLE PACKACGE -->
		
		<!-- SINGLE PACKACGE -->
		<div class="col-md-3 col-sm-3 single-service">
			
			<div class="single-package">
				
				<h3 class="package-heading main-color">Familial</h3>
				
				<div class="price">
					<h2><span class="sign"></span>3€<span class="month">/commande</span></h2>
				</div>

				<span class="package-subheading">Pour les familles et ceux qui sont à plusieurs.</span>
				
				<ul class="package-feature">
					<li><span class="main-color icon_check_alt2"></span>Plus de 90€ d'achat</li>
				</ul>
			</div>
		</div>
		<!-- /END SINGLE PACKACGE -->

		<!-- SINGLE PACKACGE -->
		<div class="col-md-3 col-sm-3 single-service">
			
			<div class="single-package">
				
				<h3 class="package-heading main-color">Et pour tous</h3>
				
				<ul class="package-feature">
					<li style="font-weight:700;font-size:20px;">1<sup>ère</sup> commande gratuite, sans engagement, </br>avec le code </br>"BIENVENUE"</li>
					<li>Les même prix qu'en magasin</li>
					<li>Livraison le soir même, si commande avant 15h</li>
				</ul>
			</div>
		</div>
		</div>
		<!-- /END SINGLE PACKAGE -->
	</div>
	<!-- /END ROW -->
</div>
<!-- /END CONTAINER -->
</section>
<!-- /END PRICING TABLE SECTION -->
<!-- =========================
     ILS PARLENT DE NOUS SECTION 
============================== -->
<section class="avis" id="avis">

<div class="container">
		
	<!-- SECTION HEADER -->
	<div class="section-header">
		<!-- SECTION TITLE -->
		<h2>Ils parlent de nous</h2>
		<div class="colored-line"></div>
		<div class="section-description" style="margin-bottom:50px;">
			 Medias, clients, commerçants ...
		</div>
	</div>
	<!-- /END SECTION HEADER -->

	<div class="col-md-3 col-sm-12"></div>
	<div id="carousel-comments" class="owl-carousel col-sm-12 col-md-4">
		<div class="item">
			<div class="one-avis single-service" style="width:100%;display: block;height: auto;">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">"C'est désormais toute la semaine que vous aurez les meilleurs produits dans votre assiette"</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              <a href="http://issuu.com/le-bonbon/docs/ouest_9dd7a5e8a951a4/26" target="_blank"><img src="<?php echo $this->getSkinUrl('images/lebonbon.png');?>" alt="Cliquez pour voir l'article du Bonbon"/></a>
	            </div>
	        </div>
        </div>
        <div class="item">
			<div class="one-avis single-service">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">"Excellents produits, service ponctuel.</br>Je recommande !"</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              Margot P., cliente de la première heure
	            </div>
	        </div>
	    </div>
		<div class="item">
			<div class="one-avis single-service">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">"Une nouvelle initiative originale et maline voit le jour aux Batignolles. Testez vite et partagez."</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              <a href="https://www.facebook.com/LivinBatignolles?fref=ts" target="_blank"><img src="<?php echo $this->getSkinUrl('images/livin.jpg');?>" alt="Cliquez pour voir l'article de Livin'Batignolles"/>
	              <span style="color:white;">Livin'Batignolles</span></a>
	            </div>
	        </div>
	    </div>
		<div class="item">
			<div class="one-avis single-service">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">"En voilà un service pratique, conçu pour faciliter la vie des consommateurs comme celle des artisans!"</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              <a href="http://www.hello-paris17.fr/medias/vivre-a-paris-17/09-06-2015-simplifiez-vous-la-vie-avec-le-service-au-pas-de-courses" target="_blank"><img src="<?php echo $this->getSkinUrl('images/hello-paris17.png');?>" alt="Cliquez pour voir l'article de Hello Paris 17"/></a>
	            </div>
	        </div>
	    </div>
	</div>
	<div class="col-md-4 col-sm-12"></div>

</div>
<!-- /END CONTAINER -->

</section>
<!-- /END SECTION -->

<!-- =========================
     FOOTER 
============================== -->
<footer id="contact-section">

<div class="container">
	
	<!-- LOGO -->
	<img src="<?php echo $this->getSkinUrl('images/logo.png')?>" alt="LOGO" class="responsive-img">
	
	<!-- SOCIAL ICONS -->
	<ul class="social-icons">
		<li><a href="https://www.facebook.com/aupasdecourses"><i class="social_facebook_square"></i></a></li>
		<li><a href="https://twitter.com/aupasdecourses"><i class="social_twitter_square"></i></a></li>
		<li><a href="https://plus.google.com/114890137995721785465/about"><i class="social_googleplus_square"></i></a></li>
		<li><a href="https://instagram.com/aupasdecourses/"><i class="social_instagram_square"></i></a></li>
	</ul>
	
	<!-- COPYRIGHT TEXT -->
	<p class="copyright">
		©2015 Au Pas De Courses, tous droits réservés.
	</p>

</div>
<!-- /END CONTAINER -->

<a href="#" class="back-to-top">Haut de page</a>
 
</footer>
<!-- /END FOOTER -->
    <?php echo $this->getChildHtml('footer') ?>
</body>
</html>