<?php
  $i = rand(1, 17); // generate random number size of the array
  $url = "images/header/".$i.".jpg"; // set variable equal to which random filename was chosen
  $angledown= $this->getSkinUrl("images/angle-down.png");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<style>
header{
	background: transparent url("<?php echo $this->getSkinUrl($url);?>") no-repeat center top / cover;
}
</style>

<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
<!-- =========================
     HEADER   
============================== -->
<header class="header" data-stellar-background-ratio="0.5" id="faites-vos-courses">

<!-- COLOR OVER IMAGE -->
<div class="color-overlay"> <!-- To make header full screen. Use .full-screen class with color overlay. Example: <div class="color-overlay full-screen">  -->
	<!-- CONTAINER -->
	<div class="container">
		<!-- ONLY LOGO ON HEADER -->
		<div class="only-logo">
			<div class="navbar">
				<div class="navbar-header">
					<img src="<?php echo $this->getSkinUrl('images/logo.png')?>" alt="Logo Au Pas De Courses">
				</div>
			</div>
		</div> <!-- /END ONLY LOGO ON HEADER -->
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<!-- HEADING AND BUTTONS -->
				<div class="intro-section">
					<!-- WELCOM MESSAGE -->
					<h1 class="intro">Les meilleurs produits de votre quartier, sans vous déplacer</h1>
				        <div class="col-md-12">
				        <form role="form" class="contact-form form_zipcode" method="post" action="<?php echo $this->getUrl('customhome/index/redirect'); ?>">
						    <div id="input-group-intro">
							 	  <p class="label_input">Mon quartier: </p>
							      <select class="form-control select-quartier" placeholder="Code postal" name="zipcode" style="background: url('<?php echo $angledown;?>') 96% / 15% no-repeat #fff;float:none;">
						    		<option disabled>Monceau-Batignolles</option>
						    		<option selected>Paris 17e</option>
						      		<option>Paris 18e</option>
						      		<option>Paris 9e</option>
						      		<option>Paris 8e</option>
						      		<option disabled>──────────</option>
						      		<option disabled>Saint Martin-Marais</option>
					      			<option>Paris 10e</option>
					      			<option>Paris 3e</option>
					      			<option>Paris 11e</option>
					      			<option>Paris 2e</option>
					      			<option disabled>──────────</option>
					      			<option>Paris 1er</option>
					      			<option>Paris 4e</option>
					      			<option>Paris 5e</option>
					      			<option>Paris 6e</option>
					      			<option>Paris 7e</option>
					      			<option>Paris 12e</option>
					      			<option>Paris 13e</option>
					      			<option>Paris 14e</option>
					      			<option>Paris 15e</option>
					      			<option>Paris 16e</option>
					      			<option>Paris 19e</option>
					      			<option>Paris 20e</option>
					      			<option>Boulogne</option>
					      			<option>Levallois Perret</option>
					      			<option>Issy Les Moulineaux</option>
					      			<option>Vincennes</option>
					      			<option>Montrouge</option>
							      </select>	
									<button class="btn btn-default standard-button select-quartier" type="submit">OK</button>
							    </div><!-- /input-group -->
						    </div>
					    </form>
					</div>
					<div class="col-md-5"></div>
					<div class="col-md-2">
						<div id="scroll-button" >
							<p id="small-header">Plus d'infos</p>
							<div class="arrow bounce"></div>
						</div>
					</div>
					<div class="col-md-5"></div>
				</div>
				<!-- /END HEADNING AND BUTTONS -->
			</div>
		</div>
		<!-- /END ROW -->
	</div>
	<!-- /END CONTAINER -->
</div>
<!-- /END COLOR OVERLAY -->
</header>
<!-- /END HEADER -->

<!-- =========================
     CONCEPT | Added on version 1.7   
============================== -->
<section class="packages grey-bg" id="concept">

<div class="container">
	
	<!-- SECTION HEADER -->
	<div class="section-header">
		
		<!-- SECTION TITLE -->
		<h2 class="dark-text">Comment cela fonctionne ?</h2>
		<div class="colored-line"></div>
		<div class="section-description" style="margin-bottom:50px;">
			 Ue plateforme qui vous propose de commander des produits frais et artisanaux de commerces de bouche locaux, et de les livrer chez vous.
		</div>
	</div>
	<!-- /END SECTION HEADER -->
    <div class="row">
		<!-- SINGLE PACKACGE -->
		<div class="col-md-4 col-sm-4 single-service">
			<div class="single-package">
				<img src="<?php echo $this->getSkinUrl('images/online.png')?>" alt="Commandez en ligne vos produits frais et artisanaux">
				<ul class="package-feature">
					<li>1 - Commandez en ligne chez les commerçants de votre quartier.</li>
				</ul>
			</div>
		</div>
		<!-- /END SINGLE PACKACGE -->
		<!-- SINGLE PACKACGE -->
		<div class="col-md-4 col-sm-4 single-service">
			<div class="single-package">
				<img src="<?php echo $this->getSkinUrl('images/shops.png')?>" alt="Les commerçants préparent votre commande">
				<ul class="package-feature">
					<li>2 - Les commerçants préparent votre commande</li>
				</ul>
				
			</div>
		</div>
		<!-- /END SINGLE PACKACGE -->
		<!-- SINGLE PACKACGE -->
		<div class="col-md-4 col-sm-4 single-service">
			<div class="single-package">
				<img src="<?php echo $this->getSkinUrl('images/cargobike.png')?>" alt="On vous livre le tout chez vous, en une fois">
				<ul class="package-feature">
					<li>3 - On vous livre le tout chez vous, en une fois</li>
				</ul>
			</div>
		</div>
		<!-- /END SINGLE PACKACGE -->
	</div>
	<!-- /END ROW -->
</div>
<!-- /END CONTAINER -->
</section>
<!-- /END CONCEPT SECTION -->
<!-- =========================
     CONCEPT | Added on version 1.7   
============================== -->
<section class="packages" id="concept">

<div class="container">
	
	<!-- SECTION HEADER -->
	<div class="section-header">
		
		<!-- SECTION TITLE -->
		<h2 class="dark-text">Faites vous livrer</h2>
		<div class="colored-line"></div>
		<div class="section-description" style="margin-bottom:50px;">
			 Au Pas De Courses est aujourd'hui actif dans les arrondissements suivants à Paris.
		</div>
	</div>
	<!-- /END SECTION HEADER -->
    <div class="row">
		<!-- SINGLE PACKACGE -->
		<div class="col-md-6 col-sm-6 single-service">
			<?php $url_cover=$this->getSkinUrl('images/monceau_batignolles.jpg');?>
				<div class="single-package" style="background-image: url('<?php echo $url_cover;?>')">
					<a href="<?php echo Mage::getBaseUrl().'../batignolles';?>">
						<div class="color-overlay">
							<h3 class="package-heading main-color">Monceau - Batignolles</h3>
							<p>17e-18e-9e-8e</p>
						</div>
					</a>
				</div>
		</div>
		<!-- /END SINGLE PACKACGE -->
		<!-- SINGLE PACKACGE -->
		<div class="col-md-6 col-sm-6 single-service">
			<?php $url_cover=$this->getSkinUrl('images/saintmartin_marais.jpg');?>
				<div class="single-package" style="background-image: url('<?php echo $url_cover;?>')">
					<a href="<?php echo Mage::getBaseUrl().'../saintmartin';?>">
						<div class="color-overlay">
							<h3 class="package-heading main-color">Saint Martin - Marais</h3>
							<p>10e-3e-11e</p>
						</div>
					</a>
				</div>
			</a>
		</div>
		<!-- /END SINGLE PACKACGE -->
	</div>
	<!-- /END ROW -->
</div>
<!-- /END CONTAINER -->
</section>
<!-- /END CONCEPT SECTION -->
<!-- =========================
     BRIEF LEFT SECTION 
============================== -->
<section class="app-brief grey-bg" id="brief1">
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div class="embed-responsive embed-responsive-16by9">
				<iframe class="embed-responsive-item" src="" data-src="https://www.youtube.com/embed/gb75gUhl5bM" allowfullscreen></iframe>	
			</div>
		</div>
		<div class="col-md-6 left-align">
			<h2 class="dark-text">Simple, pratique et local</h2>
			<div class="colored-line-left">
			</div>
			<ul class="feature-list">
				<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Des commerçants locaux sélectionnés,</li>
				<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Les mêmes prix qu'en magasin,</li>
				<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Des créneaux de livraison de 45 minutes,</li>
				<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Une livraison douce en triporteur électrique.</li>
			</ul>
		</div>
	</div>
</div>
</section>
<!-- /END SECTION -->
<!-- =========================
     PRICING TABLE | Added on version 1.7   
============================== -->
<section class="packages" id="nos-tarifs">

<div class="container">
	
	<!-- SECTION HEADER -->
	<div class="section-header">
		
		<!-- SECTION TITLE -->
		<h2 class="dark-text">Combien cela coûte ?</h2>
		<div class="colored-line"></div>
		<div class="section-description" style="margin-bottom:50px;">
			 Pas de minimum de commande. Première livraison gratuite avec le code "BIENVENUE"
		</div>
	</div>
	<!-- /END SECTION HEADER -->
	
    <div class="row">
		<div class="col-md-4 col-sm-4 single-service">
			<div class="single-package">	
				<img src="<?php echo $this->getSkinUrl('images/bagx1.png')?>" alt="En dessous de 45€ d'achat">
				<ul class="package-feature">
					<li>En dessous de 45€ d'achat</li>
					<li class="price">9€ la livraison</li>
				</ul>
			</div>
		</div>
		<div class="col-md-4 col-sm-4 single-service">
			<div class="single-package">
				<img src="<?php echo $this->getSkinUrl('images/bagx2.png')?>" alt="Entre 45 et 90€ d'achat">	
				<ul class="package-feature">
					<li>Entre 45 et 90€ d'achat</li>
					<li class="price">6€ la livraison</li>
				</ul>
			</div>
		</div><div class="col-md-4 col-sm-4 single-service">
			<div class="single-package">
				<img src="<?php echo $this->getSkinUrl('images/bagx3.png')?>" alt="Au-dessus de 90€ d'achat">	
				<ul class="package-feature">
					<li>Au-dessus de 90€ d'achat</li>
					<li class="price">3€ la livraison</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- /END ROW -->
</div>
<!-- /END CONTAINER -->
</section>
<!-- /END PRICING TABLE SECTION -->
<!-- =========================
     ILS PARLENT DE NOUS SECTION 
============================== -->
<section class="avis" id="avis">

<div class="container">
		
	<!-- SECTION HEADER -->
	<div class="section-header">
		<!-- SECTION TITLE -->
		<h2>Lauréat de la <a href="http://www.cci-paris-idf.fr/presse/communiques/7eme-edition-des-palmes-du-e-commerce-2015-neuf-laureats-recompenses-pour-des-projets-de-commerce-innovants-presse" target="_blank" >Palme du eCommerce 2015</a>!</h2>
		<div class="colored-line"></div>
		<div class="section-description" style="margin-bottom:50px;">
			 Une belle récompense pour notre équipe, nos clients et nos partenaires.
		</div>
	</div>
	<!-- /END SECTION HEADER -->

	<div class="col-md-3 col-sm-12"></div>
	<div id="carousel-comments" class="owl-carousel col-sm-12 col-md-4">
		<div class="item">
			<div class="one-avis single-service">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">	Très belle initiative. Merci Au Pas de Courses et aux commerçants partenaires :-)</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              Nadine G., Cliente fidèle.
	            </div>
	        </div>
	    </div>
		<div class="item">
			<div class="one-avis single-service">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">C'est extraordinaire d'avoir des produits faits par des artisans et livrés par Au Pas De Courses. On ne peut pas faire plus court que ce circuit là.</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              Francis Ramon, La Fille du Boulanger.
	            </div>
	        </div>
	    </div>
		<div class="item">
			<div class="one-avis single-service" style="width:100%;display: block;height: auto;">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">"C'est désormais toute la semaine que vous aurez les meilleurs produits dans votre assiette"</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              <a href="http://issuu.com/le-bonbon/docs/ouest_9dd7a5e8a951a4/26" target="_blank"><img src="<?php echo $this->getSkinUrl('images/lebonbon.png');?>" alt="Cliquez pour voir l'article du Bonbon"/></a>
	            </div>
	        </div>
        </div>
        <div class="item">
			<div class="one-avis single-service">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">"Excellents produits, service ponctuel.</br>Je recommande !"</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              Margot P., cliente de la première heure
	            </div>
	        </div>
	    </div>
	    <div class="item">
			<div class="one-avis single-service">
	            <div class="avis-main">
	              <span class="vc-outer">
	                <span class="vc-inner">Ce service existe chez les grandes enseignes, nous pouvons maintenant faire la même chose avec Au Pas De Courses!</span>
	              </span>
	            </div>
	            <div class="avis-author">
	              Michel Vaidie, Boucherie des Moines.
	            </div>
	        </div>
	    </div>
	</div>
	<div class="col-md-4 col-sm-12"></div>

</div>
<!-- /END CONTAINER -->
</section>
<!-- /END SECTION -->
<!-- =========================
     EVENEMENTS SECTION
============================== -->
<section class="packages grey-bg" id="evenements">
<div class="container">
	

<div class="container">
	<!-- SECTION HEADER -->
		<div class="section-header">
			<!-- SECTION TITLE -->
			<h2 class="dark-text">Un évènement à organiser ?</h2>
			<div class="colored-line"></div>
			<div class="section-description" style="margin-bottom:50px;">
				 Au Pas De Courses et vos commerçants de quartier vous proposent des plateaux pour vos évènements en famille ou au travail.
			</div>
		</div>
		<!-- /END SECTION HEADER -->
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<a class="btn btn-default standard-button" href="javascript:void(Tawk_API.toggle())">Nous contacter</a>
			</div> 
		</div> 
	</div>
<!-- /END CONTAINER -->
</section>
<!-- /END PRICING TABLE SECTION -->
<!-- =========================
     FOOTER 
============================== -->
<footer id="contact-section">

<div class="container">
	<!-- SOCIAL ICONS -->
	<ul class="social-icons">
		<p>Suivez nous sur</p>
		<li><a href="https://www.facebook.com/aupasdecourses"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
		<li><a href="https://twitter.com/aupasdecourses"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
		<li><a href="https://plus.google.com/114890137995721785465/about"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
		<li><a href="https://instagram.com/aupasdecourses/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
	</ul>
	
	<!-- COPYRIGHT TEXT -->
	<p class="copyright">
		©<?php echo date("Y");?> Au Pas De Courses, tous droits réservés. Crédit Photos: Pierre Mainguet, <a href="https://flic.kr/p/mJNxaB">David Fleg</a> et <a href="https://commons.wikimedia.org/wiki/File%3ARue_de_Bretagne%2C_75003_Paris%2C_2015.jpg">besopha</a>
	</p>

</div>
<!-- /END CONTAINER -->

<a href="#" class="back-to-top">Haut de page</a>
 
</footer>
<!-- /END FOOTER -->
    <?php echo $this->getChildHtml('footer') ?>
</body>
</html>