<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Deliverydate
 */
?>
<!-- BEGIN `Amasty: Delivery Date` -->
<div class="entry-edit" style="margin-bottom: 10px;">
    <div class="entry-edit-head">
        <h4 class="icon-head head-attributes"><?php echo $this->__('Delivery Date'); ?></h4>
    </div>
    <div class="hor-scroll">
        <?php foreach ($this->getFormElements() as $element): ?>
            <?php echo $element->toHtml(); ?>
        <?php endforeach; ?>
    </div>
</div>
<div class="clear"></div>
<div class="clear"></div>
<!-- END `Amasty: Delivery Date` -->
