<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Deliverydate
 */
?>
<!-- BEGIN `Amasty: Delivery Date` -->
<?php if (Mage::helper('core')->isModuleEnabled('Amasty_Orderattr')): ?>
    <div class="box-right">
<?php endif; ?>
    <div class="entry-edit" style="margin-bottom: 10px;">
        <div class="entry-edit-head">
            <h4 class="icon-head head-attributes"><?php echo $this->__('Delivery Date'); ?></h4>
            <?php if ($editUrl = $this->getEditUrl()): ?>
                <div class="tools">
                    &nbsp;&nbsp;<a href="<?php echo $editUrl; ?>">Edit</a>
                </div>
            <?php endif; ?>
        </div>
        <fieldset id="deliverydate">
            <?php $fields = $this->getDeliveryDateFields(); ?>
            <?php if (!empty($fields)): ?>
            <table cellspacing="0" class="form-list">
                <tbody>
                <?php foreach ($fields as $field): ?>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->__($field['label']); ?></label>
                        </td>
                        <td class="value" id="field_<?php echo $field['code']; ?>">
                            <?php if ('date' === $field['code']): ?>
                                <div id="viewblock_date">
                                    <?php if ($field['value']): ?>
                                        <strong>
                                            <?php echo date(Mage::helper('amdeliverydate')->getPhpFormat(), strtotime($field['value'])); ?>
                                        </strong>
                                    <?php endif; ?>
                                </div>
                            <?php elseif ('time' === $field['code']) :?>
                                <div id="viewblock_<?php echo $field['code']; ?>">
                                        <strong><?php echo nl2br(str_replace('$', '\$', htmlentities($field['value']))); ?></strong>
                                </div>
                            <?php elseif ('comment' === $field['code']) :?>
                                <div id="viewblock_<?php echo $field['code']; ?>">
                                    <strong><?php echo nl2br(htmlspecialchars($field['value'])); ?></strong>
                                </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php endif; ?>
        </fieldset>
    </div>
<?php if (Mage::helper('core')->isModuleEnabled('Amasty_Orderattr')): ?>
    </div>
<?php endif; ?>
<div class="clear"></div>
<div class="clear"></div>
<!-- END `Amasty: Delivery Date` -->
