<link rel="stylesheet" href="style/timeline.css">
<div class="container">
    <div class="col-md-12">
        <div class="page-header">
            <h1 id="timeline">Préparation des commandes <small>Process</small></h1>
        </div>
        <ul class="timeline">
            <li>
              <div class="timeline-badge"><span>15h</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">Clôture des commandes de la journée</h4>
                </div>
              </div>
            </li>
            <li>
              <div class="timeline-badge"><span>15h</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">1 - Vérification des commandes Back Office Magento</h4>
                  <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 15h</small></p>
                </div>
                <div class="timeline-body">
                  <p><a href="https://www.aupasdecourses.com/index.php/admin/petitcommis$admin/sales_order/" target="_blank">Back Office Magento - Commande</a></p>
                </div>
              </div>
            </li>
            <li class="timeline-inverted">
              <div class="timeline-badge"><span>15h</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">2 - Vérification du paiement Hipay</h4>
                  <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 15h</small></p>
                </div>
                <div class="timeline-body">
                  <p><a href="">Back Office Hipay - Transaction</a></p>
                </div>
              </div>
            </li>
            <li class="timeline">
              <div class="timeline-badge warning"><span>15h15</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">3 - Envoi de la liste des commandes aux commerçants</h4>
                  <p><small class="text-muted">Relecture du pdf et envoi mail</small></p>
                </div>
                <div class="timeline-body">
                  <p><a href="index.php?module=commercant&action=view" target="_blank">Liste des commandes par commerçant</a></p>
                </div>
              </div>
            </li>
            <li class="timeline">
              <div class="timeline-badge warning"><span>Dès 15h15</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">4 - Appel des commerçants pour validation réception commande</h4>
                  <p><small class="text-muted">Vérification des difficultés de compréhension & disponibilité produits</small></p>
                </div>
                <div class="timeline-body">
                  <p><a href="index.php?module=commercant&action=view" target="_blank">Contacts commerçants</a></p>
                </div>
              </div>
            </li>
            <li class="timeline-inverted">
              <div class="timeline-badge warning"><span>Dès 15h15</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">5 - Organisation des tournées</h4>
<!--                   <p><small class="text-muted">Si modifications de la part du commerçants</small></p> -->
                </div>
                <div class="timeline-body">
                  <p>Organisation des tournées des commerçants en fonction des commandes</p>
                  <p><a href="" target="_blank">Récupération de la liste des adresses commandes</a></p>
                  <p><a href="" target="_blank">Calcul de l'itinéraire optimal</a></p>
                </div>
              </div>
            </li>
            <li class="timeline">
              <div class="timeline-badge"><span>15h30 16h45</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">6 - Editer les commandes</h4>
                  <p><small class="text-muted">Si modifications de la part du commerçants</small></p>
                </div>
                <div class="timeline-body">
                  <p><a href="https://www.aupasdecourses.com/index.php/admin/petitcommis$admin/sales_order/" target="_blank">Back Office Magento - Commandes</a></p>
                </div>
              </div>
            </li>
            <li class="timeline-inverted">
              <div class="timeline-badge"><span>16h45 17h15</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">7 - Impression du book livreur</h4>
<!--                   <p><small class="text-muted">Si modifications de la part du commerçants</small></p> -->
                </div>
                <div class="timeline-body">
                  <h5 style="text-decoration:underline">Documents tournée commerçants</h5>
                  <p>Impression des liste commande commmerçants<p>
                  <p>Classement des listes en fonction du plan de ramassage de l'étape 4<p>
                   <h5 style="text-decoration:underline">Documents tournée clients</h5>
                  <p><a href="https://www.aupasdecourses.com/index.php/admin/petitcommis$admin/sales_order/" target="_blank">Impression des reçus</a></p>
                  <p>Classement des reçus en fonction du plan de rammassage de l'étape 4</p>
                </div>
              </div>
            </li><li class="timeline">
              <div class="timeline-badge"><span>17h30</span></div>
              <div class="timeline-panel">
                <div class="timeline-heading">
                  <h4 class="timeline-title">8 - Début de la tournée</h4>
<!--                   <p><small class="text-muted">Si modifications de la part du commerçants</small></p> -->
                </div>
              </div>
            </li>
        </ul>
    </div>
      <div>
          <a id="retour_liste" href="index.php"><button type="button" class="btn btn-default btn-block btn-lg">Retour </button></a>
      </div>
    </div>
  </div>

<!--le div fermant le container se trouve dans le fichier footer.php-->