apdc_apdc:
    resource: "@ApdcApdcBundle/Resources/config/routing.yml"
    prefix:   /


app:
  resource: "@AppBundle/Controller/"
  type:     annotation

oneup_uploader:
    resource: . 
    type: uploader
