# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    acl:
        connection: default

        # CSRF TOKEN FOR 'REFUND INPUT ACTION'
        #secured_area:
        #     form_login:
        #       csrf_token_generator: security.csrf.token_manager
        #       csrf_parameter: _csrf_security_token
        #       csrf_token_id: authenticate

    encoders:
        Apdc\ApdcBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_DISPATCH]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        apdc_provider:
            id: fos_user.user_provider.username

    access_control:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        apdc_login_firewall:
            pattern: ^/users/login$
            anonymous: true

        apdc_firewall:
            pattern: ^/
            anonymous: false
            provider: apdc_provider
            form_login:
                login_path: userLogin
                check_path: userLoginCheck
            logout:
                path: userLogout
                target: /users/login
     
