# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    acl:
        connection: default

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        apdc_firewall:
           pattern: ^/
           anonymous: true
        #    provider: in_memory
        #   form_login:
        #       login_path: users/login
        #       check_path: login_check
        #   logout:
        #       path: users/logout
        #       target: users/login
       
        # CSRF TOKEN FOR 'REFUND INPUT ACTION'
        #secured_area:
        #     form_login:
        #       csrf_token_generator: security.csrf.token_manager
        #       csrf_parameter: _csrf_security_token
        #       csrf_token_id: authenticate

#   encoders:
        #Symfony\Component\Security\Core\User\User: plaintext

#   role_hierarchy:
#       ROLE_ADMIN:       [ROLE_USER, ROLE_USERRESTRICTED]
#       ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_USERRESTRICTED, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       in_memory:
           memory: ~
#               users:
#                   userrestricted: { password: userrestrictedpass, roles: ['ROLE_USERRESTRICTED'] }
#                   user:           { password: userpass, roles: ['ROLE_USER'] }
#                   admin:          { password: adminpass, roles: ['ROLE_ADMIN'] }

#   access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
