<script>
function init() {
    var imgDefer = document.getElementsByTagName('img');
    for (var i=0; i<imgDefer.length; i++) {
        if(imgDefer[i].getAttribute('data-src')) {
            imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src'));
        }
    }
    var vidDefer = document.getElementsByTagName('iframe');
    for (var i=0; i<vidDefer.length; i++) {
        if(vidDefer[i].getAttribute('data-src')) {
            vidDefer[i].setAttribute('src',vidDefer[i].getAttribute('data-src'));
        }
    }
}
window.onload = init;
</script>
<script type="text/javascript">
function downloadJSAtOnload() {
    var jsArray = [
        "<?php echo $this->getSkinUrl('owl-carrousel/owl.carousel.min.js')?>",
        "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'googleanalytics/ga.js'?>",
        "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'tawkto/tawkto.js'?>"
        ];
    var arrayLength = jsArray.length;
    for (var i = 0; i < arrayLength; i++) {
        var element = document.createElement("script");
        element.src = jsArray[i];
        document.body.appendChild(element);
    }
}
if (window.addEventListener)
window.addEventListener("load", downloadJSAtOnload, false);
else if (window.attachEvent)
window.attachEvent("onload", downloadJSAtOnload);
else window.onload = downloadJSAtOnload;
</script>
<script src="<?php echo $this->getSkinUrl('js/custom.js');?>"></script>
<!-- Hotjar Tracking Code for http://www.aupasdecourses.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:168512,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '1709948302620869');
fbq('track', "PageView");</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1709948302620869&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->

<?php
	$key = Mage::getModel('core/variable')->loadByCode('GoogleApiKey')->getValue('plain');
?>
<script type='text/javascript' src='/js/GoogleApi/GoogleApi.js'></script>
<script src='https://maps.googleapis.com/maps/api/js?key=<?= $key ?>&signed_in=true&libraries=places&callback=GoogleApiLandingpage' async defer></script>
