<!--Iphone webapp-->
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
<meta name="format-detection" content="telephone=yes"/>
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->getSkinUrl('images/apple-touch-icon.png?v=Ryo4wAQ5QR', array('_secure'=>true));?>"/>
<link rel="apple-touch-startup-image" href="<?php echo $this->getSkinUrl('images/splash-startup.png', array('_secure'=>true));?>"/>
<!--Chrome webapp-->
<link rel="manifest" href="<?php echo $this->getSkinUrl('webapp/manifest.json', array('_secure'=>true));?>"/>
<meta name="mobile-web-app-capable" content="yes"/>
<!--Other webapp-->
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="HandheldFriendly" content="true"/>
<meta property="og:image" content="<?php echo $this->getSkinUrl('images/screens.png')?>" />
<meta property="og:image" content="<?php echo $this->getSkinUrl('images/bg-2.jpg')?>" />
<meta property="og:image" content="<?php echo $this->getSkinUrl('images/logo@2x.png')?>" />
<meta property="og:image" content="<?php echo $this->getSkinUrl('images/livraison.jpg')?>" />
<meta property="og:image" content="<?php echo $this->getSkinUrl('images/bg-1.jpg')?>" />
<meta property="og:image" content="<?php echo $this->getSkinUrl('images/bg-3.jpg')?>" />
<meta property="og:title" content="Au Pas De Courses - Les courses en ligne chez vos commerçants." />
<meta property="og:url" content="https://www.aupasdecourses.com" />
<meta property="og:type" content="website" />
<meta property="og:description" content="Faites vos courses en ligne sur Au Pas De Courses, pour bien manger avec vos petits commerçants. Essayez maintenant, la première livraison est offerte!" />
<meta name="theme-color" content="#ffffff">