<?php echo $this->getChildHtml('checkout.onepage.checkcart.info'); ?>
<div id="co-checkcart-form">
	<div class="buttons-set clearfix" id="checkcart-buttons-container">
		<p class="back-link"><a href="#" onclick="checkout.back(); return false;" class="button button-grey"><i class="fa fa-angle-left"></i> <?php echo $this->__('Revenir') ?></a></p>
		<button type="button" title="<?php echo $this->__('Continue') ?>" class="button button-green pull-right" onclick="checkcart.save()"><?php echo $this->__('Continuer') ?> <i class="fa fa-angle-right"></i></button>
		<span class="please-wait" id="checkcart-please-wait" style="display:none;">
			<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Un instant s\'il vous plaît...') ?>" title="<?php echo $this->__('Un instant s\'il vous plaît...') ?>" class="v-middle" /> <?php echo $this->__('Un instant s\'il vous plaît...') ?>
		</span>
	</div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var checkcart = new Checkcart('co-checkcart-form', '<?php echo $this->getUrl('checkout/onepage/saveCheckcart') ?>');
    //var ddateForm = new VarienForm('co-ddate-form');
    //]]>
</script>