<div id="apdc-child">
	<div id="co-ddate-form">
		<h3><?php echo $this->__('Choisissez votre créneau de livraison');?></h3>
		<fieldset class="group-select">
			<div class="input-box">
                <input type="hidden" id="ddate:date" name="ddate[date]" value="" title="<?php echo $this->__('Delivery Date') ?>" class="input-text" />
                <input type="hidden" id="ddate:dtime" name="ddate[dtime]" value="" title="<?php echo $this->__('Delivery Time') ?>" class="input-text" />
                <input type="hidden" id="ddate:ddatei" name="ddate[ddatei]" value="<?php echo Mage::getSingleton('core/session')->getDdatei(); ?>" class="input-text" />
            </div>
			<?php if (!Mage::getStoreConfig("ddate/info/calender_display")) { ?>
				<div class="delivery">
					<div class="deli_date_time">
						<div class="deli_time">
							<h6 class="first_column_header"><strong><?php echo Mage::getStoreConfig("ddate/info/first_column_header") ?></strong></h6>
							<?php
								$slots = $this->getSlots();
								foreach ($slots as $slot) {
									echo "<p>" . $slot->getDtime() . "</p>";
								}
							?>
						</div>
						<div class="deli_date">
							<div id="slideshow-area">
								<div id="slideshow-scroller">
									<div id="slideshow-holder">
										<script>

											var initSelectDdate = false;

											function selectDdate(date, dtime, elt){
                                                var ddatei = jQuery(elt).attr('data-ddatei');
                                                var isInPopup = (jQuery(elt).parents('.apdc-popup').length > 0);
                                                var needToSave = (initSelectDdate == false && (date != document.getElementById('ddate:date').value || dtime != document.getElementById('ddate:dtime').value));


												if(needToSave) {
                                                    if (isInPopup && typeof(apdcDeliveryPopup) !== 'undefined') {
                                                        apdcDeliveryPopup.showLoading();
                                                    }
													jQuery.ajax( {
														url : '<?php echo $this->getUrl('checkout/onepage/saveDdateAjax') ?>',
														type: 'post',
														dataType : 'json',
														data:{
															'date':date,
															'dtime':dtime,
															'ddatei':ddatei,
															'url':'<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>'
														},
														success : function(data) {
                                                            if (isInPopup) {
                                                                window.location.reload();
                                                            }
														}
													});
												}
												else {
													initSelectDdate = false;
												}

												document.getElementById('ddate:ddatei').value = ddatei;
												document.getElementById('ddate:date').value = date;
												document.getElementById('ddate:dtime').value = dtime;

												jQuery('#slideshow-holder ul li a').removeClass('ddate_day_active');
												jQuery('#slideshow-holder ul li a i').removeClass('fa-thumbs-up').addClass('fa-check');
											}

											function selectDdateAct(current_select){
												if (!jQuery(current_select).hasClass('disablerow')) {
													var ddatei = current_select.attr('data-ddatei');
													var option_responsive = jQuery('#slideshow-holder').find('.ddate_day_option').find("a[data-ddatei='"+ddatei+"']");
													option_responsive.addClass('ddate_day_active');
													jQuery('> i', option_responsive).removeClass('fa-check').addClass('fa-thumbs-up');
													jQuery('#slideshow-holder').find("a[data-ddatei='"+ddatei+"']").addClass('ddate_day_active');
													current_select.addClass('ddate_day_active');
													jQuery('> i', current_select).removeClass('fa-check').addClass('fa-thumbs-up');

													var showdtimetext = jQuery(option_responsive).text();
													var showddate = jQuery(option_responsive).closest('li')
														.clone()    //clone the element
														.children('div') //select all the children
														.remove()   //remove all the children
														.end()  //again go back to selected element
														.text();


													jQuery('.deli_date').find('.ddate_day_selected').text('Sélectionner');
													jQuery(option_responsive).closest('.option_slot_select').find('.ddate_day_selected').text(showdtimetext);

													document.getElementById('showddate:date').innerHTML = showddate;
													document.getElementById('showddate:dtime').innerHTML = showdtimetext;

													jQuery('.ddate_selected').show();
													jQuery(option_responsive).parent().hide();

													if(jQuery('.block-delivery').hasClass('open')) {
														jQuery('.block-delivery').removeClass('open');
													}
												} else {
													jQuery(option_responsive).parent().hide();
												}
											}
										</script>
										<?php
										$currentTime = Mage::getSingleton('core/date')->timestamp();

										$weeks = $this->getNumberWeek();
										for ($w = 0; $w < $weeks; $w++):
											?>
											<div class="slideshow-content">

												<div class="deli_date_top deli_date_head">
													<ul>
													<?php
														for ($i = 7 * $w; $i < 7 * $w + 7; $i++) { $strDate = date('Y-m-d', strtotime('+' . $i . ' day', $currentTime));
															$date_FR = Mage::app()->getLocale()->date(strtotime('+' . $i . ' day', $currentTime));
														 ?>

															<li <?php if ($i % 2 != 0) echo 'class="oddrow"' ?>>
																<?php echo $date_FR->get(Zend_Date::WEEKDAY_SHORT);?>
																<div class="option_slot_select">
																	<p class="ddate_day_selected">Sélectionner</p>
																	<p class="ddate_day_option">
																		<?php foreach ($slots as $slot) :
																			if($this->isEnabled($slot->getId(), $strDate)) :?>
																				<a onclick="selectDdate('<?php echo date('Y-m-d', strtotime('+' . $i . ' day', $currentTime)) ?>','<?php echo $slot->getDtimeId(); ?>', this); selectDdateAct(jQuery(this));" data-ddatei="dd_<?php echo $slot->getId().'_'.$i; ?>"><?php echo $slot->getDtime(); ?></a>
																		<?php else: ?>
																				<a class="disablerow"><?php echo $slot->getDtime(); ?></a>
																		<?php endif; endforeach; ?>
																	</p>
																</div>

																<span><?php echo date(Mage::helper('ddate')->month_date_format(), strtotime('+' . $i . ' day', $currentTime)) ?></span>

															</li>
													<?php } ?>
													</ul>
												</div>
												<div class="deli_date_top select_one">
													<?php 
													foreach ($slots as $slot) :
													 ?>
														<ul>
														<div class="clear"><span></span></div>
															<?php
																for ($i = 7 * $w; $i < 7 * $w +7; $i++) {
																	$strDate = date('Y-m-d', strtotime('+' . $i . ' day', $currentTime));
																	if($this->isEnabled($slot->getId(), $strDate)){
																		$remliv=$this->getRemainingnumberofOrders($slot->getId(), $strDate);
																		?>
																		<li>
																			<a href="#select" onclick="selectDdate('<?php echo date('Y-m-d', strtotime('+' . $i . ' day', $currentTime)) ?>','<?php echo $slot->getDtimeId(); ?>', this); selectDdateAct(jQuery(this));" data-ddatei="dd_<?php echo $slot->getId().'_'.$i; ?>">
																				<i class="fa fa-check remliv-icon"></i><br>
																				Créneau Dispo</a>
																		</li>
																	<?php }else{ ?>
																		<li class="disablerow">
																			<span>
																				<i class="fa fa-close remliv-icon"></i><br>
																				Créneau Non Dispo
																			</span>
																		</li>
																	<?php
																	};
																}
																?>
															<div class="clear"><span></span></div>
														</ul>
													<?php endforeach; ?>
												</div>
											</div>
											<?php
										endfor;
										?>
									</div>
								</div>
							</div>
						</div>
						<div class="clear"><span></span></div>
					</div>
				</div>

				<div style="margin-top:20px;text-align:center;" class="ddate_selected">
					<div class="col-sm-6"><i class="fa fa-calendar" style="margin-right:5px"></i>Jour de livraison: <span id="showddate:date"></span></div>
					<div class="col-sm-6"><i class="fa fa-clock-o" style="margin-right:5px"></i>Horaire: <span id="showddate:dtime"></span></div>
				</div>
				<script type="text/javascript">
					jQuery(function ($) {
						var slot = document.getElementById('ddate:ddatei').value;
						if (slot) {
							initSelectDdate = true;
							$('#slideshow-holder').find("a[data-ddatei='"+slot+"']").click();
						}
					});
				</script>
			<?php }else { ?>
                <?php $availableDaysAndSlots = $this->getAvailableDaysAndSlots(); ?>
				<div class="delivery apdc_datetimepicker">
                    <div class="select-days">
                        <ul class="select-days">
                        <?php foreach ($availableDaysAndSlots as $strDate => $dayAndSlots) : ?>
                            <li class="<?php echo ($dayAndSlots['has_slot'] ? 'available' : 'not-available'); ?>" data-date="<?php echo $strDate; ?>">
                                <div>
                                    <span class="day"><?php echo $dayAndSlots['day']['day']; ?></span>
                                    <span class="date"><?php echo $dayAndSlots['day']['date']; ?></span>
                                </div>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="select-time hide">
                        <ul>
                        </ul>
                    </div>
                    <script type="text/javascript">
                        var apdc_ddateTimePicker = Apdc_DdateTimePicker({
                            'saveUrl': '<?php echo $this->getUrl('checkout/onepage/saveDdateAjax') ?>',
                            'redirectUrl': '<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>',
                            'daysAndSlots': <?php echo json_encode($availableDaysAndSlots); ?>,
                            'currentDate': '<?php echo Mage::getSingleton('core/session')->getDdate(); ?>',
                            'currentTime': '<?php echo Mage::getSingleton('core/session')->getDtime(); ?>'
                        });
                    </script>
                </div>
			<?php } ?>
			<div>
				<?php echo (Mage::getStoreConfig("ddate/info/description") ? Mage::getStoreConfig("ddate/info/description") : '') ?>
			</div>

			<div style="margin-top:10px; <?php if (!Mage::getStoreConfig("ddate/info/comment"))
				echo 'display:none;' ?>">
				<?php echo Mage::helper('ddate')->__('Your Comment') ?>: <br/>
				<textarea name="ddate[ddate_comment]" id="ddate:ddate_comment" rows="3" cols="55" value=''></textarea>
			</div>
		</fieldset>
	</div>
	<div class="clear"><span></span></div>

	<script type="text/javascript">
		//<![CDATA[
		var ddate = new Ddate('co-ddate-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveDdate') ?>');
		var ddateForm = new VarienForm('co-ddate-form');
		//]]>
	</script>
</div>
