<?php
/**
/ @author Pierre Mainguet
 */
?>

<?php 
    $str = Mage::getVersion();
    $version = Mage::helper('ddate')->checkVersion($str);
?>

<?php
	if (Mage::getSingleton('customer/session')->isLoggedIn()) {
		?>
			<div class="block block-progress opc-block-progress col-md-4 col-sm-12">
				<!--<div class="block-title">
					<strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
				</div>-->
				<div class="block-content">
					<?php if($version == "mg1.8" || $version == "mg1.9" || $version == "enterprise14"): ?>
						<dl>
							
							<div id="billing-progress-opcheckout">
								<?php echo $this->getChildHtml('billing.progress') ?>
							</div>
							
							<div id="shipping_method-progress-opcheckout">
								<?php echo $this->getChildHtml('shippingmethod.progress') ?>
							</div>
							
							<div id="checkcart-progress-opcheckout">
								<?php echo $this->getChildHtml('checkcart.progress') ?>
							</div>
							
							<div id="payment-progress-opcheckout">
								<?php echo $this->getChildHtml('payment.progress') ?>
							</div>
							
							<!--<div id="billing-progress-opcheckout">
								<?php echo $this->getChildHtml('billing.progress') ?>
							</div>-->
							<!--<div id="shipping-progress-opcheckout">
								<?php echo $this->getChildHtml('shipping.progress') ?>
							</div>-->
							
							<!--<div id="ddate-progress-opcheckout">
								<?php echo $this->getChildHtml('ddate.progress') ?>
							</div>-->
							
						</dl>
					<?php endif; ?>
				</div>
			</div>
		<?php
	}
?>