<?php
	$collection = $this->getAllSelections();
?>
<?php if($collection['count'] > 0) :?>
<div class="row apdc_home_selection">
	<div class="col-xs-12">
	    <div class="block-promos text-center container">
	        <div class="border-container"></div>
	    	<div class="inner-box" id="carrousel-selection-home">
                <h2 class="title-block"><?php echo $this->__('En ce moment chez vos commerçants'); ?></h2>
			    <div class="colored-line"></div>
				<div id="carrousel-selection-home-row1" class="owl-carousel apdc-products-grid">
					<?php
						foreach($collection['row1'] as $selection):
							$this->getChild("card-product")->setData("product", $selection);
							echo $this->getChildHtml('card-product', false);
							/*$productUrl = $selection->getProductUrl();
							$strippedName = $this->stripTags($selection->getName(), null, true);
							$imageLabel = $this->stripTags($this->getImageLabel($selection, 'small_image'), null, true);
							if ($selection->getConfigureMode() == true && $selection->getCartItemId() && $selection->getCartItemId() > 0) {
								$formAjaxUrl = $this->helper('apdccart')->getAjaxUpdateItemOptionsUrl($selection);
							}
							else {
								$formAjaxUrl = $this->helper('apdccart')->getAjaxAddUrl($selection);
							}
							echo '<div class="product-info row item">' ;
							?>
								<form action="<?php echo $productUrl; ?>"
									  method="post"
									  class="col-md-12 product-item-info apdc-add-to-cart-form product_addtocart_form_<?php echo $selection->getId(); ?>"
									  id="product_addtocart_form_<?php echo $selection->getId(); ?>"
									  data-product-id="<?php echo $selection->getId(); ?>"
									  data-ajax-action="<?php echo $formAjaxUrl; ?>">
									<a href="<?php echo $productUrl; ?>"
									   title="<?php echo $strippedName; ?>"
									   class="show-product-popup product-image"
									   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">

										<img src="<?= $this->helper('catalog/image')->init($selection, 'small_image')?>" width="200" height="125" alt="<?php echo $imageLabel; ?>" title="<?php echo $imageLabel; ?>" />
										<?php echo $this->getChild('product_labels')->setData('product', $selection)->toHtml(); ?>
									</a>
									<div class="product-info">
										<a href="<?php echo $productUrl; ?>"
										   title="<?php echo $strippedName; ?>"
										   class="show-product-popup"
										   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">
											<h3 class="product-name"><?= $selection->getName()?></h3>
										</a>
										<p class="product-portion"><?php echo $selection->getData('short_description'); ?></p>
										<!--<p class="product-commercant-name">
											<?php echo Mage::getResourceSingleton('catalog/product')
													->getAttribute('commercant')
													->getSource()
													->getOptionText($selection->getData('commercant')); ?>
										</p>-->
										<div class="bottom">
										    <?php echo $this->getPriceHtml($selection, true) ?>
                                            <?php if($selection->getData('prix_kilo_site')) :?>
                                                <div class="product-short_desc">
                                                    <?php echo $selection->getData('prix_kilo_site'); ?>
                                                </div>
                                            <?php endif; ?>
											<?php if($selection->isSaleable()): ?>
												<div class="actions add-to-cart">
													<div class="action-group">
														<div class="action-loading">
															<div class="loader"></div>
														</div>
														<div class="pull-right">
															<input type="hidden" class="selected-optionKey-<?php echo $selection->getId(); ?>" />
															<button type="submit" title="<?php echo $this->quoteEscape($this->__('Ajouter')) ?>" class="button btn-cart simple-add-to-cart-button"><span><span><i class="fa fa-cart-plus"></i> <?php echo $this->__('Ajouter') ?></span></span></button>
															<div class="qty-buttons">
																<button type="submit" value="btn-cart-qty-minus" title="<?php echo $this->quoteEscape($this->__('Remove one product')); ?>" class="button btn-cart btn-cart-qty-minus"><span><span><i class="fa fa-minus"></i></span></span></button>
																<button type="submit" value="btn-cart-remove" title="<?php echo $this->quoteEscape($this->__('Remove product from cart')); ?>" class="button btn-cart btn-cart-remove"><span><span><i class="fa fa-trash"></i></span></span></button>
																<span class="added-qty">0</span>
																<button type="submit" value="btn-cart-qty-plus" title="<?php echo $this->quoteEscape($this->__('Add one product')); ?>" class="button btn-cart btn-cart-qty-plus"><span><span><i class="fa fa-plus"></i></span></span></button>
															</div>
														</div>
													</div>
												</div>
											<?php endif; ?>
											<?php if ($selection->getConfigureMode() == true && $selection->getCartItemId() && $selection->getCartItemId() > 0) : ?>
												<?php $item = Mage::getModel('sales/quote_item')->load($selection->getCartItemId()); ?>
												<?php if ($item && $item->getId()) : ?>
													<div class="action update-product-options disabled">
														<input type="hidden" name="update_product_options" value="1" />
														<input type="hidden" name="update_product_options_initial_values" value="<?php echo (int)$selection->getQty() . '-' . $selection->getItemComment(); ?>" />
														<button type="submit" class="btn-success btn-sm apdc-catalog-update-product-options" data-item-id="<?php echo $selection->getCartItemId(); ?>" data-product-id="<?php echo $selection->getId(); ?>" title="<?php echo $this->__('Update product'); ?>" value="update_product_options" disabled="true">
															<span><span>
																<i class="fa fa-save"></i> <?php echo $this->__('Update product');  ?>
															</span></span>
														</button>
													</div>
												<?php endif; ?>
											<?php endif; ?>
                                                        <!--<a title="<?php echo $this->quoteEscape($this->__('Ajouter')) ?>" class="button button-green btn-cart show-product-popup" href="<?php echo $selection->getProductUrl() ?>" data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>"><i class="fa fa-cart-plus"></i> <?php echo $this->__('Ajouter') ?></a>
                                                    </div>
                                                </div>
                                            </div>-->
										</div>
									</div>
									<div class="display-hover">
										<p class="advice-must-select-options"><?php echo $this->__('Veuillez choisir une option pour pouvoir ajouter ce produit au panier'); ?></p>
										<?php
										// Provides extra blocks on which to hang some features for products in the list
										// Features providing UI elements targeting this block will display directly below the product name
										if ($this->getChild('name.after')) {
											$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
											foreach ($_nameAfterChildren as $_nameAfterChildName) {
												$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
												$_nameAfterChild->setProduct($selection);
												echo $_nameAfterChild->toHtml();
											}
										}
										?>
									</div>
								</form>
							<?php
							echo '</div>' ;*/
						endforeach;
					?>
				</div>
				<div id="carrousel-selection-home-row2" class="owl-carousel apdc-products-grid">
					<?php
						foreach($collection['row2'] as $selection):
                            $this->getChild("card-product")->setData("product", $selection);
							echo $this->getChildHtml('card-product', false);
							/*$productUrl = $selection->getProductUrl();
							$strippedName = $this->stripTags($selection->getName(), null, true);
							$imageLabel = $this->stripTags($this->getImageLabel($selection, 'small_image'), null, true);
							if ($selection->getConfigureMode() == true && $selection->getCartItemId() && $selection->getCartItemId() > 0) {
								$formAjaxUrl = $this->helper('apdccart')->getAjaxUpdateItemOptionsUrl($selection);
							}
							else {
								$formAjaxUrl = $this->helper('apdccart')->getAjaxAddUrl($selection);
							}
							echo '<div class="product-info row item">' ;
							?>
								<form action="<?php echo $productUrl; ?>"
									  method="post"
									  class="col-md-12 product-item-info apdc-add-to-cart-form product_addtocart_form_<?php echo $selection['product_id']; ?>"
									  id="product_addtocart_form_<?php echo $selection->getId(); ?>"
									  data-product-id="<?php echo $selection->getId(); ?>"
									  data-ajax-action="<?php echo $formAjaxUrl; ?>">

									<a href="<?php echo $productUrl; ?>"
									   title="<?php echo $strippedName; ?>"
									   class="show-product-popup product-image"
									   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">

										<img src="<?= $this->helper('catalog/image')->init($selection, 'small_image')?>" width="200" height="125" alt="<?php echo $imageLabel; ?>" title="<?php echo $imageLabel; ?>" />
										<?php echo $this->getChild('product_labels')->setData('product', $selection)->toHtml(); ?>
									</a>
									<div class="product-info">
										<a href="<?php echo $productUrl; ?>"
										   title="<?php echo $strippedName; ?>"
										   class="show-product-popup"
										   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">
											<h3 class="product-name"><?= $selection->getName()?></h3>
										</a>
										<p class="product-portion"><?php echo $selection->getData('short_description'); ?></p>
										<!--<p class="product-commercant-name">
											<?php echo Mage::getResourceSingleton('catalog/product')
													->getAttribute('commercant')
													->getSource()
													->getOptionText($selection->getData('commercant')); ?>
										</p>-->
										<div class="bottom">
										    <?php echo $this->getPriceHtml($selection, true) ?>
                                            <?php if($selection->getData('prix_kilo_site')) :?>
                                                <div class="product-short_desc">
                                                    <?php echo $selection->getData('prix_kilo_site'); ?>
                                                </div>
                                            <?php endif; ?>
											<?php if($selection->isSaleable()): ?>
												<div class="actions add-to-cart">
													<div class="action-group">
														<div class="action-loading">
															<div class="loader"></div>
														</div>
														<div class="pull-right">
															<input type="hidden" class="selected-optionKey-<?php echo $selection->getId(); ?>" />
															<button type="submit" title="<?php echo $this->quoteEscape($this->__('Ajouter')) ?>" class="button btn-cart simple-add-to-cart-button"><span><span><i class="fa fa-cart-plus"></i> <?php echo $this->__('Ajouter') ?></span></span></button>
															<div class="qty-buttons">
																<button type="submit" value="btn-cart-qty-minus" title="<?php echo $this->quoteEscape($this->__('Remove one product')); ?>" class="button btn-cart btn-cart-qty-minus"><span><span><i class="fa fa-minus"></i></span></span></button>
																<button type="submit" value="btn-cart-remove" title="<?php echo $this->quoteEscape($this->__('Remove product from cart')); ?>" class="button btn-cart btn-cart-remove"><span><span><i class="fa fa-trash"></i></span></span></button>
																<span class="added-qty">0</span>
																<button type="submit" value="btn-cart-qty-plus" title="<?php echo $this->quoteEscape($this->__('Add one product')); ?>" class="button btn-cart btn-cart-qty-plus"><span><span><i class="fa fa-plus"></i></span></span></button>
															</div>
														</div>
													</div>
												</div>
											<?php endif; ?>
											<?php if ($selection->getConfigureMode() == true && $selection->getCartItemId() && $selection->getCartItemId() > 0) : ?>
												<?php $item = Mage::getModel('sales/quote_item')->load($selection->getCartItemId()); ?>
												<?php if ($item && $item->getId()) : ?>
													<div class="action update-product-options disabled">
														<input type="hidden" name="update_product_options" value="1" />
														<input type="hidden" name="update_product_options_initial_values" value="<?php echo (int)$selection->getQty() . '-' . $selection->getItemComment(); ?>" />
														<button type="submit" class="btn-success btn-sm apdc-catalog-update-product-options" data-item-id="<?php echo $selection->getCartItemId(); ?>" data-product-id="<?php echo $selection->getId(); ?>" title="<?php echo $this->__('Update product'); ?>" value="update_product_options" disabled="true">
															<span><span>
																<i class="fa fa-save"></i> <?php echo $this->__('Update product');  ?>
															</span></span>
														</button>
													</div>
												<?php endif; ?>
											<?php endif; ?>
                                            <!--<div class="actions">
                                                <div class="action-group">
                                                    <div>
                                                        <a title="<?php echo $this->quoteEscape($this->__('Ajouter')) ?>" class="button button-green btn-cart show-product-popup" href="<?php echo $selection->getProductUrl() ?>" data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>"><i class="fa fa-cart-plus"></i> <?php echo $this->__('Ajouter') ?></a>
                                                    </div>
                                                </div>
                                            </div>-->
										</div>
									</div>
									<div class="display-hover">
										<p class="advice-must-select-options"><?php echo $this->__('Veuillez choisir une option pour pouvoir ajouter ce produit au panier'); ?></p>
										<?php
										// Provides extra blocks on which to hang some features for products in the list
										// Features providing UI elements targeting this block will display directly below the product name
										if ($this->getChild('name.after')) {
											$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
											foreach ($_nameAfterChildren as $_nameAfterChildName) {
												$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
												$_nameAfterChild->setProduct($selection);
												echo $_nameAfterChild->toHtml();
											}
										}
										?>
									</div>
								</form>
							<?php
							echo '</div>' ;*/
						endforeach;
					?>
				</div>
				<div class="owl-buttons">
				    <a href="#" class="prev"><i class="fa fa-angle-left"></i></a>
				    <a href="#" class="next"><i class="fa fa-angle-right"></i></a>
				</div>
		    </div>
	    </div>
	</div>
</div>
<script>
    $j(document).ready(function() {
		
		var optionsOwlCarouselSelectionHome = {
			slideBy: 'page',
			items:8,
			autoPlay : false,
			loop: true,
			slideSpeed : 800,
			responsive: {
				0:{
					items:1,
					slideBy: 1,
				},
                500:{
					items:2,
					slideBy: 2,
				},
                740:{
					items:4,
					slideBy: 4,
				},
				1200:{
					items:5,
					slideBy: 5,
				}
			}	
		};
		
		var owlCarouselSelectionHomeRow1 = $j("#carrousel-selection-home-row1").owlCarousel(optionsOwlCarouselSelectionHome);
		var owlCarouselSelectionHomeRow2 = $j("#carrousel-selection-home-row2").owlCarousel(optionsOwlCarouselSelectionHome);
		
		$j("#carrousel-selection-home .prev").click(function (evt) {
			evt.preventDefault();
			owlCarouselSelectionHomeRow1.trigger('prev.owl.carousel');
			owlCarouselSelectionHomeRow2.trigger('prev.owl.carousel');
		});

		$j("#carrousel-selection-home .next").click(function (evt) {
			evt.preventDefault();
			owlCarouselSelectionHomeRow1.trigger('next.owl.carousel');
			owlCarouselSelectionHomeRow2.trigger('next.owl.carousel');
		});
        
        $j('.block-promos .apdc-products-grid .owl-item').hover(function(){
            $j(this).css({'margin-bottom' : -$j(' > .product-info .display-hover', this).outerHeight()+'px'});
        });
		
    });
</script>
<?php endif;?>
