<?php
	$currentCat = Mage::registry('current_category');
	$collection = $this->getSelectionById($currentCat->getId());
    $shop_info = $this->getData('shop_info');
?>
<?php if($collection->count() > 0) :?>
<div class="row apdc_home_selection">
	<div class="col-md-12">
	    <div class="block-promos text-center">
	    	<div class="inner-box">
                <div class="title-block"><?php echo sprintf($this->__('La sélection de %s'), $shop_info['name']); ?></div>
			    <div class="colored-line"></div>
			    	<ul id="carrousel-selection-home" class="owl-carousel apdc-products-grid apdc-all-products-slider-by-commercant">
				    	<?php foreach($collection as $selection):?>
							<?php
								$this->getChild("card-product")->setData("product", $selection);
								echo $this->getChildHtml('card-product', false);
							?>
							<?php /*
								<?php $productUrl = $selection->getProductUrl(); ?>
								<?php $strippedName = $this->stripTags($selection->getName(), null, true); ?>
								<?php $imageLabel = $this->stripTags($this->getImageLabel($selection, 'small_image'), null, true); ?>
								<li class="product-info item">
									<form action="<?php echo $productUrl; ?>"
										  method="post"
										  class="product-item-info apdc-add-to-cart-form product_addtocart_form_<?php echo $selection['product_id']; ?>"
										  id="product_addtocart_form_<?php echo $selection->getId(); ?>"
										  data-product-id="<?php echo $selection->getId(); ?>">

										<a href="<?php echo $productUrl; ?>"
										   title="<?php echo $strippedName; ?>"
										   class="show-product-popup product-image"
										   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">

											<img src="<?= $this->helper('catalog/image')->init($selection, 'small_image')->resize(250, 250)?>" width="250" height="250" alt="<?php echo $imageLabel; ?>" title="<?php echo $imageLabel; ?>" />
											<?php echo $this->getChild('product_labels')->setData('product', $selection)->toHtml(); ?>
										</a>
										<div class="product-info row">
											<a href="<?php echo $productUrl; ?>"
											   title="<?php echo $strippedName; ?>"
											   class="show-product-popup"
											   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">
												<h2 class="product-name"><?= $selection->getName()?></h2>
											</a>
											<div class="product-info-left product-info-column">

												<p class="product-commercant-name">
													<?php echo Mage::getResourceSingleton('catalog/product')
															->getAttribute('commercant')
															->getSource()
															->getOptionText($selection->getData('commercant')); ?>
												</p>

											</div>
											<div class="product-info-right product-info-column">
												<?php echo $this->getPriceHtml($selection, true) ?>
												<?php if($selection->getData('prix_kilo_site')) :?>
													<div class="product-short_desc">
														<?php echo $selection->getData('prix_kilo_site'); ?>
													</div>
												<?php endif; ?>
											</div>
											<div class="actions">
												<div class="action-group pull-right">
													<div>
														<a title="<?php echo $this->quoteEscape($this->__('Ajouter')) ?>" class="col-xs-12 button btn-cart show-product-popup" href="<?php echo $selection->getProductUrl() ?>" data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>"><i class="fa fa-cart-plus"></i> <?php echo $this->__('Ajouter') ?></a>
													</div>
												</div>
											</div>
										</div>
									</form>
								</li>
								 *
								 */
							?>
				    	<?php endforeach;?>
				    </ul>
		    </div>
	    </div>
	</div>
</div>
<script>
    $j(document).ready(function() {

		$j("#carrousel-selection-home").owlCarousel({
			  items:5,
			  itemsScaleUp : true,
			  pagination:false,
			  autoPlay : false,
			  autoHeight: false,
			  nav : true,
			  navText: ['<i class="fa fa-angle-left"></i>', '<i class="fa fa-angle-right"></i>'],
			  navContainerClass: 'owl-nav owl-nav-apdc-all-products-slider-by-commercant',
			  afterInit:function() {
				  alignProductGridActions();
			  },
			  responsive: {
				  0:{
					  items:1,
					  slideBy: 1,
				  },
				  480:{
					  items:2,
					  slideBy: 2,
				  },
				  640:{
					  items:4,
					  slideBy: 4,
				  },
				  980:{
					  items:4,
					  slideBy: 4,
				  }
			  }
		});

		$j('.block-promos .apdc-products-grid .owl-item').hover(
			function(){
				if($j('.display-hover', this).outerHeight() > 0) {
					$j(this).css({'margin-bottom' : -$j('.display-hover', this).outerHeight()+'px'});
				}
			},
			function(){
				$j(this).css({'margin-bottom' : 0});
			}
		);

    });
</script>
<?php endif;?>
