<?php
/**
 * Hipay
 *
 * NOTICE OF LICENSE
 *
 * Copyright (c) 2010, HPME - HI-MEDIA PORTE MONNAIE ELECTRONIQUE (Groupe Hi-Media, Seed Factory, 19 Avenue des Volontaires, 1160 Bruxelles - Belgium)
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 *  - Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 *  - Neither the name of the Hipay and HPME - HI-MEDIA PORTE MONNAIE ELECTRONIQUE 
 *    nor the names of its contributors may be used to endorse or promote products 
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   Paymentnetwork
 * @package    Paymentnetwork_Hipay
 * @copyright  Copyright (c) 2010 HPME - HI-MEDIA PORTE MONNAIE ELECTRONIQUE
 * @license    http://www.opensource.org/licenses/bsd-license.php  The BSD License
 */ 
?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Raleway:300,400,500,700,600" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Courgette" />
<style type="text/css">

body {
	text-align:center !important;
	font-family: Raleway, "Helvetica Neue", Verdana, Arial, sans-serif;
    color: #222;
    font-size: 16px;
    line-height: 1.5;
}

.main_message{
	font-weight: bold;
	font-size:20px;
}

.subtitle{
	font-style:italic;
}

.logo{
	display: block;
    height: 50px;
    margin-left: -90px;
    position: absolute;
    top: 50px;
    left: 50%;
}

.logo img{
	width: 180px;
}

#storename{
	color: rgb(51, 153, 51);
    font-family: Courgette, Montserrat, Raleway, Verdana;
    font-size: 18px;
    left: 100px;
    position: relative;
    text-align: center;
    top: -65px;
}

.hipay_centered_content {
	width:620px; 
	margin:0px auto; 
	text-align:left;
}

.hipay_redirect_infobox_content {
	margin-top: 155px;
	text-align: center;
}

.hipay_redirect_infobox_content span {
	color: #666666;
	font-size: 16px;
	font-weight: bold;
}

.show_loader_image {
	background:url("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/images/himediapayments/hipay/loader.gif") no-repeat scroll transparent;
	padding-left: 25px;
}

</style>
<div class="hipay_centered_content">
	<div class="logo">
        <img src="<?php echo Mage::getBaseUrl();?>../skin/frontend/rwd/commis/images/logo-green.png" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
        <div id="storename"><?php echo Mage::app()->getStore()->getName();?></div>
    </div>
	<div class="hipay_redirect_infobox_content">
		<p class="main_message"><span <?php if(!empty($paymentUrl)) { ?>class="show_loader_image"<?php }; ?>></span> Un instant s'il vous plaît.</p>
		<p>Vous allez être redirigé vers la page de paiement de notre partenaire</p>
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/images/himediapayments/hipay/hipay_wallet_mg_logo.jpg" />
		<p class="subtitle">Merci de ne pas fermer cette page et de ne pas revenir en arrière.</p>
	</div>
</div>

<?php if(!empty($paymentUrl)) { ?>
	<script type="text/javascript">parent.location.href="<?php echo $paymentUrl ?>";</script>
<?php }; ?>