<?php 
$availability = $this->getAvailability();
?>
<?php if (!empty($availability)) : ?>
<?php $header = ''; ?>
<?php $body = ''; ?>
<div class="delivery_days">
    <h3 class="delivery_days_title"><?php echo $this->__('Livraison possible le'); ?></h3>
    <?php foreach($this->getWeekDays() as $weekDay): ?>
        <?php if (is_null($weekDay['value']) || !in_array($weekDay['value'], $availability)) : ?>
            <?php $classHeader = 'no'; ?>
            <?php $body .= '<td><i class="fa fa-close"></i></td>'; ?>
        <?php else : ?>
            <?php $classHeader = 'yes'; ?>
            <?php $body .= '<td><i class="fa fa-check"></i></td>'; ?>
        <?php endif; ?>
        <?php $header .= '<th class="' . $classHeader . '">' . $weekDay['label'] . '</th>'; ?> 
    <?php endforeach; ?>
    <div>
        <table>
            <thead>
                <tr><?php echo $header; ?></tr>
            </thead>
            <tbody>
                <tr><?php echo $body; ?></tr>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>
