<?php
	$product = $this->getProduct();
	$productUrl = $product->getProductUrl();
	$strippedName = $this->stripTags($product->getName(), null, true);
    if (strlen($strippedName) > 36) {
        $strippedName = substr($strippedName, 0, 36) . '...';
    }
	$imageLabel = $this->stripTags($this->getImageLabel($product, 'small_image'), null, true);
	if ($product->getConfigureMode() == true && $product->getCartItemId() && $product->getCartItemId() > 0) {
		$formAjaxUrl = $this->helper('apdccart')->getAjaxUpdateItemOptionsUrl($product);
	} else {
		$formAjaxUrl = $this->helper('apdccart')->getAjaxAddUrl($product);
	}
	$uniqidCard = uniqid('card-');
    $availability = $this->getAvailability();
?>
<div class="product-info row item <?php echo ($this->isCategoryPage() ? ' col-xs-6 col-sm-12' : ''); ?> <?php echo (!$availability['is_available_for_sale'] ? ' notavailable' : ''); ?>" style="margin-bottom: 0px;">
	<form action="<?php echo $productUrl; ?>"
		  method="post"
		  class="product-item-info apdc-add-to-cart-form product_addtocart_form_<?php echo $product->getId(); ?>"
		  id="product_addtocart_form_<?php echo $product->getId().$uniqidCard; ?>"
		  data-product-id="<?php echo $product->getId(); ?>"
		  data-ajax-action="<?php echo $formAjaxUrl; ?>">

        <?php $productAvailabilityMessage = $this->getChild('product_availability_message'); ?>
        <?php if ($productAvailabilityMessage) : ?>
            <?php echo $productAvailabilityMessage->setData('product', $product)->toHtml(); ?>
        <?php endif; ?>
		<a href="<?php echo $productUrl; ?>"
		   title="<?php echo $strippedName; ?>"
		   class="show-product-popup product-image"
		   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">

			<img src="<?= $this->helper('catalog/image')->init($product, 'small_image')?>" width="200" height="125" alt="<?php echo $imageLabel; ?>" title="<?php echo $imageLabel; ?>" />
			<?php echo $this->getChild('product_labels')->setData('product', $product)->toHtml(); ?>
		</a>
		<div class="product-info">
			<a href="<?php echo $productUrl; ?>"
			   title="<?php echo $strippedName; ?>"
			   class="show-product-popup"
			   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">
				<h3 class="product-name"><?php echo $strippedName; ?></h3>
			</a>
			<p class="product-portion"><?php echo $product->getData('short_description'); ?></p>
			<p class="product-commercant-name">
				<?php echo Mage::getResourceSingleton('catalog/product')
						->getAttribute('commercant')
						->getSource()
						->getOptionText($product->getData('commercant')); ?>
			</p>
			<div class="bottom">
				<?php echo $this->getPriceHtml($product, true) ?>
				<?php if($product->getData('prix_kilo_site')) :?>
					<div class="product-short_desc">
						<?php echo $product->getData('prix_kilo_site'); ?>
					</div>
				<?php endif; ?>
                <?php echo $this->getChild('product_actions')->setProduct($product)->toHtml(); ?>
				<?php if ($product->getConfigureMode() == true && $product->getCartItemId() && $product->getCartItemId() > 0) : ?>
					<?php $item = Mage::getModel('sales/quote_item')->load($product->getCartItemId()); ?>
					<?php if ($item && $item->getId()) : ?>
						<div class="action update-product-options disabled">
							<input type="hidden" name="update_product_options" value="1" />
							<input type="hidden" name="update_product_options_initial_values" value="<?php echo (int)$product->getQty() . '-' . $product->getItemComment(); ?>" />
							<button type="submit" class="button button-green btn-sm apdc-catalog-update-product-options" data-item-id="<?php echo $product->getCartItemId(); ?>" data-product-id="<?php echo $product->getId(); ?>" title="<?php echo $this->__('Update product'); ?>" value="update_product_options" disabled="true">
								<span><span>
									<i class="fa fa-save"></i> <?php echo $this->__('Update product');  ?>
								</span></span>
							</button>
						</div>
					<?php endif; ?>
				<?php endif; ?>
				<?php echo $product->getCommercantName(); ?>
			</div>
		</div>
		<div class="display-hover">
			<p class="advice-must-select-options"><?php echo $this->__('Veuillez choisir une option'); ?></p>
			<?php
				if ($this->getChild('name.after')) {
					$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
					foreach ($_nameAfterChildren as $_nameAfterChildName) {
						$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
						$_nameAfterChild->setProduct($product);
						echo $_nameAfterChild->toHtml();
					}
				}
				else if ($this->getChild('name.after2')) {
					$_nameAfterChildren = $this->getChild('name.after2')->getSortedChildren();
					foreach ($_nameAfterChildren as $_nameAfterChildName) {
						$_nameAfterChild = $this->getChild('name.after2')->getChild($_nameAfterChildName);
						$_nameAfterChild->setProduct($product);
						echo $_nameAfterChild->toHtml();
					}
				}
			?>
		</div>
	</form>
</div>
