<?php
	$product = $this->getData('product');
	$productUrl = $product->getProductUrl();
	$strippedName = $this->stripTags($product->getName(), null, true);
	$imageLabel = $this->stripTags($this->getImageLabel($product, 'small_image'), null, true);
	if ($product->getConfigureMode() == true && $product->getCartItemId() && $product->getCartItemId() > 0) {
		$formAjaxUrl = $this->helper('apdccart')->getAjaxUpdateItemOptionsUrl($product);
	}
	else {
		$formAjaxUrl = $this->helper('apdccart')->getAjaxAddUrl($product);
	}
?>
<div class="product-info row item">
	<form action="<?php echo $productUrl; ?>"
		  method="post"
		  class="col-md-12 product-item-info apdc-add-to-cart-form product_addtocart_form_<?php echo $product->getId(); ?>"
		  id="product_addtocart_form_<?php echo $product->getId(); ?>"
		  data-product-id="<?php echo $product->getId(); ?>"
		  data-ajax-action="<?php echo $formAjaxUrl; ?>">
		<a href="<?php echo $productUrl; ?>"
		   title="<?php echo $strippedName; ?>"
		   class="show-product-popup product-image"
		   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">

			<img src="<?= $this->helper('catalog/image')->init($product, 'small_image')?>" width="200" height="125" alt="<?php echo $imageLabel; ?>" title="<?php echo $imageLabel; ?>" />
			<?php echo $this->getChild('product_labels')->setData('product', $product)->toHtml(); ?>
		</a>
		<div class="product-info">
			<a href="<?php echo $productUrl; ?>"
			   title="<?php echo $strippedName; ?>"
			   class="show-product-popup"
			   data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>">
				<h3 class="product-name"><?= $product->getName()?></h3>
			</a>
			<p class="product-portion"><?php echo $product->getData('short_description'); ?></p>
			<!--<p class="product-commercant-name">
				<?php echo Mage::getResourceSingleton('catalog/product')
						->getAttribute('commercant')
						->getSource()
						->getOptionText($product->getData('commercant')); ?>
			</p>-->
			<div class="bottom">
				<?php echo $this->getPriceHtml($product, true) ?>
				<?php if($product->getData('prix_kilo_site')) :?>
					<div class="product-short_desc">
						<?php echo $product->getData('prix_kilo_site'); ?>
					</div>
				<?php endif; ?>
				<?php if($product->isSaleable()): ?>
					<div class="actions add-to-cart">
						<div class="action-group">
							<div class="action-loading">
								<div class="loader"><img src="<?php echo $this->getSkinUrl('dist/images/opc-ajax-loader.gif') ?>" alt=""></div>
							</div>
							<div class="pull-right">
								<input type="hidden" class="selected-optionKey-<?php echo $product->getId(); ?>" />
								<button type="submit" title="<?php echo $this->quoteEscape($this->__('Ajouter')) ?>" class="button button-green btn-cart simple-add-to-cart-button"><span><span><img src="<?php echo $this->getSkinUrl('dist/images/icon-shopping.png') ?>" alt=""> <?php echo $this->__('Ajouter') ?></span></span></button>
								<div class="qty-buttons">
									<button type="submit" value="btn-cart-qty-minus" title="<?php echo $this->quoteEscape($this->__('Remove one product')); ?>" class="button button-green btn-cart btn-cart-qty-minus"><span><span><i class="fa fa-minus"></i></span></span></button>
									<button type="submit" value="btn-cart-remove" title="<?php echo $this->quoteEscape($this->__('Remove product from cart')); ?>" class="button button-orange btn-cart btn-cart-remove"><span><span><i class="fa fa-trash"></i></span></span></button>
									<span class="added-qty">0</span>
									<button type="submit" value="btn-cart-qty-plus" title="<?php echo $this->quoteEscape($this->__('Add one product')); ?>" class="button button-green btn-cart btn-cart-qty-plus"><span><span><i class="fa fa-plus"></i></span></span></button>
								</div>
							</div>
						</div>
					</div>
				<?php endif; ?>
				<?php if ($product->getConfigureMode() == true && $product->getCartItemId() && $product->getCartItemId() > 0) : ?>
					<?php $item = Mage::getModel('sales/quote_item')->load($product->getCartItemId()); ?>
					<?php if ($item && $item->getId()) : ?>
						<div class="action update-product-options disabled">
							<input type="hidden" name="update_product_options" value="1" />
							<input type="hidden" name="update_product_options_initial_values" value="<?php echo (int)$product->getQty() . '-' . $product->getItemComment(); ?>" />
							<button type="submit" class="btn-success btn-sm apdc-catalog-update-product-options" data-item-id="<?php echo $product->getCartItemId(); ?>" data-product-id="<?php echo $product->getId(); ?>" title="<?php echo $this->__('Update product'); ?>" value="update_product_options" disabled="true">
								<span><span>
									<i class="fa fa-save"></i> <?php echo $this->__('Update product');  ?>
								</span></span>
							</button>
						</div>
					<?php endif; ?>
				<?php endif; ?>
			</div>
		</div>
		<div class="display-hover">
			<p class="advice-must-select-options"><?php echo $this->__('Veuillez choisir une option'); ?></p>
			<?php
			if ($this->getChild('name.after')) {
				$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
				foreach ($_nameAfterChildren as $_nameAfterChildName) {
					$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
					$_nameAfterChild->setProduct($product);
					echo $_nameAfterChild->toHtml();
				}
			}
			?>
		</div>
	</form>
</div>
