<div class="container">
	<div id='login'>
		<?= $this->form()->openTag($form).PHP_EOL ?>
		<?= "<div class='form-group'>".$this->formRow($form->get('username'))."</div>".PHP_EOL ?>
		<?= "<div class='form-group'>".$this->formRow($form->get('password'))."</div>".PHP_EOL?>
		<?= "<div class='form-group'>".$this->formRow($form->get('submit'))."</div>".PHP_EOL ?>
		<?= $this->form()->closeTag().PHP_EOL ?>
	</div>
</div>
