<li class="control remember-me-box">
    <?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
    <div class="input-box">
        <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->quoteEscape($this->__('Remember Me')) ?>" />
    </div>
    <label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Remember Me') ?></label>
</li>
