<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattach
 */
?>
<?php
$order                   = Mage::registry('current_order');
$field = Mage::getModel('amorderattach/field')->load('ticket_commercant', 'code');
$content= Mage::getModel('amorderattach/order_field')->load(615, 'order_id')->getTicketCommercant();

if($field->getCustomerVisibility()=="view"):
?>
<div class="row">
    <div class="col-sm-12">
        <h2><?php echo $this->__('Tickets Commerçants') ?></h2>
        <?php
        if (!is_array($content)) {
            $val = explode(';', $content);
        }
        ?>
        <ul>
            <?php foreach ($val as $img): ?>
                    <li>Voir les tickets: <a href="<?php echo $this->getUrl('attaches/order/download', array('file' => $img, 'customer_id' => Mage::getSingleton('customer/session')->getCustomerId())); ?>"><?php echo $img; ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif;?>
</div>
<div class="row">
    <div class="col-sm-12 buttons-set">
        <p class="back-link"><a href="<?php echo Mage::getUrl('sales/order/history') ?>"><small>&laquo; </small>Revenir à la liste des commandes</a></p>
    </div>
</div>