<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattach
 */
?>
<?php
$order = Mage::registry('current_order');
$field = Mage::getModel('amorderattach/field')->load('ticket_commercant', 'code');
$content= Mage::getModel('amorderattach/order_field')->load($order->getId(), 'order_id')->getTicketCommercant();

if($field->getCustomerVisibility()=="view"):
?>
<div class="row">
    <div class="col-sm-12">
        <?php
        if (!is_array($content)) {
            $val = explode(';', $content);
        }
        ?>
        <ul>
            <?php foreach ($val as $img): ?>
                    <li>Voir les tickets commerçants:
                        <?php if($img<>""):
                            $url_src=$this->getUrl('attaches/order/download', array('file' => $img, 'customer_id' => Mage::getSingleton('customer/session')->getCustomerId()));
                            ?>
                            <a href="<?= $url_src?>"><img class="ticket_commercant" src="<?= $url_src?>"/></a>
                        <?php else:?>
                            <span>Pas de tickets (pour l'instant)</span>
                        <?php endif;?>
                    </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif;?>
</div>