<?php $_order = $this->getOrder() ;?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-head button-level">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?>
        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
        </br><a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-cart"><?php echo $this->__('Reorder') ?></a>
    <?php endif ?>
    </h1>
</div>
<h2 class="table-caption"><?php echo $this->__('Informations générales') ?></h2>
<div class="row">
    <div class="col-sm-6">
        <ul>
            <?php
                $ddate = Mage::getResourceModel('ddate/ddate')->getDdateByOrder($this->getOrder()->getIncrementId());
                if($ddate):
            ?>
                <li><strong><?php echo Mage::helper('ddate')->__('Date de livraison: ') ?></strong><?php echo Mage::helper('ddate')->format_ddate($ddate['ddate']);?></li>
                <li><strong><?php echo Mage::helper('ddate')->__('Créneau de livraison: ') ?></strong><?php if(!empty($ddate['dtime'])) { echo $ddate['dtime']; } else echo $ddate['dtimetext'] ;?></li>
            <?php endif;?>
        </ul>
    </div>
    <div class="col-sm-6">
        <ul>
            <li><strong><?php echo $this->__('Méthode de paiement: ') ?></strong><?php echo $this->getPaymentInfoHtml() ?></li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <strong><?php echo $this->__('Votre adresse de livraison') ?></strong>
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
    <div class="col-sm-6">
        <strong><?php echo $this->__('Votre adresse de facturation') ?></strong>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
</div>