<?php $refund_totals=Mage::helper('pmainguet_delivery')->getRefundorderdata($this->getOrder());
	$total=0;
	$_order=$this->getOrder();
?>
<h3>VOS REMBOURSEMENTS</h3>
<table class="table data-table" id="my-orders-table">
    <?php foreach($refund_totals as $refund):?>
        <tr>
        	<td><?php echo $refund["commercant"];?></td>
        	<td><?php echo $_order->formatPrice($refund["del_amount_refunded"]);?></td>
        </tr>
        <?php $total+=$refund["del_amount_refunded"];?>
    <?php endforeach;?>
     <tr>
        <td><strong>TOTAL REMBOURSEMENTS</strong></td>
        <td><strong><?php echo $_order->formatPrice($total) ?></strong></td>
     </tr>
</table>