<?php
	$i = mt_rand(1, 14); // generate random number size of the array
	$url = "dist/images/header/".$i.".jpg"; // set variable equal to which random filename was chosen
    $_helper=Mage::helper('apdccustomer');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
	<?php echo $this->getChildHtml('head') ?>
</head>
<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
	<?php echo $this->getChildHtml('after_body_start') ?>
	<header class="header" id="faites-vos-courses">
        <div id="background_video_container">
            <video id="background_video_video" autoplay muted loop poster="<?php echo $this->getSkinUrl($url);?>">
                <source src="<?php echo $this->getSkinUrl('media/commercants.webm');?>" type="video/webm" />
                <source src="<?php echo $this->getSkinUrl('media/commercants.mp4');?>" type="video/mp4" />
            </video>
            <img class="banner" src="<?php echo $this->getSkinUrl($url);?>" alt="Au pas de courses">
        </div>
        <div class="container">
            <ul class="top-nav">
                <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Aide">Aide</a></li>
                <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                    <li><a href="#" class="button button-green" id="account-login" data-login-view="<?php echo $this->getUrl('apdc-customer/account/ajaxPopupView');?>" role="button" title="Connexion">Connexion</a></li>
                <?php else: ?>
                    <li><a href="<?= $_helper->getCustomerWebsite()?>" class="button button-green" role="button" title="Mon Quartier">Mon Quartier</a></li>
                <?php endif ?>
            </ul>
            <div class="intro-section">
                <img id="logo" src="<?php echo $this->getSkinUrl('dist/images/logo@2x.png')?>" alt="Logo Au Pas De Courses">
                <h1 class="intro">Faites-vous livrer les bons produits de votre quartier.</h1>
                <div class="col-md-5"></div>
            </div>
        </div>
	</header>
<section id="districts">
	<div class="container">
	    <div class="border-container"></div>
		<div class="section-header">
			<h2>Mon quartier</h2>
			<div class="section-description">
				 Les meilleurs commerçants de Paris livrés chez vous.
			</div>
		</div>
		<div class="row">
			<div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../batignolles';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris9e.jpg');?>" alt="Au Pas De Courses - 9e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 9<sup>e</sup></span>
                </a>
            </div>
            <div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../saintmartin';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris10e.jpg');?>" alt="Au Pas De Courses - 10e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 10<sup>e</sup></span>
                </a>
            </div>
            <div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../saintmartin';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris11e.jpg');?>" alt="Au Pas De Courses - 11e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 11<sup>e</sup></span>
                </a>
            </div>
			<div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../paris13e';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris13e.jpg');?>" alt="Au Pas De Courses - 13e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 13<sup>e</sup></span>
                </a>
            </div>
            <div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../paris14e';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris14e.jpg');?>" alt="Au Pas De Courses - 14e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 14<sup>e</sup></span>
                </a>
            </div>
			<div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../commerce';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris15e.jpg');?>" alt="Au Pas De Courses - 14e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 15<sup>e</sup></span>
                </a>
            </div>
            <div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../paris16e';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris16e.jpg');?>" alt="Au Pas De Courses - 16e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 16<sup>e</sup></span>
                </a>
            </div>
            <div class="button-district col-xs-12 col-sm-6 col-md-3">
                <a href="<?php echo Mage::getBaseUrl().'../batignolles';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris17e.jpg');?>" alt="Au Pas De Courses - 17e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 17<sup>e</sup></span>
                </a>
            </div>
            <div class="button-district col-xs-12">
                <a href="<?php echo Mage::getBaseUrl().'../batignolles';?>">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris18e.jpg');?>" alt="Au Pas De Courses - 18e arrondissement de Paris" class="img-circle"/>
                    <span class="button">Paris 18<sup>e</sup></span>
                </a>
            </div>
             <!-- <div class="button-district col-xs-12 col-sm-6">
                <a href="javascript: void(0)">
                    <img src="<?php echo $this->getSkinUrl('dist/images/quartiers/paris7e.jpg');?>" alt="Au Pas De Courses - Paris" class="img-circle"/>
                    <span class="button">Bientôt</span>
                </a>
            </div> -->
        </div>
		<!-- <div class="row text-center">
		    <h2 class="soon">Pas encore chez vous?</h2>
			<a class="button button-green" href="#" title="Restez informés">Restez informé(e)s</a>
		</div> -->
	</div>
</section>
<div class="container">
    <div class="row">
        <section class="packages col-sm-6" id="concept">
            <div class="section-header">
                <h2>Comment ça marche</h2>
                <div class="section-description">
                     Se faire livrer des produits frais et artisanaux de commerces locaux.
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/picto/online.png')?>" alt="Commandez en ligne vos produits frais et artisanaux">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Commandez en ligne chez les commerçants de votre quartier.</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/picto/shops.png')?>" alt="Les commerçants préparent votre commande">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Les commerçants préparent votre commande</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/picto/bike.png')?>" alt="On vous livre le tout chez vous, en une fois">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">On vous livre le tout chez vous, en une fois</p>
                </div>
            </div>
        </section>
        <section class="packages col-sm-6" id="prices">
            <div class="section-header">
                <h2>Combien cela coûte</h2>
                <div class="row">
                    <div class="col-sm-4 price-tag"><span>9 €</span><br> Commande &#60;45 €</div>
                    <div class="col-sm-4 price-tag"><span>6 €</span><br> Commande &#60;90 €</div>
                    <div class="col-sm-4 price-tag"><span>3 €</span><br> Commande &#62;90 €</div>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/picto/price.png')?>" alt="Vous commandez au même prix qu'en magasin">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Commandez au même prix qu'en magasin</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/picto/weight.png')?>" alt="Nous vous remboursons les écarts de poids">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Nous vous remboursons les écarts de poids</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/picto/groceries.png')?>" alt="Vous payez une seule livraison quel que soit le nombre de commerçants">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Vous payez une seule livraison quel que soit le nombre de commerçants</p>
                </div>
            </div>
        </section>
    </div>
</div>

<section id="missions" class="container-fluid">
    <h2>Ce que nous aimons</h2>
    <div class="row">
        <div class="col-md-4 item-mission mission-1">
            <div>
                <h3>Travailler ensemble</h3>
                <p>Un fonctionnement raisonné et transparent avec nos commerçants, nos livreurs et nos équipes.</p>
            </div>
        </div>
        <div class="col-md-4 item-mission mission-2">
            <div>
                <h3>Consommer local</h3>
                <p>Le soutien des artisans de votre quartier, garants d'un savoir-faire et de produits de qualité.</p>
            </div>
        </div>
        <div class="col-md-4 item-mission mission-3">
            <div>
                <h3>Etre proche de vous</h3>
                <p>Une livraison verte, organisée en tournée et limitée à votre quartier pour favoriser la proximité.</p>
            </div>
        </div>
    </div>
</section>

<section id="cards" class="container">
    <div class="row">
        <div class="col-md-5 clients">
            <img src="<?php echo $this->getSkinUrl('dist/images/photo/sandrine.jpg')?>" alt="Nos clients">
            <p class="quote">Ce qui m'a séduite, c'est de pouvoir me faire livrer des produits sains et de qualité le soir, même lorsque je finis tard.</p>
            <p class="quote-author">Sandrine G., cliente fidèle.</p>
        </div>
        <div class="col-md-5 col-md-offset-2 partners">
            <img src="<?php echo $this->getSkinUrl('dist/images/photo/bdm.png')?>" alt="Nos commerçants partenaires">
            <p class="quote">Ce service existe chez les grandes enseignes, nous pouvons maintenant faire la même chose avec Au Pas De Courses !</p>
            <p class="quote-author">Michel Vaidie, Boucherie des Moines, Paris 17.</p>
        </div>
    </div>
</section>

<section id="advantages">
    <div class="container">
        <div class="row text-center">
            <div class="item col-sm-3 col-xs-6">
                <img src="<?php echo $this->getSkinUrl('dist/images/picto/choice.png')?>" alt="Belle sélection de produits, au même prix qu'en boutique.">
                <p>Belle sélection de produits, au même prix qu'en boutique.</p>
            </div>
            <div class="item col-sm-3 col-xs-6">
                <img src="<?php echo $this->getSkinUrl('dist/images/picto/calendar-round.png')?>" alt="Livraison en soirée du mardi au vendredi">
                <p>Livraison en soirée du mardi au vendredi.</p>
            </div>
            <div class="item col-sm-3 col-xs-6">
                <img src="<?php echo $this->getSkinUrl('dist/images/picto/fresh.png')?>" alt="Qualité et fraîcheur de la commande à la livraison.">
                <p>Qualité et fraîcheur de la commande à la livraison.</p>
            </div>
            <div class="item col-sm-3 col-xs-6">
                <img src="<?php echo $this->getSkinUrl('dist/images/picto/kitchen.png')?>" alt="Gagnez du temps et mangez bon.">
                <p>Gagnez du temps et mangez bon.</p>
            </div>
        </div>
    </div>
</section>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <ul class="social-icons">
                    <li><a href="https://www.facebook.com/aupasdecourses" title="Facebook" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="https://twitter.com/aupasdecourses" title="Twitter" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="https://instagram.com/aupasdecourses/" title="Instagram" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <p class="copyright text-center">
                    ©<?php echo date("Y");?> Au Pas De Courses, tous droits réservés.
                </p>
                <ul class="nav text-center" role="navigation">
                    <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Mentions légales">Mentions légales</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Conditions générales d'utilisation">Conditions générales d'utilisation</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Tarifs">Tarifs</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl().'../blog';?>" title="Blog">Blog</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
	<?php echo $this->getChildHtml('footer') ?>
	<?php echo $this->getChildHtml('before_body_end') ?>
    <!-- Credits
    Coin icon by Madebyoliver - http://www.flaticon.com/free-icon/coin_134652
    Scale icon by Madebyoliver - http://www.flaticon.com/free-icon/scale_135529
    Grocery icon by Madebyoliver - http://www.flaticon.com/free-icon/groceries_135532
    Calendar icon by Madebyoliver - http://www.flaticon.com/free-icon/calendar_137866
    Kitchen icon by Madebyolivder - http://www.flaticon.com/free-icon/kitchen_135441
    Snowflake icon by Madebyolivder - http://www.flaticon.com/free-icon/snowflake_136613
    Sausage icon by Madebyolivder - http://www.flaticon.com/free-icon/sausage_135419
    -->
</body>
</html>