<?php
	$i = rand(1, 17); // generate random number size of the array
	$url = "images/header/".$i.".jpg"; // set variable equal to which random filename was chosen
	$angledown= $this->getSkinUrl("images/angle-down.png");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
	<?php echo $this->getChildHtml('head') ?>
</head>
<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
	<?php echo $this->getChildHtml('after_body_start') ?>
	<header class="header" id="faites-vos-courses">
        <div id="background_video_container">
            <!-- <video id="background_video_video" autoplay muted loop poster="<?php echo $this->getSkinUrl($url);?>">
                <source src="<?php echo $this->getSkinUrl('media/demo.mp4');?>" type="video/mp4" />
                <source src="<?php echo $this->getSkinUrl('media/demo.ogv');?>" type="video/ogg" />
                <source src="<?php echo $this->getSkinUrl('media/demo.webm');?>" type="video/webm" />
            </video> -->
            <img class="banner" src="<?php echo $this->getSkinUrl('dist/images/banner-home.jpg');?>" alt="Au pas de courses">
        </div>
        <div class="container">
            <div class="top-nav">
                <a class="btn standard-button faq-button" style="float:right;" href="<?php echo $this->getBaseUrl()."faq";?>" role="button">Des questions ?</a>
            </div>
            <div class="intro-section">
                <img id="logo" src="<?php echo $this->getSkinUrl('dist/images/logo@2x.png')?>" alt="Logo Au Pas De Courses">
                <h1 class="intro">Faites-vous livrer les bons produits de votre quartier</h1>
                <p class="intro-subtitle">En ce moment, votre première livraison offerte</p>
                    <!-- <form id='form-quartier' role="form" class="col-xs-12 col-md-12 form-inline contact-form form_zipcode" method="post" action="<?php echo $this->getUrl('customhome/index/redirect'); ?>">
                        <div id="input-group-intro">
                            <input id='GoogleAutoCompleteInput' class='form-control input-quartier' placeholder='Entrez votre adresse' type='text' name='input_addr' />
                            <input id='GoogleAutoCompleteZipcode' class='form-control input-quartier' type='hidden' name="zipcode" />
                            <button id='GoogleAutoCompleteSubmit' class="btn btn-default standard-button input-quartier" type="submit">Voir mes commerçants</button>
                        </div>
                    </form>
                <div class="col-xs-12 col-md-12"></div>
                <div class="col-xs-12 col-md-12">
                    <div id="scroll-button" >
                        <p id="small-header">Plus d'infos</p>
                        <div class="arrow bounce"></div>
                    </div>
                </div> -->
                <div class="col-md-5"></div>
            </div>
        </div>
	</header>
<section class="packages" id="quartiers">
	<div class="container">
		<div class="section-header">
			<h2>Sélectionnez votre quartier</h2>
			<div class="section-description" style="margin-bottom:20px;">
				 Au Pas De Courses vous livre dans les arrondissements suivants à Paris.
			</div>
		</div>
		<div class="row">
			<div class="bouton-quartier col-sm-12 col-md-3">
				<a href="<?php echo Mage::getBaseUrl().'../batignolles';?>" style="display:block;width:100%">
					<img src="<?php echo $this->getSkinUrl('dist/images/monceau_batignolles.jpg');?>" alt="Monceau - Batignolles, 17e-18e-9e-8e arrondissements de Paris" class="img-circle" style="width:100%;max-width:200px;"/>
					<h3 class="package-heading main-color">17e-18e-9e-8e</h3>
				</a>
			</div>
			<div class="bouton-quartier col-sm-12 col-md-3">
				<a href="<?php echo Mage::getBaseUrl().'../commerce';?>" style="display:block;width:100%">
					<img src="<?php echo $this->getSkinUrl('dist/images/commerce.jpg');?>" alt="Commerce, 15e arrondissement de Paris" class="img-circle" style="width:100%;max-width:200px;"/>
					<h3 class="package-heading main-color">15e</h3>
				</a>
			</div>
			<div class="bouton-quartier col-sm-12 col-md-3">
				<a href="<?php echo Mage::getBaseUrl().'../saintmartin';?>" style="display:block;width:100%">
					<img src="<?php echo $this->getSkinUrl('dist/images/saintmartin_marais.jpg');?>" alt="Saint Martin - Marais 10e-3e-11e arrondissements de Paris" class="img-circle" style="width:100%;max-width:200px;"/>
					<h3 class="package-heading main-color">10e-3e-11e</h3>
				</a>
			</div>
			<div class="bouton-quartier col-sm-12 col-md-3">
				<a href="<?php echo Mage::getBaseUrl().'../paris13e';?>" style="display:block;width:100%">
					<img src="<?php echo $this->getSkinUrl('dist/images/tolbiac.jpg');?>" alt="Tolbiac - 13e arrondissement de Paris" class="img-circle" style="width:100%;max-width:200px;"/>
					<h3 class="package-heading main-color">13e</h3>
				</a>
			</div>
		</div>
		<div class="row text-center">
			<a class="popup-gmaps button button-green" href="https://umap.openstreetmap.fr/fr/map/zones-de-livraison-au-pas-de-courses_86851#12/48.8648/2.3401">Voir nos zones de livraison <i class="fa fa-send"></i></a>
		</div>
	</div>
</section>
<div class="container">
    <div class="row">
        <section class="packages col-md-6" id="concept">
            <div class="section-header">
                <h2>Comment cela fonctionne ?</h2>
                <div class="section-description">
                     Une plateforme pour commander et se faire livrer des produits frais et artisanaux de commerces de bouche locaux.
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/online.png')?>" alt="Commandez en ligne vos produits frais et artisanaux">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Commandez en ligne chez les commerçants de votre quartier.</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/shops.png')?>" alt="Les commerçants préparent votre commande">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Les commerçants préparent votre commande</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/cargobike.png')?>" alt="On vous livre le tout chez vous, en une fois">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">On vous livre le tout chez vous, en une fois</p>
                </div>
            </div>
        </section>
        <section class="packages col-md-6" id="nos-tarifs">
            <div class="section-header">
                <h2>Combien cela coûte ?</h2>
                <div class="section-description">
                     La livraison vous coûte
                </div>
                <div class="section-description">
                    <ul>
                        <li class="price-9"><span>9 €</span><br> Commande &#60;45 €</li>
                        <li class="price-6"><span>6 €</span><br> Commande 45 - 90 €</li>
                        <li class="price-3"><span>3 €</span><br> Commande &#62;90 €</li>
                    </ul>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/cargobike.png')?>" alt="Vous commandez au même prix qu'en magasin">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Vous commandez au même prix qu'en magasin</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/cargobike.png')?>" alt="Nous vous remboursons les écarts de poids">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Nous vous remboursons les écarts de poids</p>
                </div>
            </div>
            <div class="item row">
                <div class="col-md-3">
                    <img src="<?php echo $this->getSkinUrl('dist/images/cargobike.png')?>" alt="Vous payez une seule livraison quel que soit le nombre de commerçants">
                </div>
                <div class="col-md-9">
                    <p class="package-feature">Vous payez une seule livraison quel que soit le nombre de commerçants</p>
                </div>
            </div>
        </section>
    </div>
</div>

<section id="missions" class="container-fluid">
    <h2>Nos missions et nos valeurs</h2>
    <div class="row">
        <div class="col-md-6 item-mission mission-1">
            <div>
                <h3>Une éthique</h3>
                <p>Un fonctionnement raisonné grâce à des livreurs salariés, formés et professionnels.</p>
            </div>
        </div>
        <div class="col-md-3 item-mission mission-2">
            <div>
                <h3>Local avant tout !</h3>
                <p>Le soutien des artisans locaux et indépendants, garants d'un savoir-faire et de produits de qualité.</p>
            </div>
        </div>
        <div class="col-md-3 item-mission mission-3">
            <div>
                <h3>Proche de vous</h3>
                <p>Une livraison de proximité, organisée en tournée et limitée à votre quartier pour offrir une livraison verte et favoriser la proximité.</p>
            </div>
        </div>
    </div>
</section>

<section id="cards" class="container">
    <div class="row">
        <div class="col-md-5 clients">
            <h3>Nos clients</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet impedit facilis quo blanditiis doloremque illum reprehenderit vero praesentium beatae corporis rerum, numquam, labore, temporibus. Eligendi quis placeat voluptates vel voluptatum.</p>
        </div>
        <div class="col-md-5 col-md-offset-2 partners">
            <h3>Nos commerçants partenaires</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat possimus est deserunt, praesentium alias minus cupiditate, reiciendis quia distinctio cum quidem suscipit at et adipisci, molestiae mollitia incidunt maiores hic.</p>
        </div>
    </div>
</section>

<section class="packages grey-bg" id="brief1">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="" data-src="https://www.youtube.com/embed/gb75gUhl5bM" allowfullscreen></iframe>	
				</div>
			</div>
			<div class="col-md-6 left-align">
				<h2>Bon, pratique et responsable</h2>
				<ul class="feature-list">
					<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Des commerçants locaux sélectionnés pour la qualité de leurs produits et leur savoir-faire,</li>
					<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Des créneaux de livraison de 45 minutes,</li>
					<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Une livraison possible le soir même ou durant les 5 prochains jours,</li>
					<li><i class="fa fa-check-circle-o" aria-hidden="true"></i> Une livraison douce en triporteur électrique par un livreur professionnel.</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<section class="packages" id="avis">
	<div class="container">
		<div class="section-header">
			<h2>Lauréat des <a href="http://www.cci-paris-idf.fr/presse/communiques/7eme-edition-des-palmes-du-e-commerce-2015-neuf-laureats-recompenses-pour-des-projets-de-commerce-innovants-presse" target="_blank" >Palmes du eCommerce 2015</a>!</h2>
			<div class="colored-line"></div>
			<div class="section-description" style="margin-bottom:50px;">
				 Une belle récompense pour notre équipe, nos clients et nos partenaires.
			</div>
		</div>
		<div class="col-md-3 col-sm-12"></div>
		<div id="carousel-comments" class="owl-carousel col-sm-12 col-md-4">
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">	Très belle initiative. Merci Au Pas de Courses et aux commerçants partenaires :-)</span>
					  </span>
					</div>
					<div class="avis-author">
					  Nadine G., Cliente fidèle.
					</div>
				</div>
			</div>
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">C'est extraordinaire d'avoir des produits faits par des artisans et livrés par Au Pas De Courses. On ne peut pas faire plus court que ce circuit là.</span>
					  </span>
					</div>
					<div class="avis-author">
					  Francis Ramon, La Fille du Boulanger.
					</div>
				</div>
			</div>
			<div class="item">	
				<div class="one-avis single-service" style="width:100%;display: block;height: auto;">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">"C'est désormais toute la semaine que vous aurez les meilleurs produits dans votre assiette"</span>
					  </span>
					</div>
					<div class="avis-author">
					  <a href="http://issuu.com/le-bonbon/docs/ouest_9dd7a5e8a951a4/26" target="_blank"><img src="<?php echo $this->getSkinUrl('images/lebonbon.png');?>" alt="Cliquez pour voir l'article du Bonbon"/></a>
					</div>
				</div>
			</div>
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">"Excellents produits, service ponctuel.</br>Je recommande !"</span>
					  </span>
					</div>
					<div class="avis-author">
					  Margot P., cliente de la première heure
					</div>
				</div>
			</div>
			<div class="item">
				<div class="one-avis single-service">
					<div class="avis-main">
					  <span class="vc-outer">
						<span class="vc-inner">Ce service existe chez les grandes enseignes, nous pouvons maintenant faire la même chose avec Au Pas De Courses!</span>
					  </span>
					</div>
					<div class="avis-author">
					  Michel Vaidie, Boucherie des Moines.
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-12"></div>
	</div>
</section>
<section class="packages grey-bg" id="evenements">
	<div class="container">
		<div class="section-header">
			<h2>Un évènement à organiser ?</h2>
			<div class="colored-line"></div>
			<div class="section-description" style="margin-bottom:50px;">
				 Au Pas De Courses et vos commerçants de quartier vous proposent des plateaux et des prestations sur mesure pour vos évènements, en famille ou au travail.
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<a id="contact-button" class="btn btn-default standard-button" href="javascript:void(Tawk_API.toggle());">Contactez nous !</a>
			</div> 
		</div> 
	</div>
</section>
<footer id="contact-section">
	<div class="container">
		<ul class="social-icons">
			<p>Suivez nous sur</p>
			<li><a href="https://www.facebook.com/aupasdecourses"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
			<li><a href="https://twitter.com/aupasdecourses"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
			<li><a href="https://instagram.com/aupasdecourses/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
		</ul>
		<p class="copyright">
			©<?php echo date("Y");?> Au Pas De Courses, tous droits réservés.<!-- </br> Crédit Photos: Pierre Mainguet, <a href="https://flic.kr/p/mJNxaB">David Fleg</a> et besopha <a href="https://commons.wikimedia.org/wiki/File%3ARue_de_Bretagne%2C_75003_Paris%2C_2015.jpg">Rue de Bretagne</a> / <a href="https://flic.kr/p/xifWho">Parc Georges Brassens</a> -->
		</p>
	</div>
	<a href="#" class="back-to-top">Haut de page</a>
</footer>
	<?php echo $this->getChildHtml('footer') ?>
	<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>
