<div class="account-login-container<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <h1><?php echo $this->__('Login'); ?></h1>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getUrl('apdc-customer/account/ajaxLoginProcess');?>" method="post" id="login-form" class="form-validate scaffold-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="form-group">
            <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>"/>
        </div>
        <div class="form-group">
             <input type="password" name="login[password]" class="input-text required-entry validate-password form-control" id="pass" title="<?php echo $this->__('Password') ?>" placeholder="<?php echo $this->__('Password') ?>"/>
        </div>
        <div class="form-group">
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <a href="" data-login-view="<?php echo $this->getUrl('apdc-customer/account/ajaxPopupView');?>" class="f-left" id="forgot-password"><?php echo $this->__('Forgot Your Password?') ?></a>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
        <button type="submit" class="button button-green" title="<?php echo $this->__('Login') ?>" name="send" ><span><span><?php echo $this->__('Se Connecter') ?></span></span></button>
        <?php echo $this->getChildHtml('inchoo_socialconnect_login');?>
    </form>
        <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>