<div id="mc_embed_signup">
    <?php $quartiers=$this->getNewsletterlist();?>
    <h1><?php echo $this->__('Restez informé(e)s'); ?></h1>
    <p>Inscrivez-vous pour recevoir les nouvelles fraîches de votre quartier et de vos commercants :</p>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getUrl('apdc-front/newsletter/ajaxNewsletterProcess');?>" method="post" id="newsletter-form" class="form-validate scaffold-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="form-group">
            <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="EMAIL" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control" title="<?php echo $this->__('Votre email') ?>" placeholder="<?php echo $this->__('Votre email') ?>"/>
        </div>
        <div class="form-group">
            <select class="form-control" id="select-quartier" name="id">
                <?php foreach($quartiers as $name => $id):?>
                <option value="<?= $id;?>"><?= $name;?></option>
                <?php endforeach;?>
            </select>
        </div>
        <button type="submit" class="button button-green" title="<?php echo $this->__('S\'inscrire') ?>" name="send" ><span><span><?php echo $this->__('S\'inscrire') ?></span></span></button>
    </form>
        <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('newsletter-form', true);
    //]]>
    </script>
</div>