<div id="mc_embed_signup">
    <?php $quartiers=$this->getNewsletterlist();?>
    <h1><?php echo $this->__('Inscrivez vous!'); ?></h1>
    <p>Pour rester informer de nos ouvertures de quartier et des actualités de vos commerçants, veuillez sélectionner votre quartier et indiquer votre adresse mail ci-dessous.</p>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getUrl('apdc-front/newsletter/ajaxNewsletterProcess');?>" method="post" id="newsletter-form" class="form-validate scaffold-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="form-group">
            <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="EMAIL" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>"/>
        </div>
        <div class="form-group">
            <select class="form-control" id="exampleSelect1" name="id">
                <?php foreach($quartiers as $quartier):?>
                <option value="<?= $quartier['id'];?>"><?= $quartier['name'];?></option>
                <?php endforeach;?>
            </select>
        </div>
        <button type="submit" class="button button-green" title="<?php echo $this->__('Envoyer') ?>" name="send" ><span><span><?php echo $this->__('Envoyer') ?></span></span></button>
    </form>
        <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('newsletter-form', true);
    //]]>
    </script>
</div>