services:
#    apdc_apdc.example:
#        class: Apdc\ApdcBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#
    apdc_apdc.magento:
        class: Apdc\ApdcBundle\Services\Magento
