services:
#    apdc_apdc.example:
#        class: Apdc\ApdcBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#
    apdc_apdc.magento:
        class: Apdc\ApdcBundle\Services\Magento

    apdc_apdc.adyenlogs:
        class: Apdc\ApdcBundle\Services\AdyenLogs

    apdc_apdc.adyen:
        class: Apdc\ApdcBundle\Services\Adyen
        arguments: ['@apdc_apdc.adyenlogs']
