<ol class="opc apdc-form" id="checkoutSteps">
    <li id="opc-forgotpassword" class="section allow active">
        <div class="step-title">
            <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
        </div>
        <div id="forgotpassword-step" class="step a-item">
            <div class="container col1-set">
                <div class="row">
                    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost');?>" method="post" id="forgotpassword-form" class="apdc-form">
                        <div class="fieldset col-sm-12">
                            <?php echo $this->getMessagesBlock()->toHtml() ?>
                            <ul class="form-list fields">
                                <li style="text-align:center;">
                                    <span><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></span>
                                </li>
                                <li>
                                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" placeholder="<?php echo $this->__('Email Address') ?>"/>
                                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                                </li>
                            </ul>
                            <div class="col-sm-12" style="text-align:center;">
                                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button button-green"><?php echo $this->__('Submit') ?></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </li>
</ol>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('forgotpassword-form', true);
/*]]>*/
</script>