<ol class="opc apdc-form" id="checkoutSteps">
    <li id="opc-login" class="section allow active">
        <div class="step-title">
            <h2><?php echo $this->__('Reset a Password'); ?></h2>
        </div>
        <div id="resetpassword-step" class="step a-item">
            <div class="container col1-set">
                <div class="row">
                    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate">
                        <div class="fieldset col-sm-12">
                            <?php echo $this->getMessagesBlock()->toHtml() ?>
                            <ul class="form-list fields">
                                <li>
                                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                                    <div class="input-box">
                                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                                    </div>
                                </li>
                                <li>
                                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                                    <div class="input-box">
                                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                                    </div>
                                </li>
                                <div class="col-sm-12" style="text-align:center;">
                                    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" class="button button-green"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
                                </div>
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </li>
</ol>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>