<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="page-header"><h2>Cartes</h2></div>
    <div class="button_accueil">
      <a href=""><button type="button" class="btn btn-primary btn-lg btn-block">Récupérer liste des clients à livrer</button></a>
    </div>
    <div class="button_accueil">
      <a href="index.php?module=dispatch&action=view&dispatch=route"><button type="button" class="btn btn-primary btn-lg btn-block">Calcul itinéraire</button></a>
    </div>
    <div class="button_accueil">
        <a href="index.php"><button type="button" class="btn btn-default btn-lg btn-block">Retour</button></a>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>