<?php

/*
* Page de calcul des itinéraires livreurs
*
*
*/

$addrTable=array();
$nameTable=array();
$num = 0;
while (isset($_GET['loc' . $num])) {
  $loc = $_GET['loc' . $num];
  if ($loc == "") {
    break;
  }
  $addrTable[] = $loc;
  $num++;
}

for ($numName = 0; $numName < $num; $numName++) {
  $nameTable[$numName] = '';
  if (isset($_GET['name' . $numName])) {
    $nameTable[$numName] = $_GET['name' . $numName];
  }
}

$lat;
$lng;
if (isset($_GET['center'])) {
  $loc = $_GET['center'];
  if (eregi("\(\s*\-?([0-9]+|[0-9]*\.[0-9]+),\s*\-?([0-9]+|[0-9]*\.[0-9]+)\)",
      $loc)) {
    $latLngArr = split("[\s,\)\(]+",$loc);
    $lat = $latLngArr[1];
    $lng = $latLngArr[2];
  }
} 

$zoom = 8;
if (isset($_GET['zoom'])) {
  $zoom = $_GET['zoom'];
}

$mode = 0;
if (isset($_GET['mode'])) {
  $mode = $_GET['mode'];
}

$walk = 0;
if (isset($_GET['walk'])) {
  $walk = $_GET['walk'];
}

$bike = 0;
if (isset($_GET['bike'])) {
  $bike = $_GET['bike'];
}

$avoid = 0;
if (isset($_GET['avoid'])) {
  $avoid = $_GET['avoid'];
}

$avoidTolls = 0;
if (isset($_GET['avoidTolls'])) {
  $avoidTolls = $_GET['avoidTolls'];
}
?>

<link rel="stylesheet" href="style/routing_style.css" type="text/css" media="screen">
<link rel="stylesheet" href="style/routing_print.css" type="text/css" media="print">

<script type="text/javascript">
    function onBodyLoad() {
      google.load("maps", "3", {callback: init, other_params:"sensor=false"});
    }

    function init() {
    <?php
      if (isset($lat) && isset($lng)) {
        echo "\tloadAtStart(" . $lat . ", " . $lng . ", " . $zoom . ");\n";
      } else {
        echo "\tif (google.loader.ClientLocation != null) {\n";
        echo "\t\tlatLng = new google.maps.LatLng(google.loader.ClientLocation.latitude, google.loader.ClientLocation.longitude);\n";
        echo "\t\tloadAtStart(google.loader.ClientLocation.latitude, google.loader.ClientLocation.longitude, " . $zoom . ");\n";
        echo "\t} else {\n";
  //$lat = "37.4419";
  //$lng = "-122.1419";
        echo "\t\tloadAtStart(37.4419, -122.1419, " . $zoom . ");\n";
        echo "\t}\n";
      }
    for ($i = 0; $i < count($addrTable); $i++) {
      echo "\taddAddressAndLabel('"
          . $addrTable[$i] . "', '" . $nameTable[$i] . "');\n";
    }
    if (count($addrTable) > 0) {
      $walkStr = ($walk == 0) ? "false" : "true";
      $bikeStr = ($bike == 0) ? "false" : "true";
      $avoidStr = ($avoid == 0) ? "false" : "true";
      $avoidTollsStr = ($avoidTolls == 0) ? "false" : "true";
      echo "\tdirections(" . $mode . ", " . $walkStr . ", ". $bikeStr . ", " . $avoidStr . ", " . $avoidTollsStr . ");\n";
    }
    ?>
  }

  function toggle(divId) {
    var divObj = document.getElementById(divId);
    if (divObj.innerHTML == "") {
      divObj.innerHTML = document.getElementById(divId + "_hidden").innerHTML;
      document.getElementById(divId + "_hidden").innerHTML = "";
    } else {
      document.getElementById(divId + "_hidden").innerHTML = divObj.innerHTML;
      divObj.innerHTML = "";
    }
  }

  jQuery(function() {
    jQuery( "#accordion" ).accordion({
      collapsible: true,
    autoHeight: false,
    clearStyle: true
    });
    jQuery("input:button").button();
    jQuery("#dialogProgress" ).dialog({
      height: 140,
    modal: true,
    autoOpen: false
    });
    jQuery("#progressBar").progressbar({ value: 0 });
    jQuery("#dialogTomTom" ).dialog({
      height: 480,
    width: 640,
    modal: true,
    autoOpen: false
    });
    jQuery("#dialogGarmin" ).dialog({
      height: 480,
    width: 640,
    modal: true,
    autoOpen: false
    });
    jQuery('.myMap').height(jQuery(window).height() - 100);
  });

$( document ).ready(function() {
     onBodyLoad();
});

</script>

<div id="canvas" class="container theme-showcase" role="main">
    <div class="page-header">
      <h2>Liste des commandes <small>Tous commerçants</small></h2>
    </div>
    <div class="row">
      <div class="col-md-4">
          <div id="accordion">
            <h3 class="btn btn-default btn-block btn-lg"><a href="#" class='accHeader'>Destinations</a></h3>
            <div id="destination-div">
              <form name="address" onSubmit="clickedAddAddress(); return false;">
                Ajouter point de passage par adresse:
                <input name="addressStr" type="text">
                <input type="button" value="Add!" onClick="clickedAddAddress()">
              </form> ou <a href="#" onClick="toggle('bulkLoader'); document.listOfLocations.inputList.focus(); document.listOfLocations.inputList.select(); return false;">
              Importer en masse une liste d'adresse/de points géolocalisés (lat, lng)</a>.
              <div id="bulkLoader"></div>
            </div>

            <h3 class="btn btn-default btn-block btn-lg"><a href="#" class='accHeader'>Options d'itinéraire</a></h3>
            <div id="options-div">
              <form name="travelOpts">
                <label><input id="walking" type="checkbox"/> Marche</label>
                <label><input id="bicycling" type="checkbox"/> Vélo</label>
                <label><input id="avoidHighways" type="checkbox"/> Eviter les autoroutes</label>
                <label><input id="avoidTolls" type="checkbox"/> Eviter les routes à péages</label>
              </form>
            </div>

            <h3 class="btn btn-default btn-block btn-lg"><a href="#" class='accHeader'>Export</a></h3>
            <div id="export-div">
              <div id="exportGoogle"></div>
              <div id="exportDataButton"></div>
              <div id="exportData"></div>
              <div id="exportLabelButton"></div>
              <div id="exportLabelData"></div>
              <div id="exportAddrButton"></div>
              <div id="exportAddrData"></div>
              <div id="exportOrderButton"></div>
              <div id="exportOrderData"></div>
              <div id="garmin"></div>
              <div id="tomtom"></div>
              <div id="durations" class="pathdata"></div>
              <div id="durationsData"></div>
            </div>

            <h3 class="btn btn-default btn-block btn-lg"><a href="#" class='accHeader'>Editer l'itinéraire</a></h3>
            <div id="edit-div">
              <div id="routeDrag"></div>
              <div id="reverseRoute"></div>
            </div>

            <h3 class="btn btn-default btn-block btn-lg"><a href="#" class='accHeader'>Aide</a></h3>
            <div id="help-div">
              <p>Pour ajouter des points de passage, cliquez simplement avec le bouton gauche de votre souris sur la carte ou entrez une adresse
              soit dans le champ d'adresse unique ou dans le champ d'importation en masse.</p>
              <p>Le premier point de passage que vous ajoutez est considéré comme le départ de votre itinéraire.
              Si vous cliquez sur "Calculer la boucle le plus rapide", ce point de départ sera également le point d'arrivée.
              Si vous cliquez sur "Calculer l'itinéraire A-Z le plus rapide", le dernier point de passage entré sera considéré comme la destination finale.</p>
              <p>Pour supprimer ou éditer un point de passage, cliquez sur son marqueur.</p>
              <p>Si plus de 15 points de passage sont entrés, il n'est pas garanti que vous obteniez la solution optimale, mais la solution sera la plus proche possible
              de la solution optimale.</p>
              <p>Vous pouvez réarranger les points de passage une fois que l'itinéraire a été calculé. Pour cela, cliquez sur "Editer l'itinéraire" et glisser-déposer les points.</p>
              <p>Vous pouvez entrer jusqu'à 100 points de passage.</p>
            </div>          
          </div>
          <div class="button_itineraire">
            <input id="button1" class="btn btn-success btn-block btn-lg" type="button" value="Calculer la boucle la plus rapide" onClick="directions(0, document.forms['travelOpts'].walking.checked, document.forms['travelOpts'].bicycling.checked, document.forms['travelOpts'].avoidHighways.checked, document.forms['travelOpts'].avoidTolls.checked)">
            <input id="button2" class="btn btn-success btn-block btn-lg" type="button" value="Calculer l'itinéraire A-Z le plus court" onClick="directions(1, document.forms['travelOpts'].walking.checked, document.forms['travelOpts'].bicycling.checked, document.forms['travelOpts'].avoidHighways.checked, document.forms['travelOpts'].avoidTolls.checked)">
            <input id='button3' class="btn btn-danger btn-block btn-lg" type='button' value='Recommencer' onClick='startOver()'>
          </div>
        </div>
        <div class="col-md-8">
          <div id="map" class="myMap"></div>
          <div id="path" class="pathdata"></div>
          <div id="my_textual_div"></div>
        </div>
    </div>
  <!-- Hidden stuff -->
    <div id="bulkLoader_hidden" style="visibility: hidden;">
      <form name="listOfLocations" onSubmit="clickedAddList(); return false;">
      <textarea name="inputList" rows="10" cols="70">One destination per line</textarea><br>
      <input type="button" value="Add list of locations" onClick="clickedAddList()">
    </form></div>
    <div id="exportData_hidden" style="visibility: hidden;"></div>
    <div id="exportLabelData_hidden" style="visibility: hidden;"></div>
    <div id="exportAddrData_hidden" style="visibility: hidden;"></div>
    <div id="exportOrderData_hidden" style="visibility: hidden;"></div>
    <div id="durationsData_hidden" style="visibility: hidden;"></div>

    <div id="dialogProgress" title="Calculating route...">
      <div id="progressBar"></div>
    </div>

    <div id="dialogTomTom" title="Export to TomTom">
      <iframe name='tomTomIFrame' style='width: 580px; height: 400px'></iframe> 
    </div>

    <div id="dialogGarmin" title="Export to Garmin">
      <iframe name='garminIFrame' style='width: 580px; height: 400px'></iframe>
    </div>

<!--le div fermant le container se trouve dans le fichier footer.php-->

<script type="text/javascript">
    jQuery.noConflict();
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="libs/js/jquery.cookie.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="libs/js/BpTspSolver.js"></script>
<script type="text/javascript" src="libs/js/directions-export.js"></script>
<script type="text/javascript" src="libs/js/tsp.js"></script>

</body>