<?php 
	//Get Collection of products
	$current_cat=Mage::registry('current_category');
	$current_cat_Name=Mage::registry('current_category')->getName();
	$current_cat_Id=Mage::registry('current_category')->getId();
	$collection=$this->getSelectionbyById($current_cat_Id);

	//Get Customer Data
	$customer = Mage::helper('customer');

?>

<div class="row">
	<div class="page-title col-xs-12">
	    <div class="block-promos text-center">
	    	<div class="inner-box">
		    <span class="title-block">Vos produits préférés</span>
		    	<?php if($customer->isLoggedIn()){
			    	$orders=$this->getCustomerLastOrders();
			    		if(!$orders->getSize()){
			    			echo $this->__("Vous n'avez pas encore acheté chez ce commerçant!");
			    		}else{
			    			$items_id=$this->getCustomerLastOrderedItems($orders,$current_cat_Id);
			    			if (count($items_id)>0){	    		
						    	echo '<ul>';
					    		foreach($items_id as $id){
					    			$product=Mage::getModel('catalog/product')->load($id);
					    			echo '<li><a href="'.$product->getProductUrl().'">'.$product->getName().'</a></li>';
					    		}
						    	echo '</ul>';
						    }
			    		}
			    	}else{
			    			echo '<a href="'.$customer->getLoginUrl().'">Enregistrez vous/Connectez vous pour profiter des suggestions de Au Pas De Courses.</a>';
			    		}
			    	?>

		    </div>
	    </div>
	</div>
</div>
		
		