<?php 
	$collection=$this->getAllSelections()
			->setPageSize(20);
    $product_model = Mage::getModel('catalog/product');
?>

<div class="row">
	<div class="page-title col-xs-12">
	    <div class="block-promos text-center">
	    	<div class="inner-box">
			    <div class="title-block">La sélection du moment</div>
			    <div class="colored-line"></div>
			    	<div id="carrousel-selection-home" class="owl-carousel">
				    	<?php foreach($collection as $entity){
				    		$entityNameStripped = $this->stripTags($entity->getData('name'), null, true);?>
				    		
				    		<div class="product-info products-grid">
					    		<a href="<?php echo $entity->getProductUrl();?>" title="<?php echo $entityNameStripped;?>">
					    			<img src="<?php echo $this->helper('catalog/image')->init($entity, 'small_image')->resize(250, 250);?>" width="250" height="250" alt="<?php echo $this->htmlEscape($this->getImageLabel($entity, 'small_image'));?>" title="<?php $this->htmlEscape($this->getImageLabel($entity, 'small_image'));?>" />
					    			<!--Label bio-->
								    <?php 
								    $label_bio=['AB','Bio Européen','AB,Bio Européen'];
								    $test_bio=Mage::getResourceSingleton('catalog/product')->getAttribute('produit_biologique')->getSource()->getOptionText($entity->getData('produit_biologique'));
								    if(in_array($test_bio,$label_bio)){
								            echo '<span class="produit-biologique-selection"><img src="'.$this->getSkinUrl("images/logo_ab_petit.png").'" alt="Bio"/></span>';
								    }?>
					    		</a>
					    		<a href="<?php echo $entity->getProductUrl();?>" title="<?php echo $entityNameStripped;?>"><h2 class="product-name"><?php echo $entity->getData('name');?></h2></a>
								<?php if($entity->getData('short_description')) :?>
						        	<div class="product-short_desc">		            
										<?php echo $entity->getData('short_description')?>
									</div>
								<?php endif; ?>
				    		</div>
				    	<?php }?>
				    </div>
		    </div>
	    </div>
	</div>
</div>
		
		