<meta name="google-signin-client_id" content="<?php echo Mage::getStoreConfig('customer/inchoo_socialconnect_google/client_id'); ?>">
<script type="text/javascript">
    var apdcGoogleLoginAppiId = '<?php echo Mage::getStoreConfig('customer/inchoo_socialconnect_google/client_id'); ?>';
</script>
<script async defer src="https://apis.google.com/js/api.js" 
        onload="this.onload=function(){};googleHandleClientLoad()" 
        onreadystatechange="if (this.readyState === 'complete') this.onload()">
</script>
