<tr>
    <td class="a-right cart-total-shipping">
        <?php echo $this->__('Livraison'); ?>
        <?php echo '</br><div class="text-shipping">Livraison gratuite pour les '; ?><a href="<?php echo Mage::getBaseUrl()?>comment-commander">Early Adopters</a><?php echo '</span>'?>
    </td>
    <td class="a-right cart-total-shipping">
        <?php if ($this->isFreeShipping()): ?>
            <?php echo $this->__('Free') ?>
        <?php else: ?>
            <?php 
            $totals=$this->getTotal();
            echo $this->helper('checkout')->formatPrice($totals->getValue()*(1+$this->getVAT()/100)) ?>
        <?php endif; ?>
    </td>
</tr>