<?= $this->menu ?>
<div class="container">
	<?= $this->from ?>
	<hr>
	<?php foreach($this->orders as $store => $orders) : ?>
		<?php $id = str_replace(' ', '_', $store)?>
		<table style="width: 100%">
			<tr>
				<th>
					<h4><a href="#<?= $id ?>" data-toggle="collapse"><?= $store ?></a></h4>
				</th>
			</tr>
			<tr>
				<td>
					<div id="<?= $id ?>" class="store collapse">
						<table class="table" style="width: 100%">
							<tr>
								<th>Creneaux</th>
								<th>N Commande</th>
								<th>Montant</th>
								<th>Nom Clients</th>
								<th>Adresse</th>
								<th>Tel</th>
								<th>Autre Contact</th>
								<th>Infos</th>
							</tr>
							<?php foreach($orders as $order_id => $order) : ?>
								<tr>
									<td><?= $order['delivery_time'] ?></td>
									<td><a href="indi/orders/<?= $order_id ?>" target="_blanc"><?= $order_id ?></td>
									<td><?= "{$order['Total prix']}€" ?></td>
									<td><?= "{$order['first_name']} {$order['last_name']}" ?></td>

									<td><a href="https://www.google.com/maps?q=<?= $order['address'] ?>" target="_blanc"><?= $order['address'] ?></a></td>
									<td><a href="tel:<?= $order['phone'] ?>"><?= $order['phone'] ?></a></td>
									<td><?= $order['contact'] ?> <a href="tel:<?= $order['contact_phone'] ?>"><?= $order['contact_phone'] ?></a></td>
									<td><?= $order['info'] ?></td>
								</tr>
							<?php endforeach ?>
						</table>
					</div>
				</td>
			</tr>
		</table>
	<?php endforeach ?>
</div>
