<?php
/**
/ @author Pierre Mainguet
 */
?>
<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
<!-- <dt class="complete">
    <a href="#billing" onclick="checkout.changeSection('opc-billing'); return false;"><strong><?php echo $this->__('Billing Address') ?></strong></a>
</dt>
<dd class="complete">
    <address><?php echo $this->getBilling()->format('html') ?></address>
</dd> -->
<dt class="complete">
    <a href="#billing" onclick="checkout.changeSection('opc-billing'); return false;"><strong><?php echo $this->__('Billing Address') ?></strong></a>
</dt>
<!--<dd class="complete">
    <address><?php echo $this->getShipping()->format('html') ?></address>
</dd>-->
<?php else: ?>
<dt>
    <?php echo $this->__('Billing Address') ?>
</dt>
<!-- <dt>
    <?php echo $this->__('Shipping Address') ?>
</dt> -->
<?php endif; ?>