<?php if ($this->getCheckout()->getStepData('billing', 'complete') || $this->getCheckout()->getStepData('billing', 'allow') ): ?>
		<dt class="complete">
			<a href="#billing" onclick="checkout.changeSection('opc-billing'); return false;"><strong><?php echo $this->__('Votre adresse') ?></strong><span>1</span></a>
		</dt>
	<?php else: ?>
		<dt>
			<strong><?php echo $this->__('Votre adresse') ?></strong>
			<span>1</span>
		</dt>
<?php endif; ?>
