<?php if ($this->getCheckout()->getStepData('checkcart', 'complete') || $this->getCheckout()->getStepData('checkcart', 'allow') ): ?>
		<dt class="complete">
			<a href="#checkcart" onclick="checkout.changeSection('opc-checkcart'); return false;"><strong><?php echo $this->__('Vérification') ?></strong><span>3</span></a>
		</dt>
	<?php else: ?>
		<dt>
			<strong><?php echo $this->__('Vérification') ?></strong>
			<span>3</span>
		</dt>
<?php endif; ?>
