<?php
/**
/ @author Pierre Mainguet
 */
?>
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <a href="#payment" onclick="checkout.changeSection('opc-payment'); return false;"><i class="fa fa-credit-card" style="width: 20px;"></i><strong><?php echo $this->__('Payment Method') ?></strong></a>
</dt>
<dd class="complete">
    <?php echo $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<dt>
    <i class="fa fa-credit-card" style="width: 20px;"></i><?php echo $this->__('Payment Method') ?>
</dt>
<?php endif; ?>