<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <a href="#payment" onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Validation & paiement') ?></a>
</dt>
<!--
<dd class="complete">
    <?php echo $this->getPaymentHtml() ?>
</dd>
-->
<?php else: ?>
<dt>
    <?php echo $this->__('Validation & paiement') ?>
</dt>
<?php endif; ?>