<?php if ($this->getCheckout()->getStepData('shipping_method', 'complete') || $this->getCheckout()->getStepData('shipping_method', 'allow')): ?>
<dt class="complete">
    <a href="#shipping_method" onclick="checkout.changeSection('opc-shipping_method'); return false;"><strong><?php echo $this->__('Votre livraison') ?></strong></a>
</dt>
<?php else: ?>
<dt>
   <?php echo $this->__('Votre livraison') ?>
</dt>
<?php endif; ?>
