<div class="row homepage-reassurance">
	<div class="col-xs-12">
	<div class="title-block">Comment ça marche</div>
		<div class="colored-line"></div>
	    <div id="carrousel-reassurance" class="owl-carousel">
			<div>
				<div class="reassurance-outer first-item">
					<div class="reassurance-inner">
						<div class="reassurance-title">COMMANDEZ EN LIGNE</div>
						<div class="reassurance-text">au même prix qu'en magasin, en une seule livraison quel que soit le nombre de commerçants</div>
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer second-item">
					<div class="reassurance-inner">
						<div class="reassurance-title">NOS CRENEAUX DE LIVRAISON</div>
						<div class="reassurance-text"><?php echo $this->getChildHtml('deliverytime-home')?></div>						
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer third-item">
					<div class="reassurance-inner">
						<div class="reassurance-title">DU MARDI AU VENDREDI</div>
						<div class="reassurance-text">Livraison le jour même (pour une commande avant 15h) et jusqu'à 4 jours en avance.</div>
					</div>
				</div>
			</div>
			<?php 
				$payment_activated = Mage::getStoreConfig('apdc_general/activation/payment');
				if ($payment_activated == true) : ?>
			    <div>
					<div class="reassurance-outer fourth-item">
							<div class="reassurance-inner">
								<div class="col-xs-12 livraison-countdown" id="#livraison-countdown">
									<div id="countdown"></div>
								</div>
							</div>
							<script type='text/javascript 'src='/js/countdown/js/jquery.countdown.js'></script>
			   				<script type='text/javascript 'src='/js/countdown/js/script.js'></script>
					</div>
				</div>
			<?php endif ?>
		</div>
	</div>
</div>
<script>
    $j(document).ready(function() {
      $j("#carrousel-reassurance").owlCarousel({
            items:4,
            pagination:false,
            autoPlay : false,
            navigation : true
      });
    });
</script>
