<div class="row homepage-reassurance">
	<div class="col-xs-12">
	<div class="title-block">Comment ça marche</div>
		<div class="colored-line"></div>
	    <div id="carrousel-reassurance" class="owl-carousel">
			<div>
				<div class="reassurance-outer first-item">
					<div class="reassurance-inner">
						<div class="reassurance-title">COMMANDEZ EN LIGNE</div>
						<div class="reassurance-text">en une seule fois<br/>aux mêmes prix qu'en magasin</div>
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer second-item">
					<div class="reassurance-inner">
						<div class="reassurance-title">NOS CRENEAUX DE LIVRAISON</div>
						<div class="reassurance-text"><?php echo $this->getChildHtml('deliverytime-home')?></div>						
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer third-item">
					<div class="reassurance-inner">
						<div class="reassurance-title">DU MARDI AU VENDREDI</div>
						<div class="reassurance-text">Livraison le jour même pour une commande avant 15h.</div>
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer fourth-item">
						<div class="reassurance-inner">
								<div class="reassurance-title">10€ OFFERTS</div>
								<div class="reassurance-text">En parrainant vos proches </br><a href="https://www.aupasdecourses.com/batignolles/sponsorship/"><i>Cliquez pour en savoir plus</i></a></div>
						</div>
				</div>
			</div>
		</div>
	</div>
<?php $payment_activated = Mage::getStoreConfig('apdc_general/activation/payment'); ?>
<?php if ($payment_activated == true) : ?>
	<script type='text/javascript 'src='/js/countdown/js/jquery.countdown.js'></script>
    <script type='text/javascript 'src='/js/countdown/js/script.js'></script>
	<div class="col-xs-12 livraison-countdown" id="#livraison-countdown">
		<div id="countdown"></div>
	</div>
<?php endif ?>
</div>
