<?php 
	$collection=$this->getAllSelections();
?>

<div class="row">
	<div class="page-title col-xs-12">
	    <div class="block-promos text-center">
	    	<div class="inner-box">
			    <div class="title-block">En ce moment chez vos commerçants</div>
			    <div class="colored-line"></div>
			    	<div id="carrousel-selection-home" class="owl-carousel">
				    	<?php foreach($collection as $entity):
				    		$entity_data=$entity->getData();
				    		$entityNameStripped = $this->stripTags($entity_data['name'], null, true);
				    		if(isset($entity_data['produit_biologique'])){
				    			$label_bio=['AB','Bio Européen','AB,Bio Européen'];
					    		$test_bio=Mage::getResourceSingleton('catalog/product')->getAttribute('produit_biologique')->getSource()->getOptionText($entity_data['produit_biologique']);
					    	}
				    	?>
				    		<div class="product-info products-grid">
					    		<a href="<?= $entity_data['url_path']?>" title="<?= $entityNameStripped;?>">
					    			<img src="<?php echo $this->helper('catalog/image')->init($entity, 'small_image')->resize(250, 250);?>" width="250" height="250" alt="<?php echo $this->htmlEscape($this->getImageLabel($entity, 'small_image'));?>" title="<?php $this->htmlEscape($this->getImageLabel($entity, 'small_image'));?>" />
								    <?php 
								    if(isset($entity_data['produit_biologique']) && in_array($test_bio,$label_bio)){
								            echo '<span class="produit-biologique-selection"><img src="'.$this->getSkinUrl("images/logo_ab_petit.png").'" alt="Bio"/></span>';
								    }?>
					    		</a>
					    		<a href="<?= $entity_data['url_path']?>" title="<?php echo $entityNameStripped;?>"><h2 class="product-name"><?= $entity_data['name']?></h2></a>
								<?php if($entity_data['short_description']) :?>
						        	<div class="product-short_desc"><?= $entity_data['short_description']?></div>
								<?php endif; ?>
				    		</div>
				    	<?php endforeach;?>
				    </div>
		    </div>
	    </div>
	</div>
</div>
<script>
    $j(document).ready(function() {
      $j("#carrousel-selection-home").owlCarousel({
            items:5,
            itemsScaleUp : true,
            pagination:false,
            autoPlay : false,
            navigation : true
      });     
    });
</script>
		
		