<div class="header-neighborhood-container skip-container">
    <a href="#" title="<?php echo $this->__('Neighborhood'); ?>" id="header-neighborhood-link" data-url="<?php echo $this->getUrl('apdc-customer/account/ajaxPopupView');?>">
        <i class="fa fa-home"></i>
        <span class="label"><?php echo $this->__('Neighborhood') ?></span>
    </a>
</div>
<?php $neighborhood = $this->getCurrentNeighborhood(); ?> 
<?php if (!$neighborhood) : ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        window.setTimeout(function() {
            jQuery('#header-neighborhood-link').click();
        }, 4000);
    });
</script>
<?php endif; ?>
