<?php $neighborhoods = $this->getNeighborhoods();?>
<?php $currentNeighborhood = $this->getCurrentNeighborhood(); ?>
<?php $informationType = $this->getInformationsType(); ?>
<ul id="header-neighborhood" class="block block-neighborhood" aria-labelledby="my_neighborhood_menu">
    <?php if ($informationType) : ?>
        <li class="neighborhood_informations apdc-popup-content">
            <?php if ($informationType == 'new_neighborhood'): ?>
                <div class="neighborhood_informations_title"><?php echo $this->__('New!'); ?></div>
                <p><?php echo $this->__('You can now switch between neighborhoods. So it\'s easier if you move or want to delivery at work or to your friends.'); ?></p>
                <!-- <ul>
                    <li><i class="fa fa-eye"></i> <?php echo $this->__('Clicking this icon you can visit the neighborhood and check the shopkeeper and the products of the neighborhood'); ?></li>
                    <li><i class="fa fa-save"></i> <?php echo $this->__('Clicking this icon you set the neighborhood as your new neighborhood'); ?></li>
                </ul> -->
                <div class="neighborhood_ok">
                    <button id="neighborhood_ok" class="button button-green"><span><?php echo $this->__('I Understood'); ?></span></button>
                </div>

            <?php elseif ($informationType == 'no_neighborhood') : ?>
                <div class="neighborhood_informations_title"><?php echo $this->__('Warning!'); ?></div>
                <p><?php echo $this->__('You have not set your neighborhood yet. Please choose your neighborhood by clicking on %s icon', '<i class="fa fa-save"></i>'); ?></p>
            <?php elseif ($informationType == 'not_same_website') : ?>
                <div class="neighborhood_informations_title"><?php echo Mage::helper('apdc_neighborhood')->UserName(); ?></div>
                <p>
                    <?php echo $this->__('%s n\'est pas votre quartier par défaut. Voulez vous changer cela ?',$this->getVisitingNeighborhood()->getName()); ?>
                    <div class="neighborhood_ok">
                        <a href="<?php echo $this->getSaveVisitUrl(); ?>" class="button"><i class="fa fa-save"></i> <?php echo $this->__('Switch to %s', $this->getVisitingNeighborhood()->getName()); ?></a>
                    </div>
                </p>
            <?php endif; ?>
        </li>
    <?php endif; ?>
    <?php if ($currentNeighborhood && $currentNeighborhood->getId()) :  ?>
        <h3 class="neighborhood_title">
            <?php echo $this->__('Your Neighborhood'); ?>
        </h3>
        <?php if ($this->getVisitingNeighborhood() && $this->getVisitingNeighborhood()->getId() != $currentNeighborhood->getId()): ?>
            <li class="neighborhood_list selected">
                <?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($currentNeighborhood->getImage(), array('width' => 50, 'height' => 50)); ?>
                <a href="<?php echo $currentNeighborhood->getStoreUrl(); ?>" title="<?php echo $this->__('Visit this neighborhood'); ?>">
                    <img src="<?php echo $imageUrl; ?>" title="<?php echo $currentNeighborhood->getName(); ?>" width="50" height="50" />
                    <p>
                        <span><?php echo $currentNeighborhood->getName(); ?></span>
                        <i><?php echo $this->__('Available for delivery addresses in %s', implode(', ', $currentNeighborhood->getPostcodes())); ?></i>
                    </p>
                </a>
                <!-- <ul class="neighborhood_actions">
                    <li><a href="<?php echo $currentNeighborhood->getStoreUrl(); ?>" title="<?php echo $this->__('Visit this neighborhood'); ?>"><i class="fa fa-eye"></i></a></li>
                </ul> -->
            </li>
        <?php else : ?>
            <li class="neighborhood_list selected">
                <?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($currentNeighborhood->getImage(), array('width' => 50, 'height' => 50)); ?>
                <img src="<?php echo $imageUrl; ?>" title="<?php echo $currentNeighborhood->getName(); ?>" width="50" height="50" />
                <p>
                    <span><?php echo $currentNeighborhood->getName(); ?></span>
                    <i><?php echo $this->__('Available for delivery addresses in %s', implode(', ', $currentNeighborhood->getPostcodes())); ?></i>
                </p>
            </li>
        <?php endif; ?>
    <?php endif; ?>

    <h3 class="neighborhood_title">
        <?php if ($informationType && ($informationType == 'no_neighborhood' || $informationType == 'new_neighborhood')) : ?>
            <?php echo $this->__('Choose Your Neighborhood'); ?>
        <?php else : ?>
            <?php echo $this->__('Choose Another Neighborhood'); ?>
        <?php endif; ?>
    </h3>
    <?php foreach ($neighborhoods as $neighborhood) : ?>
        <?php if ($currentNeighborhood && $currentNeighborhood->getId() == $neighborhood->getId()) : ?>
            <?php continue; ?>
        <?php endif; ?>
        <li class="neighborhood_list choose">
            <?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($neighborhood->getImage(), array('width' => 50, 'height' => 50)); ?>
            <a href="<?php echo $neighborhood->getStoreUrl(); ?>" title="<?php echo $this->__('Visit this neighborhood'); ?>">
                <img src="<?php echo $imageUrl; ?>" title="<?php echo $neighborhood->getName(); ?>" width="50" height="50" />
                <p>
                    <span><?php echo $neighborhood->getName(); ?></span>
                    <i><?php echo $this->__('Available for delivery addresses in %s', implode(', ', unserialize($neighborhood->getPostcodes()))); ?></i>
                </p>
            </a>
            <?php if ($informationType == 'no_neighborhood') :?>
                <?php if ($this->getSession()->isLoggedIn()) : ?>
                    <ul class="neighborhood_actions">
                        <!-- <li><a href="<?php echo $neighborhood->getStoreUrl(); ?>" title="<?php echo $this->__('Visit this neighborhood'); ?>"><i class="fa fa-eye"></i></a></li> -->
                        <li><a href="<?php echo $this->getSaveUrl($neighborhood); ?>" title="<?php echo $this->__('Set % as my new neighborhood',$neighborhood->getName()); ?>"><i class="fa fa-save"></i></a></li>
                    </ul>
                <?php endif; ?>
            <?php endif ?>
        </li>
    <?php endforeach; ?>
</ul>
<script type="text/javascript">
    var neighborhoodIUnderstoodUrl = '<?php echo $this->getNeighborhoodIUnderstoodUrl(); ?>';
</script>
