<?php
$neighborhood = $this->getSession()->getNeighborhood();
$customerDefaultPostcode = '';
if (!$neighborhood) {
    $customerDefaultPostcode = Mage::helper('apdc_neighborhood')->getCustomerDefaultPostcode();
}
?>
<div id="header-neighborhood" class="block block-neighborhood" aria-labelledby="my_neighborhood_menu">
    <h3 class="neighborhood_title">
        <?php if ($neighborhood && $neighborhood->getId()) : ?>
            <?php echo $this->__('Vous souhaitez changer de d\'adresse de livraison ?'); ?>
        <?php else : ?>
            <?php echo $this->__('Choisir une adresse de livraison'); ?>
        <?php endif; ?>
    </h3>
    <div class="neighborhood_choose" id="search_neighborhoods">
        <?php if (!$neighborhood && $customerDefaultPostcode) : ?>
            <p><?php echo $this->__('Merci de confirmer votre adresse afin de nous aider à sélectionner les commerçants proche de chez vous.'); ?></p>
        <?php else : ?>
            <p><?php echo $this->__('Merci d\'indiquer votre adresse afin de nous aider à sélectionner les commerçants proche de chez vous.'); ?></p>
        <?php endif; ?>
        <?php echo $this->getChildHtml('address-bar');?>
    </div>
</div>
