<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<!--Iphone webapp-->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="format-detection" content="telephone=yes">
<link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->getSkinUrl('images/apple-touch-icon-72x72.png', array('_secure'=>true));?>">
<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->getSkinUrl('images/apple-touch-icon-114x114.png', array('_secure'=>true));?>">
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->getSkinUrl('images/apple-touch-icon-180x180.png', array('_secure'=>true));?>">
<link rel="apple-touch-icon" href="<?php echo $this->getSkinUrl('images/apple-touch-icon-180x180.png', array('_secure'=>true));?>">
<link rel="apple-touch-startup-image" href="<?php echo $this->getSkinUrl('images/splash-startup.png', array('_secure'=>true));?>">
<!--Chrome webapp-->
<link rel="manifest" href="<?php echo $this->getSkinUrl('webapp/manifest.json', array('_secure'=>true));?>">
<meta name="mobile-web-app-capable" content="yes">
<link rel="icon" sizes="192x192" href="<?php echo $this->getSkinUrl('images/apple-touch-icon-192x192.png', array('_secure'=>true));?>">
<!--Other webapp-->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="HandheldFriendly" content="true">
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '1709948302620869');
fbq('track', "PageView");</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1709948302620869&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->