<?php

namespace Apdc\ApdcBundle\Repository;

/**
 * IndiPayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndiPayoutRepository extends \Doctrine\ORM\EntityRepository
{
}
