<?php

namespace Apdc\ApdcBundle\Repository;

/**
 * NoteOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
