<?php

namespace Apdc\ApdcBundle\Repository;

/**
 * PayoutChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayoutChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
