<?php
/**
 * Inchoo is not affiliated with or in any way responsible for this code.
 *
 * Commercial support is available directly from the [extension author](http://www.techytalk.info/contact/).
 *
 * @category Marko-M
 * @package SocialConnect
 * @author Marko Martinović <marko@techytalk.info>
 * @copyright Copyright (c) Marko Martinović (http://www.techytalk.info)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<div class="clearer">
    <div class="inchoo-socialconnect-facebook">
        <div class="inchoo-socialconnect-facebook-inner">
            <a href="#" id="connect_with_facebook" data-ajax-action="<?php echo $this->getUrl('apdc_customer/facebook/ajaxLogin'); ?>"><?php echo $this->__('Se Connecter Avec Facebook'); ?></a>
        </div>
        <div class="inchoo-socialconnect-facebook-right"></div>
    </div>
</div>
