<?php 
	//Get Collection of products
	$current_cat=Mage::registry('current_category');
	$current_cat_name=Mage::registry('current_category')->getName();
	$current_cat_Id=Mage::registry('current_category')->getId();
	$selections=$this->getSelectionbyById($current_cat_Id);
?>
<?php if($selections<>null):?>
<div class="row">
	<div class="page-title col-xs-12">
	    <div class="block-promos text-center">
	    	<div class="inner-box">
			    <div class="title-block">En ce moment chez <?= '</br>'.$current_cat_name?></div>
			    <div class="colored-line"></div>
			    	<div id="carrousel-selection-home" class="owl-carousel">
				    	<?php foreach($selections as $selection):?>
				    		<div class="product-info products-grid">
					    		<a href="<?= $selection['url_path']?>" title="<?= $selection['stripped_name'];?>">
					    			<img src="<?= $selection['image_src']?>" width="250" height="250" alt="<?= $selection['image_label'];?>" title="<?= $selection['image_label'];?>" />
								    <?= $selection['html_bio']?>
					    		</a>
					    		<a href="<?= $selection['url_path']?>" title="<?= $selection['stripped_name'];?>"><h2 class="product-name"><?= $selection['name']?></h2></a>
						       	<div class="product-short_desc"><?= $selection['short_description']?></div>
				    		</div>
				    	<?php endforeach;?>
				    </div>
		    </div>
	    </div>
	</div>
</div>
<script>
    $j(document).ready(function() {
      $j("#carrousel-selection-home").owlCarousel({
            items:5,
            itemsScaleUp : true,
            pagination:false,
            autoPlay : false,
            navigation : true
      });     
    });
</script>
<?php endif;?>
