<div id="commercants-block" class="row hp-section commercants-block">
	<div class="commercants-list col-md-12">
		<div class="title-block">Mes Commer&ccedil;ants</div>
		<div class="colored-line"></div>
		<div class="row">
			<div class="commercants-main products-grid col-md-12">
				<div id="carrousel-commercants" class="owl-carousel">
					<?php
						
						//Limite le nombre de vignette visible et les affiche dans un ordre aléatoire
						$fiches=$this->getListCommercant();
						$fiches->getSelect()->orderRand();
						foreach ($fiches as $fiche){
							$_NameStripped = $this->stripTags($fiche->getName(), null, true);
							$_thumbnail=$fiche->getThumbnail();
							$src = Mage::getBaseUrl('media').'catalog/category/'.$_thumbnail;
							$_name=$fiche->getName();
							$_adresse=$fiche->getData('adresse_commercant');
							$url=$fiche->getUrl();
							?>
							<div class="commercant-item">
					            <a class="product-image" href="<?php echo $url;?>" title="<?php echo $_NameStripped;?>">
					                <img src="<?php echo $src;?>" width="100%" alt="<?php echo $_NameStripped; ?>" title="<?php echo $_NameStripped; ?>" />
					            </a>
					            <h3 class="product-name"><?php echo $_name; ?></h3>
					            <span><?php echo $_adresse; ?></span>
					        </div>    	
					<?php
						}
						?>
						<!-- Commerçants à venir -->
						<div class="commercant-item">
				            <a class="product-image" href="<?php echo Mage::getBaseUrl().'commercant-form/'?>" title="A venir">
				                <img src="<?php echo Mage::getBaseUrl('media').'resource/commerçant_dummy.png'?>" width="100%" alt="" title="" />
				            </a>
				            <h3 class="product-name" style="text-align:center;"><a href="<?php echo Mage::getBaseUrl().'commercant-form/'?>">Suggérez nous votre commerçant, Cliquez ici!</a></h3>
				        </div>  
				</div>
			</div>
		</div>
		<!-- Disable for now
		<div class="row text-center">
			<a class="btn brown commercants" href="<?php echo Mage::getBaseUrl().'commercants'?>">Voir tous les commerçants</a>
		</div> -->
	</div>
</div>