<?php
    //Récupération de la fiche du commerçant
    $current_cat=Mage::registry('current_category');
    $current_cat_Name=$current_cat->getName();	
    $current_cat_Id=Mage::registry('current_category')->getId();
 ?>
<div class="row">
	<div class="page-title category-title col-xs-12">
	    <h1 class="subtitle commercant_name"><?php echo $current_cat_Name ?></h1>
	</div>
</div>
<div class="row">
	<div class="col-md-12 commercant-bottom-margin">
		<div class="row">
			<div class="col-md-6" style="z-index:9;">
				<div class="photo-commercant">
					<img class="img-responsive img-thumbnail" src="<?php echo $current_cat->getImageURL() ?>">
				</div>
			</div>
			<div class="col-md-6 commercant-selection">
				<h2 class="title-block" style="width:300px">La petite histoire</h2>
				<div class="colored-line"></div>
				<div class="desc-commercant">
					<p><?php echo $current_cat->getData('description') ?></p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="row commercant-selection">
			<h2 class="title-block" style="width:300px">Les infos pratiques</h2>
			<div class="colored-line"></div>
			<div class="col-md-6">
				<dl class="dl-horizontal infos-commercant">
				  <dt>Adresse</dt>
				  <dd><a href="https://www.google.fr/maps/place/<?php echo str_replace(" ","+",$current_cat->getData('adresse_commercant'));?>" target="_blank"><?php echo $current_cat->getData('adresse_commercant');?></a>
				  </dd>
				   <dt>Horaires</dt>
				   <dd>
				   		<?php $array=explode(',',$current_cat->getData('horaires_commercant'));
				   		foreach($array as $day){
				   			echo $day.'<br/>';
				   		} 
				   		?>
				   	</dd>
				   <!--
				   <dt>Badge</dt>
				  <dd><?php echo $current_cat->getData('badge_commercant') ?></dd>-->
				</dl>
			</div>
			<div class="col-md-6">
				<dl class="dl-horizontal infos-commercant">
				  <dt>Jour livraisons</dt>
				  <dd><?php echo $current_cat->getData('livraison_commercant') ?></dd>
				  <dt>Téléphone</dt>
				  <dd><?php echo $current_cat->getData('telephone') ?></dd>
				</dl>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="commercant_product_cat commercant-selection">
		<h2 class="title-block" style="width:300px">Les rayons</h2>
		<div class="colored-line"></div>
		<?php
		$childrenCat = Mage::getModel('catalog/category')->getCategories($current_cat_Id);?>
		<div class="col-md-12">
			    <div id="carrousel-cats" class="owl-carousel">
					<?php
						foreach ($childrenCat as $cat) {
							$cat=Mage::getModel('catalog/category')->load($cat->getId());?>
								<div class="linkcat">
									<a href="<?php echo $cat->getUrl()?>">
									<div class="img-wrapper">
									    <img class="img-responsive img-thumbnail" src="<?php echo $cat->getThumbnailUrl($cat)?>" alt="<?php echo $this->htmlEscape($cat->getName())?>" title="<?php echo $this->htmlEscape($cat->getName())?>" />
									    <div class="description">
									    		<span><?php echo $this->htmlEscape($cat->getName())?></span>
									    </div>
									</div>
									</a>
							    </div>
						<?php } 
					//Reset the category to the current category, otherwise use last category data in foreach loop
					Mage::getSingleton('catalog/layer')->setCurrentCategory($current_cat_Id);  
					?>
				</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12 block_selection">
		<?php echo $this->getChildHtml('blockselection')?>
	</div>
	<!-- <div class="col-md-6 block_lastorders">
		<?php echo $this->getChildHtml('lastorder')?>
	</div> -->
</div>

<script>
    $j(document).ready(function() {
     
      $j("#carrousel-cats").owlCarousel({
            items:4,
            pagination:false,
            autoPlay : false,
            navigation : true
      });
     
    });
</script>