<?php
    //Récupération de la fiche du commerçant
    $current_cat=Mage::registry('current_category');  
    $current_cat_data=$current_cat->getData();
    $horaires=str_replace(',','</br>',$current_cat_data['horaires_commercant']);
    $url_adresse="https://www.google.fr/maps/place/".str_replace(" ","+", $current_cat_data['adresse_commercant']);
    $delivery_days=$current_cat->getResource()->getAttribute('delivery_days')->getFrontend()->getValue($current_cat);

 ?>
<div class="row">
	<div class="page-title category-title col-xs-12">
	    <h1 class="subtitle commercant_name"><?= $current_cat_data['name'] ?></h1>
	</div>
</div>
<div class="row">
	<div class="col-md-12 commercant-bottom-margin">
		<div class="row">
			<div class="col-md-6" style="z-index:9;">
				<div class="photo-commercant">
					<img class="img-responsive img-thumbnail" src="<?php echo $current_cat->getImageURL() ?>">
				</div>
			</div>
			<div class="col-md-6 commercant-selection">
				<h2 class="title-block" style="width:300px">La petite histoire</h2>
				<div class="colored-line"></div>
				<div class="desc-commercant">
					<p><?= $current_cat_data['description'] ?></p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="row commercant-selection">
			<h2 class="title-block" style="width:300px">Les infos pratiques</h2>
			<div class="colored-line"></div>
			<div class="col-md-6">
				<dl class="dl-horizontal infos-commercant">
				  <dt>Adresse</dt><dd><a href="$url_adresse" target="_blank"><?= $current_cat_data['adresse_commercant'];?></a></dd>
				   <dt>Horaires</dt><dd><?= $horaires?></dd>
				</dl>
			</div>
			<div class="col-md-6">
				<dl class="dl-horizontal infos-commercant">
				  <dt>Jour livraisons</dt><dd><?= $delivery_days ?></dd>
				  <dt>Téléphone</dt><dd><?= $current_cat_data['telephone'] ?></dd>
				</dl>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<?php echo $this->getChildHtml("commercant-categories");?>
</div>
<div class="row">
	<div class="col-sm-12 block_selection">
		<?php echo $this->getChildHtml('blockselection')?>
	</div>
</div>