<?php 
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/
?>

<ul class="links">
	<li class="first"><b><?php echo $this->__('Invitations'); ?></b></li>
	<li><a title="My Referrals" href="<?php echo $this->getUrl('*/referral') ?>"><?php echo $this->__('My Referrals'); ?></a></li>
	<li><a title="My Credits" href="<?php echo $this->getUrl('*/credit') ?>"><?php echo $this->__('My Credits'); ?></a></li>
	<li><a title="My Payments" href="<?php echo $this->getUrl('*/payment') ?>"><?php echo $this->__('My Payments'); ?></a></li>
</ul>
<br /><br />



<?php  echo $this->getMessagesBlock()->getGroupedHtml(); ?>


<div class="page-title"><h1><?php echo $this->__( 'Invitation' ); ?></h1></div>
<?php if(!$this->canInvite()) { ?>
	<p><?php echo $this->__( 'Please place an order to have access to Refer a Friend'); ?></p>
<?php }
	else { ?>


	<script language="javascript" type="text/javascript">
	jQuery(document).ready(function() {
		jQuery('#email_upload_block').hide();
		var $items = jQuery('#invitationtab>ul>li');
		$items.mouseover(function() {
			$items.removeClass('selected');
			jQuery(this).addClass('selected');

			var index = $items.index(jQuery(this));
			jQuery('#invitationtab>div').hide().eq(index).show();
		}).eq(0).mouseover();
	});

	var str_email = "<?php echo $this->__( 'Email'); ?>";
	var str_uploaded_emails = "Email(s) uploadé(s)";
	//var str_uploaded_emails = "<?php echo $this->__( 'Uploaded Email'); ?>";
	var ajax_url = "<?php echo $this->getUrl('*/*/ajaxuploadone') ?>";

	var idnext = 0;
	var maxemails = "<?php echo $this->getEmailLImit(); ?>";
	function add_email_field() {
		idnext++;
		if(idnext>=maxemails) return;
		var elem = document.createElement("div");
		elem.id = 'emailfield'+idnext;
		elem.innerHTML = str_email+' <input type="text" name="email_to[]" /> <button type="button" onclick="del_email_field(\'emailfield'+idnext+'\');"> &nbsp;-&nbsp; </button>';
		document.getElementById('email_container').appendChild(elem);
	}
	function del_email_field(id) { var div = document.getElementById(id); div.parentNode.removeChild(div); }

	function checkall(is_checked,elem_name) {
		if(is_checked) jQuery("input:checkbox."+elem_name).attr('checked','checked');
		else jQuery("input:checkbox."+elem_name).removeAttr('checked');
	}

	function toggle_email_section(img_id,div_id) {

		if(jQuery("#"+div_id).is(':hidden')) {
			jQuery('#'+div_id).show('slow');
			jQuery('#'+img_id).attr('src','<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-16-arrow-down.png'); ?>');
		}
		else {
			jQuery('#'+div_id).hide('slow');
			jQuery('#'+img_id).attr('src','<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-16-arrow-right.png'); ?>');
		}
	}


	function upload_email_one() {
		email = jQuery('#email_one').val();
		jQuery('#email_one').val('');
		if(jQuery("#data_container_upload").length == 0) {
			//it doesn't exist so add it
			jQuery('#email_container').append('<div id="data_container_upload"></div>');
		}
		jQuery('#data_container_upload').html('<span><img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/loading.gif'); ?>" /></span>');
		jQuery.ajax({
			type: "POST",
			url: ajax_url,
			data: { 'task':'invite_uploadone','tmpl':'component','no_html':1,'email': email },
			success: function(data) {
				// now reload emails
				myhtml = '<div>\
							<img id="img_email_import_upload" src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-16-arrow-down.png'); ?>" onclick="toggle_email_section(\'img_email_import_upload\',\'data_email_import_upload\');"/>\
							<b>'+str_uploaded_emails+'</b>\
							<input type="checkbox" onclick="checkall(this.checked,\'email_to_import_upload\')" CHECKED>\
						</div>\
						<div id="data_email_import_upload" class="emails_imported">';
				jQuery.each(data, function(key, val) {
					myhtml += '<div><input type="checkbox" CHECKED class="email_to_import_upload" name="email_to_import_upload[]" value="'+val.email+'"> '+val.email+'</div>';
				})
				myhtml += '</div><br />';
				jQuery('#data_container_upload').html(myhtml);

			},
			dataType: 'json'
		});
		//alert(email);
		jQuery('#email_one').focus();
	}

	function switch_templates(type,id) {
		jQuery('.invitation_template_'+type).hide();
		jQuery('#invitation_template_'+id).show();
			  if(type=='email') document.frmEmail.invitation_id.value = id;
		else if(type=='facebook') document.frmFacebook.invitation_id.value = id;
		else if(type=='twitter') document.frmTwitter.invitation_id.value = id;
	}
	</script>


	<div class="welcome-msg">
		<!-- <p><?php echo $this->getInvitationDescription(); ?></p> -->
		<h2>Votre lien unique</h2>
		<p>C'est ce lien qui permettra à vos filleuls de vous faire bénéficier de vos avantages parrain.</p>
		<div class="customer-link-box">
			<a href="<?php echo Mage::helper('awodev_aworewards/data')->registration_link();?>"><?php echo Mage::helper('awodev_aworewards/data')->registration_link();?></a>
		</div>
		<p>Envoyez votre lien unique à tous vos proches. S'ils l'utilisent pour s'enregistrer sur Au Pas De Courses, ils gagneront des avantages et vous en ferons également bénéficier.</p>
		<p>N'hésitez pas à le poster sur votre mur Facebook, à l'envoyer par mail, ou à utiliser le formulaire ci-dessous</p>
		<h3>Avantages pour vos filleuls:</h3>
		<ul>
			<li>La 1ere livraison est gratuite dès leur première commande</li>
			<li>Ils reçoivent chacun 10€ de réduction dès qu'ils commandent pour plus de 35€ sur Au Pas De Courses, sur une ou plusieurs commandes (valable une seule fois)</li>
		</ul>
		<p></p>
		<h3>Vos avantages:</h3>
		<ul><li>Vous recevez 10€ pour la première commande de chacun de vos filleuls.</li></ul>
		<div class="call-to-action">
			<p class="principal">Plus vous parrainez et plus vous gagnez!</p>
			<p>Utilisez le formulaire ci-dessous, votre propre messagerie, votre mur Facebook ... pour coller votre lien unique et envoyer vos parrainages.</p>
		</div>
	</div>
	<br/>
	<?php 
	$_invitations = $this->getInvitations();
	$_invitation_firstkey = array();
	if(!empty($_invitations['email'])) $_invitation_firstkey['email'] = key($_invitations['email']);
	if(!empty($_invitations['facebook'])) $_invitation_firstkey['facebook'] = key($_invitations['facebook']);
	if(!empty($_invitations['twitter'])) $_invitation_firstkey['twitter'] = key($_invitations['twitter']);
	?>
	<div id="invitationtab">
		<ul class="<?php if(count($_invitations)<2) echo 'hide';?>">
			<?php if(isset($_invitations['email'])) : ?><li class="support"></li><?php endif; ?>
			<?php if($this->is_facebook() && isset($_invitations['facebook'])) : ?><li class="facebook"></li><?php endif; ?>
			<?php if($this->is_twitter() && isset($_invitations['twitter'])) : ?><li class="twitter"></li><?php endif; ?>
		</ul>
		<?php if(isset($_invitations['email'])) { ?>
		<div class="<?php if(count($_invitations)<2) echo 'onlyone';?>">
			<h4><?php echo $this->__( 'Email Directly'); ?></h4>
			<?php
			if($this->is_google_import()) :
			?>
				<div class="getter_link">
					<form name="frmgmail" method="post" action="<?php echo $this->getUrl('*/*/socialmail') ?>">
						<a href="javascript:document.frmgmail.submit();">
							<img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon_50_google_r.png'); ?>" alt="google" />
							<span ><?php echo $this->__( 'Download Email addresses from Google Mail'); ?></span>
						</a>
						<noscript><input type="submit" value="<?php echo $this->__( 'Download Email addresses from Google Mail'); ?>" /></noscript>
						<input type="hidden" name="getter" value="google" />
					</form>
				</div>
			<?php
			endif;
			if($this->is_yahoo_import()) :
			?>
				<div class="getter_link">
					<form name="frmymail" method="post" action="<?php echo $this->getUrl('*/*/socialmail') ?>">
						<a href="javascript:document.frmymail.submit();">
							<img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon_50_yahoo_r.png'); ?>" alt="yahoo" />
							<span ><?php echo $this->__( 'Download Email addresses from Yahoo Mail'); ?></span>
						</a>
						<noscript><input type="submit" value="<?php echo $this->__( 'Download Email addresses from Yahoo Mail'); ?>" /></noscript>
						<input type="hidden" name="getter" value="yahoo" />
					</form>
				</div>
			<?php 
			endif; 
			?>
			<!--<div class="getter_link">
				<a href="javascript:void(0);" onclick="jQuery('#email_upload_block').toggle();return false;">
					<img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon_50_upload.png'); ?>" alt="upload" />
					<span><?php echo $this->__( 'Envoi de plusieurs emails par fichier texte'); ?></span>
					<!-- <span><?php echo $this->__( 'Upload Email addresses with text file, one per line'); ?></span> -->
				<!--</a>
				<div id="email_upload_block">
					<form method="post" action="<?php echo $this->getUrl('*/*/importemail') ?>" enctype="multipart/form-data">
						<input type="file" name="file" /> <input type="submit" value="<?php echo $this->__( 'Submit'); ?>" />
					</form>
				</div>
			</div>-->
			<div class="getter_link">
				<form onsubmit="upload_email_one(); return false;">
					<img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon_50_pencil.png'); ?>" alt="upload one" />
					<span>
						<?php echo $this->__( 'Email'); ?>
						<div class='row' style="margin-top:10px">
							<div class="col-xs-6">
								<input type="text" id="email_one" name="email_one" />
							</div>
							<div class="col-xs-1">
								<input type="submit"  class="button" style="float:left;" value="Ajouter" />
							</div>
						</div>
					</span>
				</form>
			</div>
			<br />

			<form name="frmEmail" method="post" action="<?php echo $this->getUrl('*/*/sendinvite') ?>" class="adminform" onsubmit="this.Submit.disabled=true; return true;">

				<div><b><?php echo $this->__( 'To');?></b></div>
				<div id="email_container">
				<?php
					$loaded_emails = $this->getLoadedEmails(); 
					if(!empty($loaded_emails)) :
						foreach($loaded_emails as $getter=>$email_section) :
				?>
							<div id="data_container_<?php echo $getter;?>">
								<div>
									<img id="img_email_import_<?php echo $getter;?>" src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-16-arrow-down.png'); ?>" onclick="toggle_email_section('img_email_import_<?php echo $getter;?>','data_email_import_<?php echo $getter;?>');"/>
									<b><?php 
										$title = '';
										if($getter=='google') $title = 'Google Mail';
										elseif($getter=='yahoo') $title = 'Yahoo Mail';
										elseif($getter=='upload') $title = 'Uploaded Emails';
										echo $this->__($title);
									?></b>
									<input type="checkbox" onclick="checkall(this.checked,'email_to_import_<?php echo $getter;?>')" CHECKED>
								</div>
								<div id="data_email_import_<?php echo $getter;?>" class="emails_imported" >
									<?php foreach($email_section as $email) : ?>
										<div><input type="checkbox" CHECKED class="email_to_import_<?php echo $getter;?>" name="email_to_import_<?php echo $getter;?>[]" value="<?php echo $email; ?>"> <?php echo $email; ?></div>
									<?php endforeach; ?>
								</div>
							<br />
							</div>
						<?php endforeach; ?>
					<?php endif; ?>
					
				</div>
				<br />
				
				
				<div class="bold"><?php echo $this->__( 'Personal Message'); ?></div>
				<div>
					<?php if(count($_invitations['email'])>1) : ?>
						<select onchange="switch_templates('email',this.value);">
						<?php foreach($_invitations['email'] as $k=>$invitation) : ?>
							<option value="<?php echo $k; ?>"><?php echo $invitation['dd']; ?></option>
						<?php endforeach; ?>
						</select>
					<?php endif; ?>
				</div>
				
				<div class="personalmsg">
					<?php foreach($_invitations['email'] as $k=>$invitation) : ?>
						<div id="invitation_template_<?php echo $k; ?>" class="invitation_template_email <?php if($k!=$_invitation_firstkey['email']) echo 'hide2'; ?>">
							
							<?php echo $invitation['body1']; ?>
							<?php if(!empty($invitation['isnote'])) : ?>
								<textarea class="inputbox" cols="60" rows="7" name="custommessage_<?php echo $k; ?>" onFocus="if(this.value=='<?php echo $this->__('Your message here...');?>')this.value=''" ><?php echo $this->__('Your message here...');?></textarea>
							<?php endif; ?>
							<?php echo $invitation['body2']; ?>
						</div>
					<?php endforeach; ?>
				</div>
				

				
				<br />
				
				<div align="center"><input type="submit" name="Submit" value="<?php echo $this->__( 'Submit'); ?>" class="button" /></div>

				<input type="hidden" name="invitation_id" value="<?php echo $_invitation_firstkey['email']; ?>" />
			</form>

		</div>
		<?php } ?>
		<?php if($this->is_facebook() && isset($_invitations['facebook'])) { ?>
		<div class="<?php if(count($_invitations)<2) echo 'onlyone';?>">
			<h4><?php echo $this->__( 'Post to Facebook Wall'); ?></h4>
			<div>
				
				<div class="bold"><?php echo $this->__( 'Personal Message'); ?></div>
				<div>
					<?php if(count($_invitations['facebook'])>1) : ?>
						<select onchange="switch_templates('facebook',this.value);">
						<?php foreach($_invitations['facebook'] as $k=>$invitation) : ?>
							<option value="<?php echo $k; ?>"><?php echo $invitation['dd']; ?></option>
						<?php endforeach; ?>
						</select>
					<?php endif; ?>
				</div>
				
				<form name="frmFacebook" method="post" action="<?php echo $this->getUrl('*/*/socialpost') ?>" >
					<div class="personalmsg">
						<?php foreach($_invitations['facebook'] as $k=>$invitation) : ?>
							<div id="invitation_template_<?php echo $k;?>" class="invitation_template_facebook <?php if($k!=$_invitation_firstkey['facebook']) echo 'hide2'; ?>">
						
								<?php echo $invitation['body1']; ?>
								<?php if(!empty($invitation['isnote'])) : ?>
									<textarea class="inputbox" cols="60" rows="7" name="custommessage_<?php echo $k;?>" onFocus="if(this.value=='<?php echo $this->__('Your message here...');?>')this.value=''" ><?php echo $this->__('Your message here...');?></textarea>
								<?php endif; ?>
								<?php echo $invitation['body2']; ?>
							</div>
						<?php endforeach; ?>
					</div>
					<!-- <input type="submit" value="<?php echo $this->__( 'Post to Facebook Wall'); ?>" /> -->
					<div align="center"><input type="submit" name="Envoyez" value="<?php echo $this->__( 'Submit'); ?>" class="button" /></div>
					<input type="hidden" name="getter" value="facebook" />
					<input type="hidden" name="getter_type" value="postpublic" />
					<input type="hidden" name="invitation_id" value="<?php echo $_invitation_firstkey['facebook']; ?>" />
				</form>
				
			</div>
		
		</div>
		<?php } ?>
		<?php if($this->is_twitter() && isset($_invitations['twitter'])) { ?>
		<div class="<?php if(count($_invitations)<2) echo 'onlyone';?>">
			<h4><?php echo $this->__( 'Tweet About Us'); ?></h4>
			<div>
			
				<div class="bold"><?php echo $this->__( 'Personal Message'); ?></div>
				<div>
					<?php if(count($_invitations['twitter'])>1) : ?>
						<select onchange="switch_templates('twitter',this.value);">
						<?php foreach($_invitations['twitter'] as $k=>$invitation) : ?>
							<option value="<?php echo $k; ?>"><?php echo $invitation['dd']; ?></option>
						<?php endforeach; ?>
						</select>
					<?php endif; ?>
				</div>
				
				<form name="frmTwitter" method="post" action="<?php echo $this->getUrl('*/*/socialpost') ?>" >
					<div class="personalmsg">
						<?php foreach($_invitations['twitter'] as $k=>$invitation) : ?>
							<div id="invitation_template_<?php echo $k;?>" class="twitter <?php if($k!=$_invitation_firstkey['twitter']) echo 'hide2'; ?>">
						
								<?php echo $invitation['body1']; ?>
								<?php if(!empty($invitation['isnote'])) : ?>
									<textarea class="inputbox" cols="60" rows="7" name="custommessage_<?php echo $k;?>" onFocus="if(this.value=='<?php echo $this->__('Your message here...');?>')this.value=''" ><?php echo $this->__('Your message here...');?></textarea>
								<?php endif; ?>
								<?php echo $invitation['body2']; ?>
							</div>
						<?php endforeach; ?>
					</div>
					<input type="submit" value="<?php echo $this->__( 'Tweet About Us'); ?>" />
					<input type="hidden" name="getter" value="twitter" />
					<input type="hidden" name="getter_type" value="postpublic" />
					<input type="hidden" name="invitation_id" value="<?php echo $_invitation_firstkey['twitter']; ?>" />
				</form>
			
			
			
			</div>
		
		</div>
		<?php } ?>
		

		
	</div>


<?php } ?>









<br />
<br />
<br />



