<?php 
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Deliverydate
 */
$deliveryDate = $this->getDeliveryDateProgress();
if (is_array($deliveryDate) && !empty($deliveryDate)): ?>
<!-- BEGIN Checkout Progress `Amasty: Delivery Date` -->
    <?php
        $hlp = Mage::helper('amdeliverydate');
        foreach($deliveryDate as $key => $value) {
            switch ($key) {
                case 'date':
                    if ($value) {
                        echo '<br />'
                            . $hlp->__('Delivery Date') . ': '
                            . $value;
                    }
                    break;
                case 'time':
                    if ($value) {
                        echo '<br />'
                            . $hlp->__('Delivery Time Interval') . ':<br />'
                            . $value;
                    }
                    break;
                case 'comment':
                    if ($value) {
                        echo '<br />'
                            . $hlp->__('Delivery Comments') . ':<br />'
                            . nl2br(htmlentities(preg_replace('/\$/','\\\$', $value), ENT_COMPAT, "UTF-8"));
                    }
                    break;
            }
        }
    ?>
<!-- END Checkout Progress `Amasty: Delivery Date` -->
<?php endif; ?>