<tr>
    <td class="a-right cart-total-shipping">
        <?php echo $this->__('Livraison à domicile'); ?>
    </td>
    <td class="a-right cart-total-shipping">
        <?php if ($this->isFreeShipping()): ?>
            <?php echo $this->__('OFFERTE') ?>
        <?php else: ?>
            <?php 
            $totals=$this->getTotal();
            echo $this->helper('checkout')->formatPrice($totals->getValue()*(1+$this->getVAT()/100)) ?>
        <?php endif; ?>
    </td>
</tr>