<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$_points = $this->getPointTotal();
?>

<div class="entry-edit">
	<div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo $this->__('AwoRewards Points'); ?></h4></div>
	<?php if(!empty($_points)):?>
	<fieldset>
		<table cellspacing="2" class="box-left"><tbody>
			<tr>
				<td><strong><?php echo $this->__('Total Points') ?>:</strong></td>
				<td><?php echo number_format($_points['total'],2) ?></td>
			</tr>
			<tr>
				<td><strong><?php echo $this->__('Claimed Points') ?>:</strong></td>
				<td><?php echo number_format($_points['claimed'],2) ?></td>
			</tr>
			<tr>
				<td><strong><?php echo $this->__('Unclaimed Points') ?>:</strong></td>
				<td><?php echo number_format($_points['unclaimed'],2) ?></td>
			</tr>
		</tbody></table>
	</fieldset>
	
	<div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo $this->__('Other'); ?></h4></div>
	<fieldset>
		<table cellspacing="2" class="box-left"><tbody>
			<tr>
				<td><strong><?php echo $this->__('Generated Registration LInk') ?>:</strong></td>
				<td><?php $link = $this->getLink(); echo '<a href="'.$link.'" target="_blank">'.$link.'</a>'; ?></td>
			</tr>
		</tbody></table>
	</fieldset>
	<?php else:?>
	<strong style="color:red;">Warning: Aworewards doesn't seems to be properly set up!!!</strong>
	<?php endif;?>
</div>


