<!-- DataTables -->
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.js"></script>
<script>
function screenshot(){
	html2canvas($('#data_commande'), {
		onrendered: function(canvas) {
		var myImage = canvas.toDataURL("image/png");
		var order_id=$("#incrementid-dropdown").val();
		Pic = myImage.replace(/^data:image\/(png|jpg);base64,/, "");

    // Sending the image data to Server
    $.ajax({
        url: 'save.php',
		type: 'post',
		        data: {
		            image: Pic,
		            orderid:order_id,
		            name:order_id+'_remb.png'
		        },
		        dataType: 'image/png',
        success: function (msg) {
            alert("Done, Picture Uploaded.");
        }
    });
		    //window.open(myImage);
		}
	});	
};
function ticketimage(){

};

</script>
<?php
			//récupération de la liste des commandes (numéro et date)
			$orderid_array=get_list_orderid();
			krsort($orderid_array);

    		//Récupération des données de la commande si spécifié
    		if(isset($_GET['increment_id'])){
    			$select_id=$_GET['increment_id'];			
    			$order=Mage::getModel('sales/order')->loadByIncrementId($select_id);
    		}else{
    			$select_id='';
    		}
?>

<body>
  <div id="canvas" class="container theme-showcase" role="main">
    <div class="page-header">
			<label class="control-label">Remboursement de la commande n°: </label><select id="incrementid-dropdown" class="form-control">
	    		<?php foreach($orderid_array as $id => $d){
	    			echo '<option ';
	    			if($_GET['increment_id']==$id){echo "selected";}
	    			echo '>'.$id.'</option>';
	    		}?>
	    	</select>
    </div>
    <div id="filter"><label>Sélectionnez le commerçant:</label></div>
    <div class="row">
    	<div id="data" class="col-sm-12">
	    	<table class="display dt-responsive no-wrap" id="data_commande">
		    	 <thead>
			      <tr>
					<th>Produit</th>
					<th class="sort">Commerçant</th>
					<th>Prix à l'unité</th>
					<th>Prix Unitaire</th>
					<th class="float">Quantité facturée</th>
					<th class="float">Prix total</th>
					<th class="float" id="prixfinal">Prix final</th>
					<th class="float" id="diffprixfinal">Dif prix tot</th>
					<th class="float" id="diffprixCGV">Dif prix CGV</th>
			      </tr>
			    </thead>
			    <tbody>
				    <?php
				    	if(isset($_GET['increment_id'])){
					    	$ordered_items = $order->getAllItems();
							$sorted_items = array();
							  foreach ($ordered_items as $item) {
							      if (!$item->isDeleted()) {
							          $sorted_items[] =  $item;
							      }
							  }

					    	$tot_qty=0;
					    	$sum=0;
					      	foreach($sorted_items as $item){
					      		$itemid=$item->getProduct()->getId();
						      	$product = Mage::getModel('catalog/product')->load($itemid);
									echo '<tr>';
										echo '<td class="col-sm-2"><a href="'.$product->getProductUrl().'">'.$item->getName().'</a></td>';
										echo '<td class="col-sm-2 sort">'.$product->getAttributeText('commercant').'</td>';
										if($item->getPrixKiloSite()<>""){
											echo '<td class="prix_unite col-sm-2">'.$item->getPrixKiloSite().'</td>';
										}else{
											echo '<td class="prix_unite col-sm-2">'.$product->getPrixKiloSite().'</td>';
										}
										echo '<td class="col-sm-1">'.round($item->getPriceInclTax(),2).'</td>';
										echo '<td class="col-sm-1">'.round($item->getQtyOrdered(),0).'</td>';
										echo '<td class="col-sm-1">'.round($item->getRowTotalInclTax(),2).'</td>';
										echo '<td class="col-sm-1"><input type="text" name="'.$itemid.'-prixfinal" class="prixfinal" style="width:60px" value="'.round($item->getRowTotalInclTax(),2).'"></td>';
										echo '<td class="diffprixfinal">0</td>';
										echo '<td class="diffprixcgv">0</td>';
									echo '</tr>';
								$tot_qty+=$item->getQtyOrdered();
								$sum+=$item->getRowTotalInclTax();
							}
							}else{?>
								<td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
							<?php
				     	 }?>
			    </tbody>
			    <tfoot>
			    	<tr>
				     	 	<th colspan=3><strong>Total</strong></th>
				     	 	<th></th>
				     	 	<th></th>
				     	 	<th></th>
				     	 	<th></th>
				     	 	<th></th>
				     	 	<th></th>
				    </tr>
				</tfoot>
	    	</table>
    	</div>
    </div>
  </div>
  <div style="margin-bottom:20px;">
  		<a class="btn btn-lg btn-success" href="javascript:void(0);" onclick="screenshot();">Générer screenshot</a>
  </div>
</body>
<script>

//Self-invoking functions
$(function(){
  
	//Lorsque l'on sélectionne un increment id dans le menu déroulant, requete pour récupérer la commande correspondante et l'afficher
	$("#incrementid-dropdown").change(function(){
		window.location='index.php?module=remboursement&action=view&increment_id=' + this.value;
	    $("#warning-message").removeClass("hidden");
	});

	//Fonction calculant la différence entre le prix final et le prix initial des produits
	function price_difference(){

		var limite_prix=5;
		var diff_max_prix=0.5;
		var diff_max_percent=0.10;

		$('input.prixfinal').each(function(){
			totalprice=$(this).parent().parent().children("td")[5];
			totalprice=parseFloat($(totalprice).text());
			if($(this).val()!=""){
				valeur=parseFloat($(this).val());
				diff=parseFloat($(this).val())-totalprice;

				//Mise à jour de la colonne Diff Prix final pour la ligne correspondante
				$(this).parent().parent().children('.diffprixfinal').html(diff.toFixed(2));

				//Mise à jour de la colonne Diff Prix CGV pour la ligne correspondante
				if(totalprice>limite_prix){
					if(Math.abs(diff)>diff_max_prix){
						$(this).parent().parent().children('.diffprixcgv').html(diff.toFixed(2));
					}else{
						$(this).parent().parent().children('.diffprixcgv').html(0);
					}
				}else{
					if(Math.abs(diff/totalprice)>diff_max_percent){
						$(this).parent().parent().children('.diffprixcgv').html(diff.toFixed(2));
					}else{
						$(this).parent().parent().children('.diffprixcgv').html(0);
					}
				}
			}
		});
	}

	//Mise à jour des totaux des colonnes Prix Final / Diff Prix final et Diff Prix CGV (prise en compte uniquement des données affichées)
	function updatetotals(){
		
		var sumPrixFinal=0;
		var sumDiffPrixFinal=0;
		var sumDiffPrixCGV=0;
		var table = $('#data_commande').DataTable();

		//prixfinal
		var column = table.column('#prixfinal',{page:'current'});
		 $('input.prixfinal').each(function(){
			sumPrixFinal+=parseFloat($(this).val().replace("",0));
		});
		 $( column.footer() ).html(sumPrixFinal.toFixed(2));

		 //diffprixfinal
		 var column = table.column('#diffprixfinal',{page:'current'});
		 $('td.diffprixfinal').each(function(){
			sumDiffPrixFinal+=parseFloat($(this).text());
		});
		 $( column.footer() ).html(sumDiffPrixFinal.toFixed(2));

		 //diff prix CGV
		 var column = table.column('#diffprixCGV',{page:'current'});
		 $('td.diffprixcgv').each(function(){
			sumDiffPrixCGV+=parseFloat($(this).text());
		});
		 $( column.footer() ).html(sumDiffPrixCGV.toFixed(2));
	}

	/*-----------------------------------------------*/
	/*      UPDATE EN FOCNTION D'EVENEMENTS          */
	/*-----------------------------------------------*/

	//Mise à jour lorsque qu'input prix final modifié 
	$('input').each(function() {
	   var elem = $(this);
	   // Save current value of element
	   elem.data('oldVal', elem.val());
	   // Look for changes in the value
	   elem.bind("propertychange change click keyup input paste", function(event){
	      // If value has changed...
	      if (elem.data('oldVal') != elem.val()) {
	       // Updated stored value
	       elem.data('oldVal', elem.val());
	       price_difference();
	       updatetotals();
	     }
	   });
	 });

	//Mise à jour lorsque clic sur le tableau
	$('#data_commande').on('click', 'tr', function () {
		updatetotals();
	});

	//Mise à jour lorsque dessin du tableau
	$('#data_commande').on('draw.dt', function () {
		updatetotals();
	} );

	//Screenshot function

	
	
});

//Fonction se lance lorsque la page a chargé
$(document).ready(function() {
	//Setup de la table de données
    var table=$('#data_commande').DataTable({
    	"pageLength": -1,
    	"lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "Tous"] ],
    	initComplete: function () {
            this.api().columns(['.sort']).every(function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $('#filter') )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
 
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
 
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            });
        },

        "footerCallback": function ( row, data, start, end, display ) {
        	var sumPrixTotal=0;
            var api = this.api(), data;
 
            // Remove the formatting to get integer data for summation
            var intVal = function ( i ) {
                return typeof i === 'string' ?
                    i.replace(/[\$,]/g, '')*1 :
                    typeof i === 'number' ?
                        i : 0;
            };

 			this.api().columns(['.float']).every(function (){
 				var index = this.index();
	 
	            // Total over this page
	            pageTotal = api
	                .column( index, { page: 'current'} )
	                .data()
	                .reduce( function (a, b) {
	                    return intVal(a) + intVal(b);
	                }, 0 );

	            pageTotal=pageTotal.toFixed(2);

	            // Update footer
	            $( api.column( index ).footer() ).html(pageTotal);
	        });

	        $('input.prixfinal').each(function(){
 				sumPrixTotal+=parseFloat($(this).val().replace("",0));
				$( api.column('#prixfinal').footer() ).html(sumPrixTotal);
 			});
        }
    } );

});

</script>