<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$_rules = $this->getRules();
?>

<script language="javascript" type="text/javascript">
<!--
jQuery(document).ready(function() {
	jQuery("select").not('.orderable').select2();
	jQuery('.orderable').select2().select2Sortable();
});
function generate_code() {
	
	var $select = jQuery('#rule_ids');
	var $select2 = $select.siblings('.select2-container'),
		unselected = [],
		sorted;

	$select.find('option').each(function(){
		!this.selected && unselected.push(this);
	});

	sorted = $($select2.find('.select2-choices li[class!="select2-search-field"]').map( function() {
		if (!this) { return undefined; }
		var id = jQuery(this).data('select2Data').id;
		return $select.find('option[value="' + id + '"]')[0];
	}));

	sorted.push.apply(sorted, unselected);
	rule_ids = [];
	for(i=0; i<sorted.length; i++) {
		if(sorted[i]['selected']) {
			rule_ids.push(sorted[i]['value']);
		}
	}
	
	
	jQuery('#blockcode').hide();
	if(rule_ids.length>0) {
		code = '{{block type="awodev_aworewards/promotion" name="promoblock" template="awodev/aworewards/block/promotion'+jQuery('#view_type').val()+'.phtml" rule_ids="'+rule_ids.join(',')+'"}}';
		jQuery('#blockcode_display').html( code );
		jQuery('#blockcode').show();
	}
		
}

function hideblock() { jQuery('#blockcode').hide() }
</script>

	
<table class="admintable">

	<tr >
		<td class="key" nowrap><?php echo $this->__('View Type'); ?></td>
		<td>
			<select id="view_type" onchange="hideblock();"  style="width:300px;">
				<option value=""><?php echo $this->__('Narrow'); ?></option>
				<option value="_wide"><?php echo $this->__('Wide'); ?></option>
			</select>
		</td>
		<td></td>
	</tr>
	<tr >
		<td class="key" nowrap><?php echo $this->__('Rules'); ?></td>
		<td>
			<select id="rule_ids" class="orderable"  onchange="hideblock();" MULTIPLE style="width:300px;">
				<?php foreach($_rules as $row) { ?>
					<option value="<?php echo $row['id']; ?>"><?php echo '['.$row['website_name'].']'.$row['rule_name']; ?></option>
				<?php } ?>
			</select>
		</td>
		<td><button type="button" onclick="generate_code()"><?php echo $this->__('Generate'); ?></button></td>
	</tr>
	

</table>
<br /><br />
<div id="blockcode" style="display:none;">
	<div style="font-weight:bold;color:green;"><?php echo $this->__('Copy the below code into your cms Page or Static Block to display the promotion'); ?></div>
	<div id="blockcode_display" style="padding:10px;background-color:#dfdfdf;border:1px solid #aaaaaa;font-weight:bold;"></div>
</div>


	

