<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$_reflist = $this->getReferralList();
$_credlist = $this->getCreditList();
$_status = $this->getStatus();//printrx($_status);
$_license = $this->getLicense();
?>
<style>
	div.icon { text-align: center; margin-right: 15px; float: left; margin-bottom: 15px; }
	#cpanel span { display: block; text-align: center; }
	#cpanel img { padding: 10px 0; margin: 0 auto; }
	#cpanel div.icon a {background-color: white;background-position: -30px;display: block;float: left;height: 97px;width: 108px;color: #565656;vertical-align: middle;text-decoration: none;border: 1px solid #CCC;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;-webkit-transition-property: background-position, -webkit-border-bottom-left-radius, -webkit-box-shadow;-moz-transition-property: background-position, -moz-border-radius-bottomleft, -moz-box-shadow;-webkit-transition-duration: 0.8s;-moz-transition-duration: 0.8s;border-top-left-radius: 5px 5px;border-top-right-radius: 5px 5px;border-bottom-right-radius: 5px 5px;border-bottom-left-radius: 5px 5px;}
	.table { width:100%; background-color: #FFFFFF; border: 1px solid #CCCCCC; }
	.table tr th { background: -moz-linear-gradient(center top , #F9F9F9, #ECECEC) repeat-x scroll left top #ECECEC; color: #333333; font-size: 13px; padding: 4px 6px; text-align: left; text-shadow: 0 1px 0 #FFFFFF; }
	.table tr td { border-bottom: 1px solid #CCCCCC; color: #333333; font-size: 12px; padding: 4px 4px 4px 6px; }
</style>

<br /><br />
<div>



<table cellspacing="0" cellpadding="0" border="0" width="100%"><tbody>
<tr valign="top">
	<td  valign="top">
		<div id="cpanel">
			<div style="float:left;"><div class="icon"><a href="<?php echo Mage::helper("adminhtml")->getUrl("*/adminhtml_rule"); ?>"><img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-48-rule.png'); ?>" alt=""><span><?php echo $this->__('Rules'); ?></span></a></div></div>
			<div style="float:left;"><div class="icon"><a href="<?php echo Mage::helper("adminhtml")->getUrl("*/adminhtml_invitation"); ?>"><img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-48-invitation.png'); ?>" alt=""><span><?php echo $this->__('Invitation'); ?></span></a></div></div>
			<div style="float:left;"><div class="icon"><a href="<?php echo Mage::helper("adminhtml")->getUrl("*/adminhtml_referral"); ?>"><img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-48-referral.png'); ?>" alt=""><span><?php echo $this->__('Referrals'); ?></span></a></div></div>
			<div style="float:left;"><div class="icon"><a href="<?php echo Mage::helper("adminhtml")->getUrl("*/adminhtml_credit"); ?>"><img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-48-credit.png'); ?>" alt=""><span><?php echo $this->__('Credit History'); ?></span></a></div></div>
			<div style="float:left;"><div class="icon"><a href="<?php echo Mage::helper("adminhtml")->getUrl("*/adminhtml_payment"); ?>"><img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-48-payment.png'); ?>" alt=""><span><?php echo $this->__('Payment History'); ?></span></a></div></div>
			<div style="float:left;"><div class="icon"><a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/system_config/edit/section/awodev_aworewards"); ?>"><img src="<?php echo $this->getSkinUrl('images/awodev/aworewards/icon-48-config.png'); ?>" alt=""><span><?php echo $this->__('Configuration'); ?></span></a></div></div>
			<div style="clear:both;"></div>
		</div>
	</td>
	<td width="400" valign="top" style="padding-left:20px;">			
		<div id="genstat-pane" class="pane-sliders">

		
			<table class="table">
			<thead><tr><th><?php echo $this->__('Promotion'); ?></th></tr></thead>
			<tr><td><?php echo $this->__('Generate block code for CMS pages and static blocks.'); ?>
				<br />
				<script language="javascript" type="text/javascript">
				function block_generate() {
					jQuery(document).ready(function () {
						jQuery.fancybox({
							"width"				: "75%",
							"height"			: "75%",
							"autoScale"     	: false,
							"transitionIn"		: "none",
							"transitionOut"		: "none",
							"type": "iframe",
							//"href": "index.php?tab=AdminAwoRewards&module=aworewards&id="+id+"&view=creditdetail&token=0aa95ed31202b630bebafb633d86860a"
							"href":"<?php echo Mage::helper("adminhtml")->getUrl("*/*/blockcode"); ?>"
						});
					});	
				}
				</script>
				<button type="button" onclick="block_generate()"><?php echo $this->__('Get Started'); ?></button>
			</td></tr>
			</table>
			<br />
			
			<table class="table">
			<thead><tr><th colspan="2"><?php echo $this->__( 'License' ); ?></th></tr></thead>
			<tbody>
			<?php if(!empty($_license->l)) { ?>
				<tr><td width="33%"><?php echo $this->__( 'License' ); ?>:</td>
					<td><?php echo $_license->l; ?></td>
				</tr>
				<tr><td width="33%"><?php echo $this->__( 'Website' ); ?>:</td>
					<td><?php echo $_license->url; ?></td>
				</tr>
				<tr><td width="33%"><?php echo $this->__( 'Expiration' ).':'; ?></td>
					<td><b><?php echo empty($_license->exp) 
									? '<font color="green">'.$this->__( 'Permanent license' ).'</font>' 
									: '<font color="red">'.date('Y-m-d H:i:s',$_license->exp).'</font> <span style="font-size:17px;">&raquo;</span> <a href="http://awodev.com/documentation/frequently-asked-questions#license-permanent" target="_blank">'.$this->__( 'Make license permanent' ).'</a>';?></b>
					</td>
				</tr>
			<?php }  else { ?>
				<tr><td><b><span style="color:red;font-size:16px;"><?php echo $this->__( 'Invalid License' ); ?></span></b></td></tr>
			<?php } ?>
			</tbody>
			</table>
			<br />
				
			<table class="table">
			<thead><tr><th colspan="2"><?php echo $this->__('Check for Updates'); ?></th></tr></thead>
			<tbody>
			<?php if($_status->connect==0) : ?>
				<tr><td colspan="2"><b><font color="red"><?php echo $this->__('Connection Failed'); ?></font></b></td></tr>
			<?php elseif($_status->enabled==1) : ?>
				<tr><td colspan="2">
					<?php if($_status->current==0) : ?>
					<strong><font color="green"><?php echo $this->__('Latest Version Installed'); ?></font></strong>
					<?php elseif($_status->current==-1) : ?>
					<b><font color="red"><?php echo $this->__('Old Version currently installed'); ?></font></b> &nbsp; &nbsp;[ <a href="http://awodev.com/documentation/prestashop/aworewards/release-notes" target="_blank"><?php echo $this->__('release notes'); ?></a> ]
					<?php else : ?>
					<b><font color="orange"><?php echo $this->__('Newer Version'); ?></font></b>
					<?php endif; ?>
					</td>
				</tr>
				<?php if($_status->current!=0) : ?>
				<tr><td width="33%"><?php echo $this->__('Latest Version'); ?></td><td><?php echo $_status->version.' ('.$_status->released.')'; ?></td></tr>
				<?php endif; ?>
			<?php endif; ?>
			<tr><td width="33%"><?php echo $this->__('Installed Version'); ?>:</td><td><?php echo $_status->current_version; ?></td></tr>
			</tbody>
			</table>
		
		</div>
	</td>
</tr>
<tr><td colspan="2">		
		<?php if(!empty($_credlist)) { ?>
		<div>
			<h4><?php echo $this->__('Last Ten Credits'); ?></h4>
			<table class="table">
				<thead>
					<tr>
						<th class="title"><strong><?php echo $this->__('Date'); ?></strong></th>
						<th class="title"><strong><?php echo $this->__('Rule Type'); ?></strong></th>
						<th class="title"><strong><?php echo $this->__('Customer'); ?></strong></th>
						<th class="title"><strong><?php echo $this->__('Reward'); ?></strong></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($_credlist as $row) { ?>
					<tr>
						<td><?php echo $row['timestamp']; ?></td>
						<td><?php echo $row['str_rule_type']; ?></td>
						<td><?php echo $row['user_name']; ?></td>
						<td><?php echo $row['reward']; ?></td>
					</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
		<?php } ?>
		
		
		<?php if(!empty($_reflist)) { ?>
		<div>
			<h4><?php echo $this->__('Last Ten Referrals'); ?></h4>
			<table class="table">
				<thead>
					<tr>
						<th class="title"><?php echo $this->__('Date'); ?></th>
						<th class="title"><?php echo $this->__('Sponsor'); ?></th>
						<th class="title"><?php echo $this->__('Friend'); ?></th>
					</tr>
				</thead>

				<tbody>
					<?php foreach($_reflist as $row) { ?>
					<tr>
						<td><?php echo $row['send_date']; ?></td>
						<td><?php echo $row['affiliate_name']; ?></td>
						<td><?php echo $row['friend_name']; ?></td>
					</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
		<?php } ?>

		
</td></tr>

</tbody></table>
</div>


