<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$_invitation = Mage::registry('awodev_aworewards_invitation_form_data');
$_messages = Mage::registry('awodev_aworewards_invitation_form_messages');

$_isnew = true;
$_id = (int)$_invitation->getData('id');
if(!empty($_id)) $_isnew = false;

$_couponlist = Mage::helper('awodev_aworewards/coupon')->getCouponCodes();
$_websitelist = Mage::helper('awodev_aworewards')->getWebsites();
$_storelist = Mage::helper('awodev_aworewards')->getStores($_invitation->getData('website_id'));

$params = $_invitation->getData('params');//echo '<pre>'; print_r($params);exit;
if (!empty($params) && is_string($params)) $params = Mage::helper('core')->jsonDecode($params);
$locale = $_invitation->getData('locale');
if (!empty($locale) && is_array($locale)) $locale = (object)$locale;



?>

<script language="javascript" type="text/javascript">
<!--

jQuery(document).ready(function() {

	jQuery("form[name=edit_form] select").not('.orderable').select2();

	change_invitationtype();

});

function change_invitationtype() {
	var form = document.edit_form;
	
	
	jQuery('#tr_description,#tr_email_subject,#tr_coupon_template,#tr_coupon_expiration,#tr_email_b0dy').hide();

	
	if(form.elements["invitation[invitation_type]"].selectedIndex == 0) {
		form.elements["invitation[coupon_template]"].selectedIndex = 0;

		form.elements["invitation[locale][email_subject][0]"].value = ''; 
		form.elements["invitation[locale][email_body][0]"].value = ''; 
		form.elements["invitation[locale][description][0]"].value = ''; 
	}
	
	if(form.elements["invitation[invitation_type]"].value=='email') jQuery('#tr_description,#tr_email_subject,#tr_coupon_template,#tr_coupon_expiration,#tr_email_b0dy').show();
	else if(form.elements["invitation[invitation_type]"].value=='facebook') jQuery('#tr_description,#tr_coupon_template,#tr_coupon_expiration,#tr_email_b0dy').show();
	else if(form.elements["invitation[invitation_type]"].value=='twitter') jQuery('#tr_description,#tr_coupon_template,#tr_coupon_expiration,#tr_email_b0dy').show();
	
	
}


function changestore(val) {

	jQuery.each(jQuery('[name^="invitation[locale]"]'),function (i,l) {
		jQuery(this).hide();
		id = jQuery(this).attr('id');
		if(id!=undefined) {
			if(jQuery('#'+id+'_parent.mceEditor').length!=0) {
				jQuery('#'+id+'_parent.mceEditor').hide();
			}
		}
		
		name = jQuery(this).attr('name');
		test = name.substr(name.lastIndexOf("["));
		
		if(test=='['+val+']') {
			//mceEditor defaultSkin
			is_found = false;
			if(id!=undefined) {
				if(jQuery('#'+id+'_parent.mceEditor').length!=0) {
					is_found = true;
					jQuery('#'+id+'_parent.mceEditor').show();
				}
			}
			if(!is_found) jQuery(this).show();
		}
		
	});
}

//-->
</script>
<script type="text/javascript">
window.onload=function() {
   tinyMCE.init({
    mode : "exact",
    elements: "invitation_locale_email_body_<?php echo implode(',invitation_locale_email_body_',array_keys($_storelist));?>",
    theme : "advanced",
    plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
    theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_path_location : "bottom",
    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
    theme_advanced_resize_horizontal : 'true',
    theme_advanced_resizing : 'true',
    apply_source_formatting : 'true',
    convert_urls : 'false',
    force_br_newlines : 'true',
    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

  });
};
</script>

<style>
.inputbox{ width: 250px !important;}
table.admintable td.label { width: 200px;}
fieldset.adminform { margin: 10px; overflow: hidden; border: 1px #ccc solid; text-align: left; }
fieldset.adminform legend { margin: 0; padding: 0; color: #146295; font-size: 1.182em; font-weight: bold; width:auto; border:0; line-height:1.182em; }
div.clr {clear:both;}
</style>		
		



		
<div ><?php //echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div id="messages"><?php echo $_messages; ?></div>	
		
     


<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3><?=$this->__('Invitation')?></h3></td>
			<td class="a-right">
				<button style="" onclick="setLocation('<?php echo $this->getUrl('*/*/index'); ?>')" class="scalable back" type="button" title="<?php echo $this->__( 'Back' ); ?>" ><span><?php echo $this->__( 'Back' ); ?></span></button>
				<button style="" onclick="confirmSetLocation('Are you sure?', '<?php echo $this->getUrl('*/*/delete/id/'.$_id ); ?>')" class="scalable delete" type="button" title="<?php echo $this->__( 'Delete' ); ?>"><span><?php echo $this->__( 'Delete' ); ?></span></button>
				<button onclick="editForm.submit()" class="scalable save" type="button"><span><?php echo $this->__( 'Save Invitation' ); ?></span></button>
				<!--<button onclick="editForm.submit($('edit_form').action + 'back/edit/')" class="scalable save" type="button"><span>Save and Continue Edit</span></button>-->
			</td>
		</tr>
	</table>
</div>
<div class="entry-edit">


<form id="edit_form" name="edit_form" method="post" action="<?=$this->getUrl('*/*/save')?>">
		
	<fieldset class="adminform">
	<legend></legend>
	
	<table class="admintable">
		<tr valign="top" id="">
			<td class="label" nowrap><?php echo $this->__( 'Website' ); ?> <span class="required">*</span></td>
			<td>
				<?php if ($_isnew): ?>
					<select id="" name="invitation[website_id]" class="inputbox required-entry">
						<?php $select = $_invitation->getData('website_id'); ?>
						<?php foreach ($_websitelist as $k=>$v): ?>
							<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
					</select>
				<?php else : ?>
					<input type="hidden" name="invitation[website_id]" value="<?php echo $_invitation->getData('website_id'); ?>" />
					<?php echo isset($_websitelist[$_invitation->getData('website_id')]) ? $_websitelist[$_invitation->getData('website_id')] : ''; ?>
					<select id="" name="_storelist" class="inputbox" onchange="changestore(this.value);">
						<?php foreach ($_storelist as $k=>$v): ?>
							<option value="<?php echo $k ?>"><?php echo $v ?></option>
						<?php endforeach ?>
					</select>
				<?php endif ?>
			</td>
			<td class="value scope-label"></td>
		</tr>
		<tr><td class="label" nowrap><?php echo $this->__( 'Title' ); ?> <span class="required">*</span></td>
			<td><input class="inputbox required-entry" type="text" name="invitation[invitation_name]" size="30" maxlength="255" value="<?php echo $_invitation->getData('invitation_name'); ?>" /></td>
			<td class="value scope-label" nowrap></td>
		</tr>
		<tr>
			<td class="label" nowrap><?php echo $this->__( 'Ordering' ); ?></label></td>
			<td><input class="inputbox validate-digits" type="text" name="invitation[ordering]" size="30" maxlength="255" value="<?php echo $_invitation->ordering; ?>" />
				<p class="helper_text"><?php echo $this->__( 'The order to display in the front end dropdown'); ?></p>
			</td>
			<td class="value scope-label" nowrap></td>
		</tr>
		<tr><td class="label" nowrap><?php echo $this->__( 'Published' ); ?> <span class="required">*</span></td>
			<td><select id="" name="invitation[published]" class="inputbox required-entry">
				<?php $select = $_invitation->getData('published'); ?>
				<?php foreach (Mage::helper('awodev_aworewards')->vars('published') as $k => $v): ?>
					<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</td>
			<td class="value scope-label" nowrap></td>
		</tr>
		<tr><td class="label" nowrap><?php echo $this->__( 'Form Type' ); ?> <span class="required">*</span></td>
			<td><select id="" name="invitation[invitation_type]" class="inputbox required-entry" onchange="change_invitationtype();">
					<option value=""></option>
					<?php $select = $_invitation->getData('invitation_type'); ?>
					<?php foreach (Mage::helper('awodev_aworewards')->vars('invitation_type') as $k => $v): ?>
						<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
				</select>
			</td>
			<td class="value scope-label" nowrap></td>
		</tr>
	
		<tr id="tr_description">
			<td class="label"><?php echo $this->__( 'Dropdown Description' ); ?> <span class="required">*</span></td>
			<td><?php foreach($_storelist as $k=>$v) : ?>
					<input style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox <?php if($k==0) echo 'required-entry';?>" type="text" size="60" name="invitation[locale][description][<?php echo $k; ?>]" value="<?php echo !empty($locale->description[$k]) ? $locale->description[$k] : ''; ?>" maxlength="255">
				<?php endforeach; ?>
			</td>
			<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
		</tr>
		<tr id="tr_email_subject">
			<td class="label"><?php echo $this->__( 'Email Subject' ); ?></td>
			<td><?php foreach($_storelist as $k=>$v) : ?>
					<input style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox <?php if($k==0) echo 'validate-aworewards-emailsubject';?>" type="text" size="60" name="invitation[locale][email_subject][<?php echo $k; ?>]" value="<?php echo !empty($locale->email_subject[$k]) ? $locale->email_subject[$k] : ''; ?>" maxlength="255">
				<?php endforeach; ?>
			</td>
			<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
		</tr>
		<tr id="tr_coupon_template">
			<td class="label" nowrap><label><?php echo $this->__( 'Coupon to Copy' ); ?> - {coupon_code}</label></td>
			<td><select id="" name="invitation[coupon_template]" class="inputbox">
				<option value=""></option>
				<?php $select = $_invitation->getData('coupon_template'); ?>
				<?php foreach ($_couponlist as $v): ?>
					<option value="<?php echo $v->coupon_id ?>" <?php if($v->coupon_id==$select): ?>selected="selected"<?php endif ?>><?php echo $v->code ?></option>
				<?php endforeach ?>
				</select>
			</td>
			<td class="value scope-label"></td>
		</tr>
		<tr id="tr_coupon_expiration">
			<td class="label" nowrap valign="top"><label><?php echo $this->__( 'Expiration' ).' ('.$this->__('Days').')'; ?></label></td>
			<td><input class="inputbox" type="text" name="invitation[coupon_expiration]" size="30" maxlength="255" value="<?php echo !empty($this->row->coupon_expiration) ? $this->row->coupon_expiration : ''; ?>" /></td>
			<td class="value scope-label"></td>
		</tr>
		<tr id="tr_email_b0dy" valign="top">
		
			<td class="key">
				
				<label><?php echo $this->__( 'Message' ); ?> <span class="required">*</span></label>
				<br style="clear:both;"/><br /><div align="right"><table style="text-align:left;font-weight:normal;">
					<tr><th><?php echo $this->__( 'Tags' ); ?></th></tr>
					<tr><td>{user_name}</td></tr>
					<tr><td>{customer_link}</td></tr>
					<tr><td>{customer_note}</td></tr>
					<tr><td>{coupon_code}</td></tr>
				</table></div>
			</td>
			<td><?php foreach($_storelist as $k=>$v) : ?>
					<textarea id="invitation_locale_email_body_<?php echo $k; ?>" name="invitation[locale][email_body][<?php echo $k; ?>]" style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox <?php if($k==0) echo ''; ?>" cols="30" rows="10"  ><?php echo !empty($locale->email_body[$k]) ? $locale->email_body[$k] : ''; ?></textarea>
				<?php endforeach; ?>
 			</td>
			<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
		</tr>
		
		
	
	</table>

	</fieldset>

	
	


	<div class="clr"></div>


<input name="invitation[id]" type="hidden" value="<?php echo $_id ?>" />
<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
</form>


</div>



<script type="text/javascript">
var editForm = new varienForm('edit_form');

Validation.addAllThese([
	['validate-aworewards-emailsubject', '<?php echo Mage::helper('awodev_aworewards')->__('This field is required.') ?>', function(v,elm) {
		var tmp = ['email'];
		if(tmp.indexOf(elm.form.elements["invitation[invitation_type]"].value)==-1) return true;
		return !Validation.get('IsEmpty').test(v);
	}]
]);

</script>
