<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$this->initTotals();
$_credits = $this->getCredits();
?>

<style>
table.adminlist { width: 100%; border-spacing: 1px; background-color: #ffffff; color: #666; }
table.adminlist th { background-color: #EBEDF4; text-align:left;}
table.adminlist th,table.adminlist td { padding-right:7px; }
</style>

<h2><?php echo $this->__('Payment Details'); ?></h2>
<table class="" style="width:auto;">
	<tr><td><b><?php echo $this->__('ID'); ?>: </b></td><td><?php echo $this->getPayment()->id; ?></td></tr>
	<tr><td><b><?php echo $this->__('Customer'); ?>: </b></td><td><?php echo $this->getCustomer()->firstname.' '.$this->getCustomer()->lastname; ?></td></tr>
	<tr><td><b><?php echo $this->__('Entry Date'); ?>: </b></td><td><?php echo $this->getPayment()->payment_date; ?></td></tr>
	<tr><td><b><?php echo $this->__('Paid'); ?>: </b></td><td><?php echo number_format($this->getPayment()->amount_paid,2); ?></td></tr>
	<tr valign="top">
		<td><b><?php echo $this->__('Details'); ?>: </b></td>
		<td><?php
				$payment_details = '';
				if($this->getPayment()->payment_type=='mage_coupon') $payment_details = $this->__('Coupon Code').': '.$this->getPayment()->payment_details;
				elseif($this->getPayment()->payment_type=='paypal') {
					$a = explode('|',$this->getPayment()->payment_details);
					$payment_details .= '<div>'.$this->__('Receiver Transaction ID').': '.@$a[1].'</div>';
					$payment_details .= '<div>'.$this->__('Sender Transaction ID').': '.@$a[2].'</div>';
				}
				echo $payment_details;
			?>
		</td>
	</tr>
</table>

<h2><?php echo $this->__('Credits'); ?></h2>
<table class="adminlist" cellspacing="1">
<thead>
	<tr>
		<th width="1%" nowrap="nowrap"><?php echo $this->__('ID'); ?></th>
		<th class=""><?php echo $this->__('Rule Name'); ?></th>
		<th class=""><?php echo $this->__('Rule Type'); ?></th>
		<th class=""><?php echo $this->__('Order'); ?></th>
		<th class=""><?php echo $this->__('Points'); ?></th>
		<th class=""><?php echo $this->__('Entry Date'); ?></th>
	</tr>
</thead>

<tbody>
	<?php foreach($_credits as $_credit) { ?>
		<tr>
			<td align=""><?php echo $_credit->id; ?></td>
			<td align=""><?php echo $_credit->rule_name; ?></td>
			<td align=""><?php echo !empty($_credit->rule_type) ? Mage::helper('awodev_aworewards')->vars('rule_type',$_credit->rule_type) : ''; ?></td>
			<td align=""><?php if($_credit->rule_type=='order') echo $_credit->increment_id; ?></td>
			<td align=""><?php echo number_format($_credit->points,2); ?></td>
			<td align=""><?php echo $_credit->timestamp; ?></td>
		</tr>
	<?php } ?>
</tbody>

</table>
<br />
<br />


