<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

//$_rule = Mage::getModel('awodev_aworewards/rule')->load($this->getRequest()->getParam('id'));

//$_rule = Mage::getModel('awodev_aworewards/locale')->load(1);
//echo '<pre>'; print_r($_rule);
//exit;
//$_rule = Mage::getModel('awodev_aworewards/locale')->setEntity(1,2);

$_rule = Mage::registry('awodev_aworewards_rule_form_data');
$_messages = Mage::registry('awodev_aworewards_rule_form_messages');

$_isnew = true;
$_id = (int)$_rule->getData('id');
if(!empty($_id)) $_isnew = false;

$_couponlist = Mage::helper('awodev_aworewards/coupon')->getCouponCodes();
$_websitelist = Mage::helper('awodev_aworewards')->getWebsites();
$_storelist = Mage::helper('awodev_aworewards')->getStores($_rule->getData('website_id'));

//echo '<pre>'; print_r($_storelist);echo '</pre>';
//echo '<pre>'; print_r($_rule);echo '</pre>';
	  // = Mage::getModel('awodev_aworewards/rule')->getResource()->load();
//$_data = $_rule->getAllItems();
   // $customerData = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getCustomer()->getId())->getData();

$params = $_rule->getData('params');//echo '<pre>'; print_r($params);exit;
if (!empty($params) && is_string($params)) $params = (object) Mage::helper('core')->jsonDecode($params);
$locale = $_rule->getData('locale');
if (!empty($locale) && is_array($locale)) $locale = (object)$locale;


?>

<script language="javascript" type="text/javascript">
<!--

jQuery(document).ready(function() {

	jQuery("form[name=edit_form] select").not('.orderable').select2();

	var form = document.edit_form;
	change_pay();
	change_ruletype();
	
	blur_help_text(form.elements["rule[startdate]"],'YYYY-MM-DD hh:mm:ss');
	blur_help_text(form.elements["rule[expiration]"],'YYYY-MM-DD hh:mm:ss');

});

function change_customer_type() {
	check_registration_extras();
}


function change_pay() {
	var form = document.edit_form;

	if(form.elements["rule[credit_type]"].selectedIndex == 0) {
		form.elements["rule[points]"].value = '';
		form.elements["rule[params][coupon_expiration]"].value = '';
		//form.template_id.selectedIndex = 0;
		//form.profile_id.selectedIndex = 0;
	}
	jQuery('#tr_pay_exp,#tr_pay_points,#tr_pay_coup,#tr_pay_system_email_subject,#tr_pay_ps_email_body').hide();
	
	if(form.elements["rule[credit_type]"].selectedIndex != 0) {
		if(form.elements["rule[credit_type]"].value == 'mage_coupon') jQuery('#tr_pay_exp,#tr_pay_coup,#tr_pay_system_email_subject,#tr_pay_ps_email_body').show();
		else if(form.elements["rule[credit_type]"].value == 'points') jQuery('#tr_pay_points').show();
	}
	
	check_pointsfield();
	check_registration_extras();
}

function change_ruletype() {
	var form = document.edit_form;
	
	if(form.elements["rule[rule_type]"].selectedIndex == 0) {
		form.elements["rule[params][order_trigger]"].value = '';
		form.elements["rule[params][order_min_type]"].value = '';
		form.elements["rule[params][order_min]"].value = '';
		form.elements["rule[params][reg_delay]"].value = '';
		form.elements["rule[params][reg_nosend]"].checked = false;
	}
	jQuery('#customer_type').removeAttr('disabled');
	jQuery('#tr_order_trigger,#tr_order_mintype,#tr_order_min,#tr_order_percent,#tr_reg_nosend,#tr_review_onlyfirst,#tr_predefined_text,#tr_username,#tr_promo_head,#tr_promo_desc').hide();
	
	if(form.elements["rule[rule_type]"].value=='order') jQuery('#tr_order_trigger,#tr_order_mintype,#tr_order_min,#tr_order_percent').show();
	//else if(form.elements["rule[rule_type]"].value=='registration') jQuery('#tr_reg_nosend').show();
	else if(form.elements["rule[rule_type]"].value=='review') jQuery('#tr_review_onlyfirst').show();
	else if(form.elements["rule[rule_type]"].value=='facebook_wall') {
		jQuery('#customer_type').val('everyone').attr('disabled','disabled');
		jQuery('#customer_type').select2().select2('val','everyone');
		jQuery('#tr_predefined_text,#tr_promo_head,#tr_promo_desc').show();
	}
	else if(form.elements["rule[rule_type]"].value=='twitter_tweet') {
		jQuery('#customer_type').val('everyone').attr('disabled','disabled');
		jQuery('#customer_type').select2().select2('val','everyone');
		jQuery('#tr_predefined_text,#tr_promo_head,#tr_promo_desc').show();
	}
	else if(form.elements["rule[rule_type]"].value=='twitter_follow') {
		jQuery('#customer_type').val('everyone').attr('disabled','disabled');
		jQuery('#customer_type').select2().select2('val','everyone');
		jQuery('#tr_username,#tr_promo_head,#tr_promo_desc').show();
	}
	else if(form.elements["rule[rule_type]"].value=='facebook_like') {
		jQuery('#customer_type').val('everyone').attr('disabled','disabled');
		jQuery('#customer_type').select2().select2('val','everyone');
		jQuery('#tr_username,#tr_promo_head,#tr_promo_desc').show();
	}
	
	check_registration_extras();
	
	
}

function check_pointsfield() {
	var form = document.edit_form;
	
	if(form.elements["rule[credit_type]"].value=='points') {
		if(trim(form.elements["rule[params][order_percent]"].value)!='' && form.elements["rule[params][order_percent]"].value>0) {
			form.elements["rule[points]"].value=''; 
			jQuery('#tr_pay_points').hide();
		} else jQuery('#tr_pay_points').show();
	}
	
}

function check_registration_extras() {
	var form = document.edit_form;
	if(form.elements["rule[customer_type]"].value=='everyone'
	&& form.elements["rule[rule_type]"].value=='registration'
	&& form.elements["rule[credit_type]"].value=='mage_coupon') jQuery('#tr_reg_delay,#tr_reg_nosend').show();
	else jQuery('#tr_reg_delay,#tr_reg_nosend').hide();
	
}

function focus_help_text(item,txt) {
	if(item.value == txt) {
		item.style.color="#000000";
		item.value = '';
	}
}
function blur_help_text(item,txt) {
	if(item.value=='' || item.value == txt) {
		item.style.color="#aaaaaa";
		item.value=txt;
	} else item.style.color="#000000";
}
function trim(str) { return jQuery.trim(str); }
function isUnsignedInteger(s) { return (s.toString().search(/^[0-9]+$/) == 0); }

function changestore(val) {

	jQuery.each(jQuery('[name^="rule[locale]"]'),function (i,l) {
		jQuery(this).hide();
		id = jQuery(this).attr('id');
		if(id!=undefined) {
			if(jQuery('#'+id+'_parent.mceEditor').length!=0) {
				jQuery('#'+id+'_parent.mceEditor').hide();
			}
		}
		
		name = jQuery(this).attr('name');
		test = name.substr(name.lastIndexOf("["));
		
		if(test=='['+val+']') {
			//mceEditor defaultSkin
			is_found = false;
			if(id!=undefined) {
				if(jQuery('#'+id+'_parent.mceEditor').length!=0) {
					is_found = true;
					jQuery('#'+id+'_parent.mceEditor').show();
				}
			}
			if(!is_found) jQuery(this).show();
		}
		
	});
}

//-->
</script>
<script type="text/javascript">
window.onload=function() {
   tinyMCE.init({
    mode : "exact",
    elements: "rule_locale_email_body_<?php echo implode(',rule_locale_email_body_',array_keys($_storelist));?>",
    theme : "advanced",
    plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
    theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_path_location : "bottom",
    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
    theme_advanced_resize_horizontal : 'true',
    theme_advanced_resizing : 'true',
    apply_source_formatting : 'true',
    convert_urls : 'false',
    force_br_newlines : 'true',
    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

  });
};
</script>

<style>
.inputbox{ width: 250px !important;}
table.admintable td.label { width: 200px;}
div.width-50 { width: 50%; }
div.width-50 fieldset { background-color: white; padding: 5px 17px 17px 17px; }
fieldset.adminform { margin: 10px; overflow: hidden; border: 1px #ccc solid; text-align: left; }
fieldset.adminform legend { margin: 0; padding: 0; color: #146295; font-size: 1.182em; font-weight: bold; width:auto; border:0; line-height:1.182em; }
div.m input, div.m select, div.m textarea{width:auto;}
div.clr {clear:both;}
</style>		
		



		
<div ><?php //echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div id="messages"><?php echo $_messages; ?></div>	
		
     


<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3><?=$this->__('Rule')?></h3></td>
			<td class="a-right">
				<button style="" onclick="setLocation('<?php echo $this->getUrl('*/*/index'); ?>')" class="scalable back" type="button" title="<?php echo $this->__( 'Back' ); ?>" ><span><?php echo $this->__( 'Back' ); ?></span></button>
				<button style="" onclick="confirmSetLocation('Are you sure?', '<?php echo $this->getUrl('*/*/delete/id/'.$_id ); ?>')" class="scalable delete" type="button" title="<?php echo $this->__( 'Delete' ); ?>"><span><?php echo $this->__( 'Delete' ); ?></span></button>
				<button onclick="editForm.submit()" class="scalable save" type="button"><span><?php echo $this->__( 'Save Rule' ); ?></span></button>
				<!--<button onclick="editForm.submit($('edit_form').action + 'back/edit/')" class="scalable save" type="button"><span>Save and Continue Edit</span></button>-->
			</td>
		</tr>
	</table>
</div>
<div class="entry-edit">

<form id="edit_form" name="edit_form" method="post" action="<?=$this->getUrl('*/*/save')?>">
		
	<div class="width-50" style="min-width:400px;float:left;">

		<fieldset class="adminform">
		<legend></legend>
		
		<table class="admintable">
			<tr valign="top" id="">
				<td class="label" nowrap><?php echo $this->__( 'Website' ); ?> <span class="required">*</span></td>
				<td>
					<?php if ($_isnew): ?>
						<select id="" name="rule[website_id]" class="inputbox required-entry">
							<?php $select = $_rule->getData('website_id'); ?>
							<?php foreach ($_websitelist as $k=>$v): ?>
								<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
							<?php endforeach ?>
						</select>
					<?php else : ?>
						<input type="hidden" name="rule[website_id]" value="<?php echo $_rule->getData('website_id'); ?>" />
						<?php echo isset($_websitelist[$_rule->getData('website_id')]) ? $_websitelist[$_rule->getData('website_id')] : ''; ?>
						<select id="" name="_storelist" class="inputbox" onchange="changestore(this.value);">
							<?php foreach ($_storelist as $k=>$v): ?>
								<option value="<?php echo $k ?>"><?php echo $v ?></option>
							<?php endforeach ?>
						</select>
					<?php endif ?>
				</td>
				<td class="value scope-label"></td>
			</tr>
		
		
			<tr><td class="label" nowrap><?php echo $this->__( 'Rule Name' ); ?> <span class="required">*</span></td>
				<td><input class="inputbox required-entry" type="text" name="rule[rule_name]" size="30" maxlength="255" value="<?php echo $_rule->getData('rule_name'); ?>" /></td>
			</tr>
		
			<tr><td class="label" nowrap><?php echo $this->__( 'Published' ); ?> <span class="required">*</span></td>
				<td><select id="" name="rule[published]" class="inputbox required-entry">
					<?php $select = $_rule->getData('published'); ?>
					<?php foreach (Mage::helper('awodev_aworewards')->vars('published') as $k => $v): ?>
						<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
					</select>
				</td>
			</tr>
			<tr><td class="label" nowrap><?php echo $this->__( 'Customer Type' ); ?> <span class="required">*</span></td>
				<td><select id="customer_type" name="rule[customer_type]" class="inputbox required-entry" onchange="change_customer_type()">
					<?php $select = $_rule->getData('customer_type'); ?>
					<?php foreach (Mage::helper('awodev_aworewards')->vars('customer_type') as $k => $v): ?>
						<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
					</select>
				</td>
			</tr>
			<tr><td class="label" nowrap valign="top"><label><?php echo $this->__( 'Start Date' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-date" type="text" name="rule[startdate]" size="1" style="width:49px;" maxlength="19" value="<?php echo $_rule->getData('startdate'); ?>"
						onfocus="focus_help_text(this,'YYYY-MM-DD hh:mm:ss')" onblur="blur_help_text(this,'YYYY-MM-DD hh:mm:ss')"  />
					<p class="helper_text"><?php echo $this->__( 'Setting a rule start date and time means 2 things. 1) The rule is valid from the start date onwards. 2) Only registrations/orders made from the start date onwards will be accounted for by the rule.' ); ?></p>
				</td>
			</tr>
			<tr><td class="label" nowrap valign="top"><label><?php echo $this->__( 'Rule Expiration' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-date" type="text" name="rule[expiration]" size="1" maxlength="19" value="<?php echo $_rule->getData('expiration'); ?>" style="width:49px;"
						onfocus="focus_help_text(this,'YYYY-MM-DD hh:mm:ss')" onblur="blur_help_text(this,'YYYY-MM-DD hh:mm:ss')"  />
					<p class="helper_text"><?php echo $this->__( 'Setting a rule expiration date and time means 2 things. 1) The rule expires at the expiration time. 2) Only registrations/orders made up until expiration will be accounted for by the rule.' ); ?></p>
				</td>
			</tr>
			<tr valign="top"><td class="label" nowrap><label><?php echo $this->__( 'Notes' ); ?></label></td>
				<td><textarea class="inputbox" cols="18" rows="3" name="rule[note]" style="width:147px;"><?php echo $_rule->getData('note'); ?></textarea>
			</tr>
		
		
		</table>
		
		</table>
		</fieldset>

	</div>

	<div class="width-50" style="min-width:400px;float:left">

		<fieldset  class="adminform">
		<legend></legend>


		<table class="admintable">
			<tr valign="top">
				<td class="label" nowrap><?php echo $this->__( 'Rule Type' ); ?> <span class="required">*</span></td>
				<td><select id="" name="rule[rule_type]" class="inputbox required-entry" onchange="change_ruletype()">
					<?php $select = $_rule->getData('rule_type'); ?>
					<option value=""></option>
					<?php foreach (Mage::helper('awodev_aworewards')->vars('rule_type') as $k => $v): ?>
						<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
					</select>
				</td>
				<td class="value scope-label"></td>
			</tr>
			<tr>
				<td class="label" nowrap><?php echo $this->__( 'Ordering' ); ?></label></td>
				<td><input class="inputbox validate-digits" type="text" name="rule[ordering]" size="30" maxlength="255" value="<?php echo $_rule->ordering; ?>" />
					<p class="helper_text"><?php echo $this->__( 'The order of a rule is important.  Only one rule within a specified rule type will be processed.  So the first rule found that the customer qualifies for will be used.'); ?></p>
				</td>
			</tr>
					
			<tr valign="top" id="tr_order_mintype" style="display:none;"><td class="label" nowrap><label><?php echo $this->__( 'Minimum Order Total Type' ); ?><span class="star">&#160;*</span></label></td>
				<td><select id="" name="rule[params][order_min_type]" class="inputbox validate-aworewards-ordermintype">
					<?php $select = !empty($params->order_min_type) ? $params->order_min_type : ''; ?>
					<option value=""></option>
					<?php foreach (Mage::helper('awodev_aworewards')->vars('order_min_type') as $k => $v): ?>
						<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
					</select>
					<p class="helper_text"><?php echo $this->__( 'This field lets you set if the minimum value must be reached for every order or across multiple orders. For example, if you set the minimum value to 100 and the minimum order type to Per Order, then only if a customer spends 100 in a single order will the rule be triggered. If the minimum order type is set to "All Orders" then the order totals accumulate and when a customer spends minimum of 100 across all their orders the rule will be triggered and reward earned.' ); ?></p>
				</td>
				<td class="value scope-label"></td>
			</tr>
			<tr valign="top" id="tr_order_min" style="display:none;"><td class="label" nowrap><label><?php echo $this->__( 'Minimum Order Total' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-ordermin" type="text" name="rule[params][order_min]" size="30" maxlength="255" value="<?php echo !empty($params->order_min) ? $params->order_min : ''; ?>" />
					<p class="helper_text"><?php echo $this->__( 'The minimum value the order total(s) must reach for the reward (coupon/amount) to be generated. Please note this field works with minimum order total type field.' ); ?></p>
				</td>
				<td class="value scope-label"></td>
			</tr>
			<tr valign="top" id="tr_order_trigger" style="display:none;">
				<td class="label" nowrap><label><?php echo $this->__( 'Order Number to trigger rule' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-ordertrigger" type="text" name="rule[params][order_trigger]" size="30" maxlength="255" value="<?php echo !empty($params->order_trigger) ? $params->order_trigger : ''; ?>" />
					<p class="helper_text"><?php echo $this->__( 'This field lets you set which orders the rule will apply to. For example if the rule should apply to every 10th order up to first 100 orders, then set it to 10,20,30,40,50,60,70,80,90,100. Please note this is orders per customer and works only with order total type of "Per Order".' ); ?></p>
				</td>
				<td class="value scope-label"></td>
			</tr>
			<tr valign="top" id="tr_order_percent" style="display:none;">
				<td class="label" nowrap><label><?php echo $this->__( 'Percent of Order Total' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-orderpercent" type="text" name="rule[params][order_percent]" size="30" maxlength="255" value="<?php echo !empty($params->order_percent) ? $params->order_percent : ''; ?>" onchange="check_pointsfield();"/>
					<p class="helper_text"><?php echo $this->__( 'The percentage of the order total end payment which will be given to a beneficiary. For example entering 2.5 and setting the customer type to sponsor will mean the sponsor will be credited with 2.5% of the order total completed by his/her friend. If the customer type is set to friend, then the customer receives a 2.5% cashback on their order.' ); ?></p>
				</td>
				<td class="value scope-label"></td>
			</tr>
			
			
			<tr valign="top" id="tr_reg_delay" style="display:none;"><td class="label" nowrap><label><?php echo $this->__( 'Delay in Days' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-regdelay" type="text" name="rule[params][reg_delay]" size="30" maxlength="255" value="<?php echo !empty($params->reg_delay) ? $params->reg_delay : ''; ?>" /></td>
				<td class="value scope-label"></td>
			</tr>
			<tr id="tr_reg_nosend" style="display:none;"><td class="label" nowrap><label></label></td>
				<td><input class="inputbox" type="checkbox" name="rule[params][reg_nosend]" value="1" <?php if(!empty($params->reg_nosend)) echo 'CHECKED';; ?> /> <?php echo $this->__( 'Do not send Coupon if customer ordered' ); ?></td>
				<td class="value scope-label"></td>
			</tr>
			
			<tr id="tr_review_onlyfirst" style="display:none;"><td class="label" nowrap><label></label></td>
				<td><input class="inputbox" type="checkbox" name="rule[params][review_onlyfirst]" value="1" <?php if(!empty($params->review_onlyfirst)) echo 'CHECKED';; ?> /> <?php echo $this->__( 'First review only' ); ?></td>
				<td class="value scope-label"></td>
			</tr>
			
			
			<tr id="tr_predefined_text" valign="top"><td class="label" nowrap><label><?php echo $this->__( 'Predefined Text' ); ?></label></td>
				<td><?php foreach($_storelist as $k=>$v) : ?>
						<textarea style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox <?php if($k==0) echo 'validate-aworewards-predefined'; ?>" cols="18" rows="7" name="rule[locale][predefined_text][<?php echo $k; ?>]" style="width:400px;"><?php echo !empty($locale->predefined_text[$k]) ? htmlspecialchars_decode($locale->predefined_text[$k]) : ''; ?></textarea>
					<?php endforeach; ?>
				</td>
				<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
			</tr>
			
			
			
			<tr id="tr_username" valign="top"><td class="label" nowrap><label><?php echo $this->__( 'Username' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-follow" type="text" name="rule[params][username]" value="<?php echo !empty($params->username) ? $params->username : ''; ?>"  /> </td>
				<td class="value scope-label"></td>
			</tr>
			
			<tr id="tr_promo_head" valign="top"><td class="label" nowrap><label><?php echo $this->__( 'Marketing Headline' ); ?></label></td>
				<td><?php foreach($_storelist as $k=>$v) : ?>
						<input style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox <?php if($k==0) echo 'validate-aworewards-promohead';?>" type="text" name="rule[locale][promo_headline][<?php echo $k; ?>]" value="<?php echo !empty($locale->promo_headline[$k]) ? htmlspecialchars_decode($locale->promo_headline[$k]) : ''; ?>"  />
					<?php endforeach; ?>
				</td>
				<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
			</tr>
			
			<tr id="tr_promo_desc" valign="top"><td class="label" nowrap><label><?php echo $this->__( 'Marketing Description' ); ?></label></td>
				<td><?php foreach($_storelist as $k=>$v) : ?>
						<input style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox" type="text" name="rule[locale][promo_description][<?php echo $k; ?>]" value="<?php echo !empty($locale->promo_description[$k]) ? htmlspecialchars_decode($locale->promo_description[$k]) : ''; ?>"  />
					<?php endforeach; ?>
				</td>
				<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
			</tr>
			
			
		</table>

		</fieldset>



		<fieldset class="adminform">
		<legend></legend>


		<table class="admintable">
			<tr valign="top">
				<td class="label" nowrap><?php echo $this->__( 'Credit Type' ); ?> <span class="required">*</span></td>
				<td><select id="" name="rule[credit_type]" class="inputbox required-entry" onchange="change_pay()">
					<option value=""></option>
					<?php $select = $_rule->getData('credit_type'); ?>
					<?php foreach (Mage::helper('awodev_aworewards')->vars('credit_type') as $k => $v): ?>
						<option value="<?php echo $k ?>" <?php if($k==$select): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
					</select>
				</td>
				<td class="value scope-label"></td>
			</tr>
			<tr valign="top" id="tr_pay_points" style="display:none;">
			<td class="label" nowrap><label><?php echo $this->__( 'Points' ); ?></label></td>
				<td><input class="inputbox validate-aworewards-creditpoints" type="text" name="rule[points]" size="30" maxlength="255" value="<?php echo $_rule->getData('points'); ?>" /></td>
				<td class="value scope-label"></td>
			</tr>
			<tr valign="top" id="tr_pay_coup" style="display:none;">
				<td class="label" nowrap><label><?php echo $this->__( 'Coupon to Copy' ); ?></label></td>
				<td><select id="" name="rule[template_id]" class="inputbox">
					<option value=""></option>
					<?php $select = $_rule->getData('template_id'); ?>
					<?php foreach ($_couponlist as $v): ?>
						<option value="<?php echo $v->coupon_id ?>" <?php if($v->coupon_id==$select): ?>selected="selected"<?php endif ?>><?php echo $v->code ?></option>
					<?php endforeach ?>
					</select>
				</td>
				<td class="value scope-label"></td>
			</tr>
			<tr valign="top" id="tr_pay_exp" style="display:none;">
				<td class="label" nowrap valign="top"><label><?php echo $this->__( 'Expiration' ).' ('.$this->__('Days').')'; ?></label></td>
				<td><input class="inputbox" type="text" name="rule[params][coupon_expiration]" size="30" maxlength="255" value="<?php echo !empty($params->coupon_expiration) ? $params->coupon_expiration : ''; ?>" /></td>
				<td class="value scope-label"></td>
			</tr>
			
			<tr id="tr_pay_system_email_subject" style="display:none;">
				<td class="label"><?php echo $this->__( 'Email Subject' ); ?></td>
				<td><?php foreach($_storelist as $k=>$v) : ?>
						<input style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox <?php if($k==0) echo 'validate-aworewards-credit-mage_coupon';?>" type="text" size="60" name="rule[locale][email_subject][<?php echo $k; ?>]" value="<?php echo !empty($locale->email_subject[$k]) ? $locale->email_subject[$k] : ''; ?>" maxlength="255">
					<?php endforeach; ?>
				</td>
				<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
			</tr>
			<tr id="tr_pay_ps_email_body" style="display:none;" valign="top">
			
				<td class="label">
					<?php echo $this->__( 'Message' ); ?><span class="star">&#160;*</span>
					<br style="clear:both;"/><br /><div align="right"><table style="text-align:left;font-weight:normal;">
					<tr><th><?php echo $this->__( 'Tags' ); ?></th></tr>
						<tr><td>{store_name}</td></tr>
						<tr><td>{siteurl}</td></tr>
						<tr><td>{coupon_code}</td></tr>
						<tr><td>{coupon_value}</td></tr>
						<tr><td>{coupon_expiration}</td></tr>
						<tr><td>{recipient_firstname}</td></tr>
						<tr><td>{recipient_lastname}</td></tr>
						<tr><td>{today_date}</td></tr>
						<tr><th><?php echo $this->__( 'Referrals' ); ?></td></tr>
						<tr><td>{sponsor_firstname}</td></tr>
						<tr><td>{sponsor_lastname}</td></tr>
						<tr><th><?php echo $this->__( 'Order' ); ?></td></tr>
						<tr><td>{order_number}</td></tr>
						<tr><td>{order_date}</td></tr>
						<tr><td>{order_total}</td></tr>
					</table></div>
				</td>
				<td><?php foreach($_storelist as $k=>$v) : ?>
						<textarea id="rule_locale_email_body_<?php echo $k; ?>" name="rule[locale][email_body][<?php echo $k; ?>]" style="<?php if($k!=0) echo 'display:none'; ?>" class="inputbox <?php if($k==0) echo ''; ?>" cols="30" rows="10"  ><?php echo !empty($locale->email_body[$k]) ? $locale->email_body[$k] : ''; ?></textarea>
					<?php endforeach; ?>
 				</td>
				<td class="value scope-label" nowrap><?php echo Mage::helper('adminhtml')->__('[STORE VIEW]') ?></td>
			</tr>
			
			
		</table>

		</fieldset>
		
		
		
		

		
	
	</div>


	<div class="clr"></div>







<input name="rule[id]" type="hidden" value="<?php echo $_id ?>" />
<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />

</form>
</div>



<script type="text/javascript">
var editForm = new varienForm('edit_form');

/*Validation.addAllThese([['validate-aworewards-regdelay', '<?php echo Mage::helper('awodev_aworewards')->__('Please use numbers only in this field. Please avoid spaces or other characters such as dots or commas.') ?>', function(v,elm) {
	if(elm.form.elements["rule[rule_type]"].value!='registration') return true;
	return !/[^\d]/.test(v);

}]]);*/

Validation.addAllThese([
	['validate-aworewards-date', '<?php echo Mage::helper('awodev_aworewards')->__('Please enter a valid date.') ?>', function(v,elm) {
			if(v=='YYYY-MM-DD hh:mm:ss') {
				v = '';
				elm.form.elements[elm.name].value = '';
			}
			if(v=='') return true;
			if(!/^\d{4}\-\d{2}\-\d{2}\s+\d{2}\:\d{2}\:\d{2}$/.test(v)) return false;
			else {
				YYYY = v.substr(0,4);
				MM = v.substr(5,2);
				DD = v.substr(8,2);
				hh = v.substr(11,2);
				mm = v.substr(14,2);
				ss = v.substr(17,2);
				if(YYYY>2100 || MM>12 || DD>31 || hh>23 || mm>59 || ss>59) return false;
			}
			return true;
	}]
	,['validate-aworewards-ordermintype', '<?php echo Mage::helper('awodev_aworewards')->__('This field is required.') ?>', function(v,elm) {
		if(elm.form.elements["rule[rule_type]"].value!='order') return true;
		return !Validation.get('IsEmpty').test(v);
	}]
	,['validate-aworewards-ordermin', '<?php echo Mage::helper('awodev_aworewards')->__('Please enter a number 0 or greater in this field.') ?>', function(v,elm) {
		if(elm.form.elements["rule[rule_type]"].value!='order') return true;

		if (Validation.get('IsEmpty').test(v)) return true;
		v = parseNumber(v);
		return !isNaN(v) && v >= 0;
	}]
	,['validate-aworewards-ordertrigger', '<?php echo Mage::helper('awodev_aworewards')->__('Please enter string.') ?>', function(v,elm) {
		if(elm.form.elements["rule[rule_type]"].value!='order') return true;
		if (Validation.get('IsEmpty').test(v)) return true;
		return /^\d+(\s*,\s*\d+)*\s*$/.test(v);
	}]

	,['validate-aworewards-promohead', '<?php echo Mage::helper('awodev_aworewards')->__('This is a required field.') ?>', function(v,elm) {
		var tmp = ['facebook_wall','twitter_tweet','facebook_like','twitter_follow'];
		if(tmp.indexOf(elm.form.elements["rule[rule_type]"].value)==-1) return true;
		return !Validation.get('IsEmpty').test(v);
	}]
	,['validate-aworewards-predefined', '<?php echo Mage::helper('awodev_aworewards')->__('This is a required field.') ?>', function(v,elm) {
		var tmp = ['facebook_wall','twitter_tweet'];
		if(tmp.indexOf(elm.form.elements["rule[rule_type]"].value)==-1) return true;
		return !Validation.get('IsEmpty').test(v);
	}]
	,['validate-aworewards-follow', '<?php echo Mage::helper('awodev_aworewards')->__('This is a required field.') ?>', function(v,elm) {
		var tmp = ['facebook_like','twitter_follow'];
		if(tmp.indexOf(elm.form.elements["rule[rule_type]"].value)==-1) return true;
		return !Validation.get('IsEmpty').test(v);
	}]
	,['validate-aworewards-creditpoints', '<?php echo Mage::helper('awodev_aworewards')->__('Please enter a number 0 or greater in this field.') ?>', function(v,elm) {
		if(elm.form.elements["rule[credit_type]"].value!='points') return true;
		if(elm.form.elements["rule[rule_type]"].value=='order' && !Validation.get('IsEmpty').test(elm.form.elements["rule[params][order_percent]"].value)) return true;
		v = parseNumber(v);
		return !isNaN(v) && v >= 0;
	}]
	,['validate-aworewards-orderpercent', '<?php echo Mage::helper('awodev_aworewards')->__('Please enter a number 0 or greater in this field.') ?>', function(v,elm) {
		if(elm.form.elements["rule[rule_type]"].value!='order') return true;
		if (Validation.get('IsEmpty').test(v)) return true;
		v = parseNumber(v);
		return !isNaN(v) && v >= 0;
	}]
	,['validate-aworewards-credit-mage_coupon', '<?php echo Mage::helper('awodev_aworewards')->__('This field is required.') ?>', function(v,elm) {
		var tmp = ['mage_coupon'];
		if(tmp.indexOf(elm.form.elements["rule[credit_type]"].value)==-1) return true;
		return !Validation.get('IsEmpty').test(v);
	}]

]);



/*
	if(form.elements["rule[credit_type]"].value=='mage_coupon') {
		//if(form.template_id.selectedIndex==0) err += '\n'+str_template+': '+str_err_selection;
		if(trim(form.elements["rule[params][coupon_expiration]"].value)!='' && !isUnsignedInteger(form.elements["rule[params][coupon_expiration]"].value)) err += '\n'+str_coup_exp+': '+str_err_valid_value;
		//if(form.profile_id.selectedIndex==0) err += '\n'+str_profile+': '+str_err_selection;
	} 

*/



</script>