<?php

require_once '../abstract.php';

class Pmainguet_RemoveSpecificOrigins extends Mage_Shell_Abstract{

	public function deletespecoptions()
	{

		$array=[
			"origine" =>[
				"Afrique du Sud",
				"Algérie",
				"Allemagne",
				"Angleterre",
				"Antilles",
				"Argentine",
				"Atlantique ",
				"Atlantique Centre-Est",
				"Atlantique Nord",
				"Atlantique Nord-Est",
				"Australie",
				"Autriche",
				"Belgique",
				"Bénin",
				"Biélorussie",
				"Brésil",
				"Bulgarie",
				"Cameroun",
				"Canada",
				"Chili",
				"Chine",
				"Colombie",
				"Corse",
				"Costa Rica",
				"Côte d'Ivoire",
				"Crète",
				"Cuba",
				"Danemark",
				"Ecosse",
				"Egypte",
				"Equateur",
				"Espagne",
				"Ethiopie",
				"Europe",
				"France",
				"Ghana",
				"Golfe de Corinthe",
				"Grande Bretagne",
				"Grèce",
				"Hollande",
				"Honduras",
				"Ile Maurice",
				"Iran",
				"Irlande",
				"Islande ",
				"Israël",
				"Italie ",
				"Japon",
				"Jordanie",
				"Kenya",
				"La Réunion",
				"Lituanie",
				"Madagascar",
				"Manche",
				"Maroc",
				"Martinique",
				"Méditerranée",
				"Mer Baltique",
				"Mexique",
				"Norvège",
				"Nouvelle-Zélande",
				"Océan Indien",
				"Ouganda",
				"Pacifique Nord",
				"Pays-Bas",
				"Pérou",
				"Pologne",
				"Portugal",
				"République Dominicaine",
				"République Tchèque",
				"Réunion",
				"Russie",
				"Sardaigne",
				"Sénégal",
				"Sicile",
				"Suisse",
				"Togo",
				"Tunisie",
				"Turquie",
				"Uruguay",
				"Venezuela",
				"Vietnam",
			],
			'produit_biologique' =>[
				"Oui",
				"Non",
			],
			'produit_de_saison' =>[
				"Oui",
				"Non",
			],
			'labels_produits' => [
				'AOC',
				'AOP',
				'IGP',
				'DOC',
				'DOP',
				"Biodynamie",
				'Demeter',
				'Direct Producteur',
				'Label Rouge',
				'Local',
				'Sans Lactose',
				'Sans Gluten',
				'Végétarien',
				'Vegan',
				'Acidulé & Fruité',
				'Corsé & Généreux',
				'Doux & Aromatique',
				'Doux et subtil',
				'Épicé et gourmand',
				'Explosif & fruité',
				'Floral & Elégant',
				'Fort & Etoffé',
				'Fruité',
				'Fruité & Floral',
				'Minéral',
				'Minéral & Fruité',
				'Moelleux',
				'Puissant & rond',
				'Puissant & Gourmand',
				'Puissant & Sauvage',
				'Sauvage',
				'Sauvage & Chocolaté',
				'Sec',
				'Bleu Blanc Coeur',
				'Noir de Bigorre',
				'Oméga 3',
				'Chair farineuse',
				'Chair ferme',
				'Chair tendre',
				'Pleine Terre',
				'Fabrication artisanale',
				'Fait Maison',
				'Casher',
				'Halal',
				'Qualité Supérieure',
				'Sans sel',
				'Sans traitement',
				'Selon arrivage',
				'Stock Limité',
				'Tablettes assemblage',
				'Tablettes de plantation',
				'Tablettes de terroir',
				'Vigneron indépendant',
				'Commerce Equitable',
			],
			'producteur' => [
				"Brasserie Franziskaner",
				"Conserverie Algoplus",
				"Ferme avicole du lac",
				"Happy Crulture",
				"Prince des Dombes",
				"Martin et James",
				"Volailles des Champs",
				"Accoceberry",
				"Acetaia Montale Rangone",
				"Affinage Frères Paccard",
				"Affinage Maison Seignemartin",
				"Affinage Marcel Charrade",
				"Affiné par Terres d'Auvergne",
				"Affineur Marcel Petite",
				"Agrilatina",
				"Agrobiodôme",
				"Agrôbiome",
				"Agromonte",
				"Ahadi",
				"Alain Barbier",
				"Alain Milliat",
				"Alain Regnault",
				"Alce Nero",
				"Alejandro",
				"Ambrosi",
				"Andines",
				"André Laurent",
				"André Legrand",
				"Anfosso",
				"Anne-Marie et Jean-Guy Todeschini",
				"Antoine Picard",
				"Au Rucher de Flora",
				"Authentikon",
				"Azais Polito",
				"Babybio",
				"Beaujolais",
				"BelleNature",
				"Benoit Déhu",
				"Bergerie des Costes",
				"Beutelsbacher",
				"BF",
				"Billecart Salmon",
				"Bioleyre",
				"Bordier",
				"Boule de Miel",
				"Bouvet",
				"Brasserie Altiplano",
				"Brasserie Bosteel",
				"Brasserie Boulevard Brewery",
				"Brasserie Brew Dog",
				"Brasserie d'Achouffe",
				"Brasserie des Sources",
				"Brasserie Dupont",
				"Brasserie Kiuchi Brewery",
				"Brasserie L.Huygue",
				"Brasserie Lepers",
				"Brasserie Shepherd Neame",
				"C. Gorrec",
				"Café Michel ",
				"Cardell",
				"Carle",
				"Carles",
				"Cascita Daneto",
				"Caseificio Maldera",
				"Caseificio Palazzo",
				"Caseificio Taddei",
				"Castaing",
				"Caves Cathédrales",
				"Cazes",
				"Cécile Gondard",
				"Celnat",
				"Challans",
				"Champicarde",
				"Chapoutier",
				"Château Beynat",
				"Château Cadenette",
				"Château de Berne",
				"Château de Coulaine",
				"Chateau La Brande",
				"Château Montrose",
				"Château Yvonne",
				"Chocolat Robert",
				"Cirio",
				"Citadelle",
				"Claire Naudin",
				"Clémence herbes et sens",
				"Clothilde Pain",
				"Coca-Cola",
				"Collines",
				"Comme Des Papas",
				"Comptoir du Caviar",
				"Comptoires et Compagnies",
				"Comsea",
				"Cook",
				"Coop de Yenne",
				"Coopérative Fromagère Jeune Montagne",
				"Coopérative Les Bergers du Larzac",
				"Coopérative Vercors Lait",
				"Coopérative Vercos",
				"Coquet",
				"Costa d'Oro",
				"Couronne de Dijon",
				"Croc' Olives",
				"Crosti ",
				"D'ANVIAL",
				"Danival ",
				"De la famille Dolcerrocca",
				"DELAMOTTE",
				"Délicemer",
				"Delicio",
				"Des Hommes & des Boeufs",
				"Désirs et Traditions",
				"Destination Bio ",
				"Deutz Classic",
				"Diplomatico",
				"Dispo limitée",
				"Domaine Cadenette",
				"Domaine Champier",
				"Domaine d'en Ségur",
				"Domaine de Beaujeu",
				"Domaine de l'aumonier",
				"Domaine de la croix belle",
				"Domaine de la Dourbie",
				"domaine de la Genillotte",
				"Domaine de la Patience",
				"Domaine de la Taille aux Loups",
				"Domaine Des artauds",
				"Domaine des garances",
				"Domaine du Cristia",
				"Domaine Duplessis",
				"Domaine FL",
				"Domaine Fournier",
				"Domaine Lafond Roc-Epine",
				"Domaine Lafouge",
				"Domaine Lassagne",
				"Domaine Massin",
				"Domaine PEROL",
				"Domaine Taliani",
				"Domaine Tremeaux",
				"Domaine Villalin",
				"Drouet",
				"Du Bocq",
				"Dubernet",
				"dubernet",
				"EARL de la sebirerie",
				"EARL du bois bleu",
				"EARL Le Clos",
				"Edgar Brwkhor",
				"Emile Noël ",
				"Etoile du Quercy",
				"Excel",
				"Famille Carle",
				"Famille Dombre",
				"Famille Fabre",
				"Famille Paccard",
				"Famille Paugam",
				"Famille Paugam / Regnault",
				"Famille Perrin",
				"Famille Perros",
				"Famille Saget ",
				"Famille Salamita",
				"Familli Solarino",
				"FAOU",
				"Farme Montalet",
				"Fattoria Dell'Alento",
				"Ferme Belair",
				"Ferme Chapuis",
				"Ferme de Bellevue",
				"Ferme de Férolles",
				"Ferme de la Bretonnerie",
				"Ferme de la Nalière",
				"Ferme de Viltain",
				"Ferme des Arnaud",
				"Ferme des Loges",
				"Ferme du Bourg",
				"Ferme du Champ Secret",
				"Ferme du Gâtinais",
				"Ferme du pont des loups",
				"Ferme du vert",
				"Ferme Durr",
				"Ferme Marine de Campomoro",
				"Ferme Plagne",
				"Ferme Terres Promises",
				"Ferme Ticoz  /Regnault",
				"Finesse des Vergers",
				"Fisker",
				"Fjordking",
				"Fraîcheur des Cabanes",
				"France",
				"France Coq",
				"Franck Phélan",
				"François & Jean-Marie Cherrier",
				"François Bedel",
				"François Morel",
				"Fréderic Mabileau",
				"FREVAL",
				"Fromagerie Bamalou",
				"Fromagerie Berthaut",
				"Fromagerie Bio du Maine",
				"Fromagerie de Bellelay",
				"Fromagerie de Saunière",
				"Fromagerie Delin",
				"Fromagerie Dolcerocca",
				"Fromagerie Dongé",
				"Fromagerie Duroux",
				"Fromagerie Gaugry",
				"Fromagerie Graidorge",
				"Fromagerie Jacquin",
				"Fromagerie Le Pic",
				"Fromagerie Les Monts de Joux",
				"Fromagerie San Salvatore",
				"Fruitière Vinicole d'Arbois",
				"Fumaison de l'arsenal",
				"Fumerie artisanale Andric",
				"Gaec des Pampilles",
				"GAEC Les Marronniers",
				"Garofallo",
				"Gillardeau",
				"Gilles Gelun",
				"Gilles Hervy",
				"Gillot",
				"Gocce d'Isola",
				"Godminster",
				"Grandeur Nature",
				"Granomy",
				"Guillaume Verger",
				"Guy et Marylone Julien",
				"Gwénolé Leroy",
				"Havanna",
				"Hinano",
				"Iliada",
				"Istara",
				"J. Barthouil",
				"J.Mourat",
				"Jacquelin",
				"Jacques Tissot",
				"Jardin de Gaïa ",
				"JC David",
				"Jean Bousquet",
				"Jean d'Aubignac",
				"Jean d'Audignac",
				"Jean Hervé ",
				"Jean Michel Lesage",
				"Jean-Claude Boisset",
				"Jean-Philippe Dubourdieu",
				"JM Chancel",
				"Joseph Landron",
				"Kaltbach",
				"Kaviari",
				"Kaviari Paris",
				"Kerbriant",
				"L'abeille bleue",
				"L'atelier Bernard MAROT",
				"L'Atelier du Poissonnier",
				"L'épicurien -confitures artisanales-",
				"L'épicurien -culinaire-",
				"L'épicurien -les condiments-",
				"L'épicurien -les culinaires-",
				"L'épicurien -les fromagères-",
				"L'épicurien -les gourmandises-",
				"L'épicurien -les tartinables-",
				"L'Esprit des Clos",
				"L'Isola D'Oro",
				"L'oustalet",
				"La Baratte du Crémier",
				"la bastide blanche",
				"La bio d'Olivier",
				"La cantine Riondo",
				"La Chanteracoise",
				"La Croix saint laurent",
				"La ferme de Sauvagnat",
				"La Hulotte",
				"La Merced Campo",
				"La Mère-Mimosa",
				"La Mortuacienne",
				"La Racotière",
				"La Sablaise",
				"La Soculente",
				"Laborie",
				"Lait cru de chèvre",
				"Laiterie de la ferme de Grignon",
				"Laiterie des Hauts de Savoie",
				"Langerigue",
				"Le bio d'Olivier",
				"Le Coq Toqué",
				"Le Craulois",
				"Le Grand Lejon",
				"Le Montsurais",
				"Le pain des fleurs",
				"Le Pas-Sage Obligé",
				"Le rendez-vous des gourmets",
				"Le Saunier de Camargue",
				"Le Sauzet",
				"Lehmann",
				"Léon Dupont",
				"Les ANTONIN",
				"Les bergers du larzac",
				"Les caves d'Ordanche",
				"Les Charbonnières - La vallée de Joux",
				"Les délices du maraicher",
				"Les Fanalous",
				"Les Frambises",
				"Les Fromageries Occitanes",
				"Les Impeccables",
				"Les Monts de Joux",
				"Les Sauces Morin",
				"Les saveurs de Chailly",
				"Les saveurs de Clavon",
				"Les Terres d'Auvergne",
				"Llusard",
				"Loïc Durand",
				"Louis Max",
				"Luxeapers",
				"Maison Appert",
				"Maison Carle",
				"Maison Carles",
				"Maison Fontaine des veuves",
				"Maison Gaudin",
				"Maison Matartre",
				"Maison Pouzadoux",
				"Manet Freres",
				"Mangue|framboise|fraise|ananas",
				"Marc Kreydenweiss",
				"Marie Hot",
				"Marillier père et fils",
				"Markal ",
				"Markal",
				"Maxence Baud",
				"Meneau",
				"Merve Restauration",
				"Michel Besnier",
				"Michel Guigner",
				"Mieral",
				"Mme Cazes",
				"Monsallier",
				"Monsieur Appert",
				"Montcalm",
				"Monte Naro",
				"Monterosa",
				"Moreau Naudet",
				"Morin",
				"Moulin de Chantemerle",
				"Moulin de La Gaumerie",
				"Moulin Oliversion",
				"Mouneyrac",
				"Murgella",
				"Mutti",
				"Nathalie & Philippe",
				"Nicolas Perrin",
				"Nikka",
				"Ogier",
				"Oleanthi",
				"Olivier Depardon",
				"Oosterlinck-brake",
				"ORRI",
				"Overnat ",
				"Pamplie",
				"Pan",
				"Panealba",
				"Papillon",
				"Pascal Delbeck",
				"Pascal et Jacky Preys",
				"Paul Georgelet",
				"Paul Mas",
				"Père Louis",
				"Philia",
				"Philippe Raimbault",
				"Phillippe Cartoux",
				"Pichaud Solignac",
				"Pierre et Bertrand Couly",
				"Plaimont",
				"Polenta Valsugana",
				"Pommery",
				"Portugal",
				"Primaflore",
				"Priméal",
				"Primeale",
				"Prince de Bretagne",
				"Prince de Paris",
				"Prosain ",
				"Provamel ",
				"Pyla",
				"R.Junca",
				"Rapunzel ",
				"Rebélion",
				"Ricotta del Brigante",
				"Rinascita",
				"Roble",
				"Rocca",
				"Roche",
				"Roland Augustin & Fils",
				"Rosée de la Reine ",
				"Roussy",
				"Saint Faron",
				"Saint Joseph de rivière",
				"Salamita",
				"Sales",
				"SARL Bonde de Gâtine",
				"SARL Bourel",
				"SARL DUBOIS",
				"SARL Le Fédou",
				"Sassy",
				"Sauce Bistrot",
				"Saveurs d'Italie",
				"Schweppes",
				"Sebastien David",
				"Ségala",
				"Senorio Vizcantar",
				"Sgambaro",
				"Shim'on Ariche",
				"Smith Haut Laffite",
				"Soal",
				"Sophie et Thierry Chardon",
				"Brasserie St Stefanus",
				"Stéphane Chetrit",
				"Superproducteur",
				"Sylvain Rabate",
				"Tentazione Pugliesi",
				"Terra Madre",
				"Terre de Berne",
				"Terres de Café",
				"Teyssier",
				"Thomas Queguiner",
				"V. Bouchard",
				"Vendée",
				"Vergers de Suarone",
				"Viander",
				"Villani",
				"Vincent Siret-Courtaud",
				"Yves Combes",
			]
		];

		$setup = new Mage_Eav_Model_Entity_Setup('core_setup');
		
		foreach($array as $name => $value){
			$attribute  = Mage::getSingleton("eav/config")->getAttribute("catalog_product", $name);
			foreach ($attribute->getSource()->getAllOptions() as $option) {
			        if(!in_array($option['label'],$value)){
			        	echo "Delete ".$option["label"]." from product attribute dataset".PHP_EOL;
			        	$update['delete'][$option['value']] = true;
			        	$update['value'][$option['value']] = true;
			        }
			}
			$setup->addAttributeOption($update);
		}
		die();
	}

	// Implement abstract function Mage_Shell_Abstract::run();
    public function run()
    {
        $steps = ['deletespecoptions'];
        //get argument passed to shell script
        $step = $this->getArg('step');
        if (in_array($step, $steps)) {
            $this->$step();
        } else {
            echo "STEP MUST BE ONE OF THESE:\n";
            foreach ($steps as $s) {
                echo $s.",\n";
            }
        }
    }

}

$shell = new Pmainguet_RemoveSpecificOrigins();
$shell->run();