<?php
/**
/ @author Pierre Mainguet
*/
?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>amasty/amorderattr/payment.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>amasty/amorderattr/conditions.js"></script>
<script type="text/javascript">

    //var h = new Hash();
    Validation.addAllThese([
        ['validate-checkboxgroup-required', 'Please select an option.', function(v, elm) {
            id = elm.id.slice(0, elm.id.lastIndexOf("_"));
            checkboxGroupChecked = false;
            $$('input[id^=' + id + ']').each(function(checkbox){
                if (checkbox.checked || jQuery(checkbox).hasClass('validation-failed'))
                {
                    checkboxGroupChecked = true;
                }
            });
            return checkboxGroupChecked;
        }],
        
        ['validate-length', 'Please use the value with length less or equal than 25 characters', function(v) {
            return v.length <= 25;
        }],
        ['validate-zip', 'Merci de spécifier un code postal valide, sans espace, par exemple 75001', function(v) {
            return Validation.get('IsEmpty').test(v) || /(^\d{5}$)/.test(v);
            }],
    ]);
    function clearHash() {
        h = new Hash();
    }
    $$('#checkoutSteps button').each(function(button){
        button.observe('click', clearHash);
    });
    
    var amOrderattrConditionObj = new amOrderattrCondition({
        'shipping_methods': []    });
    
    amOrderattrConditionObj.check();
</script>
<form id="co-billing-form" action="" class="apdc-form">
	<div class="row">

		<div class="col-sm-6">
			<fieldset>
				<ul class="form-list">
					<label class="control-label" for="shipping-address-select"><?php echo $this->__('Votre adresse de livraison') ?></label>
				<?php if ($this->customerHasAddresses()): ?>
				   <li class="wide fields">
					   <div class="input-box">
					       <label><?php echo $this->__('Vos adresses enregistrées') ?></label>
						   <?php echo $this->getAddressesHtmlSelect('shipping') ?>
					   </div>
				   </li>
				<?php endif ?>
					<li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
						<fieldset>
							<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
							<ul>
								<li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
						<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
								<li class="fields">
									<label for="shipping:street1" class="required"><?php echo $this->__('Address') ?> <em>*</em></label>
									<div class="input-box">
										<input maxlength="128" type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
									</div>
								</li>
						<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
						<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
								<li class="fields">
									<div class="input-box">
										<input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
									</div>
								</li>
						<?php endfor; ?>
								<?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
								<li class="fields">
									<label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
									<div class="input-box">
										<input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
									</div>
								</li>
								<?php endif; ?>
								<li class="fields">
									<div class="field">
										<label for="shipping:city" class="required"><?php echo $this->__('City') ?> <em>*</em></label>
										<div class="input-box">
											<input maxlength="60" type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
										</div>
									</div>
									<div class="field">
										<label for="shipping:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?> <em>*</em></label>
										<div class="input-box">
											<input maxlength="5" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
										</div>
									</div>
								</li>
								<li class="fields">
									<div class="field">
										<label for="shipping:country_id" class="required"><?php echo $this->__('Country') ?> <em>*</em></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
									<div class="field">
										<label for="shipping:region" class="required"><?php echo $this->__('State/Province') ?> <em>*</em></label>
										<div class="input-box">
											<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
												<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
											</select>
											<script type="text/javascript">
											//<![CDATA[
												$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
											//]]>
											</script>
											<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
										</div>
									</div>
								</li>
								<li class="fields">
									<div class="field">
										<label for="shipping:telephone" class="required"><?php echo $this->__('Telephone') ?> <em>*</em></label>
										<div class="input-box">
											<input maxlength="10" type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
										</div>
									</div>
								</li>
							<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
								<li class="control">
									<input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
							<?php else:?>
								<li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
							<?php endif;?>
							</ul>
						</fieldset>
					</li>
				</ul>    
			</fieldset>
		</div>
		<div class="col-sm-6">
			<div id="amorderattr" class="form-second-column">
			    <div class="row fields">
                    <div class="field col-md-4">
                        <label for="batiment">Bâtiment</label>
                        <input maxlength="20" id="batiment" name="amorderattr[batiment]" value="<?php echo Mage::helper('apdc_checkout')->getSavedAttrValue('batiment');?>" class="input-text" type="text"/>
                        <div type="anchor" id="anchor_batiment"></div>
                    </div>
                    <div class="field required col-md-4">
                        <label for="etage">Etage <em>*</em></label>
                        <input maxlength="3" id="etage" name="amorderattr[etage]" value="<?php echo Mage::helper('apdc_checkout')->getSavedAttrValue('etage');?>" class="required-entry input-text" type="text"/>
                        <div type="anchor" id="anchor_etage"></div>
                    </div>
                    <div class="field col-md-4">
                        <label for="codeporte1">Code porte 1 & 2</label>
                        <input maxlength="10" id="codeporte1" name="amorderattr[codeporte1]" value="<?php echo Mage::helper('apdc_checkout')->getSavedAttrValue('codeporte1');?>" class="input-text" type="text"/>
                        <div type="anchor" id="anchor_codeporte1"></div>
                    </div>
                </div>
				<div class="row fields">
				    <div class="field required col-md-6">
                        <label for="contactvoisin">Contact en cas d'absence <em>*</em></label>
                        <input maxlength="80" id="contactvoisin" name="amorderattr[contactvoisin]" value="<?php echo Mage::helper('apdc_checkout')->getSavedAttrValue('contactvoisin');?>" class="required-entry input-text" type="text"/>
                        <div type="anchor" id="anchor_contactvoisin"></div>
                    </div>
                    <div class="required field col-md-6">
                        <label for="telcontact">Téléphone du contact <em>*</em></label>
                        <input maxlength="10" id="telcontact" name="amorderattr[telcontact]" value="<?php echo Mage::helper('apdc_checkout')->getSavedAttrValue('telcontact');?>" class="required-entry input-text" type="text"/>
                        <div type="anchor" id="anchor_telcontact"></div>
                    </div>
				</div>
				<div class="row fields">
				    <div class="field col-md-12">
                        <label for="infoscomplementaires">Informations complémentaires</label>
                        <input maxlength="490" id="infoscomplementaires" name="amorderattr[infoscomplementaires]" value="<?php echo Mage::helper('apdc_checkout')->getSavedAttrValue('infoscomplementaires');?>" class=" input-text" type="text"/>
                        <div type="anchor" id="anchor_infoscomplementaires"></div>
                    </div>
				</div>
				<p class="required"><?php echo $this->__('* Required Fields') ?></p>
			</div>
		</div>
        <ul>
            <li class="control fields">
                <input type="checkbox" name="billing[same_as_shipping]" id="billing:same_as_shipping" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Shipping Address') ?>" onclick="billing.setSameAsShipping(this.checked, 'billing-address-row')" class="checkbox" /><label for="billing:same_as_shipping"><?php echo $this->__('L\'adresse de facturation est la même que l\'adresse d\'expédition') ?></label>
            </li>
        </ul>
	</div>	
	<div class="row" id="billing-address-row">	
		<div class="col-sm-6">
			<fieldset>
				<ul class="form-list">
					<label class="control-label" for="billing-address-select"><?php echo $this->__('Adresse de facturation') ?></label>
				<?php if ($this->customerHasAddresses()): ?>
					<li class="wide">
						<div class="input-box">
							<?php echo $this->getAddressesHtmlSelect('billing') ?>
						</div>
					</li>
				<?php endif; ?>
				<li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
					<fieldset>
						<input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
						<ul>
							<li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
							<li class="fields">
					<?php if(!$this->isCustomerLoggedIn()): ?>
								<div class="field">
									<label for="billing:email" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
									<div class="input-box">
										<input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
									</div>
								</div>
					<?php endif; ?>
							</li>
					<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
							<li class="fields">
								<label for="billing:street1" class="required"><?php echo $this->__('Address') ?> <em>*</em></label>
								<div class="input-box">
									<input maxlength="128" type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
								</div>
							</li>
					<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
					<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
							<li class="fields">
								<div class="input-box">
									<input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
								</div>
							</li>
					<?php endfor; ?>
							<?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
							<li class="fields">
								<label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
								<div class="input-box">
									<input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
								</div>
							</li>
							<?php endif; ?>
							<li class="fields">
								<div class="field">
									<label for="billing:city" class="required"><?php echo $this->__('City') ?> <em>*</em></label>
									<div class="input-box">
										<input maxlength="60" type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
									</div>
								</div>
								<div class="field">
									<label for="billing:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?> <em>*</em></label>
									<div class="input-box">
										<input maxlength="5" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
									</div>
								</div>
							</li>
							<li class="fields">
								<div class="field">
									<label for="billing:country_id" class="required"><?php echo $this->__('Country') ?> <em>*</em></label>
									<div class="input-box">
										<?php echo $this->getCountryHtmlSelect('billing') ?>
									</div>
								</div>
								<div class="field">
									<label for="billing:region_id" class="required"><?php echo $this->__('State/Province') ?> <em>*</em></label>
									<div class="input-box">
										<select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
											<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
										</select>
										<script type="text/javascript">
										//<![CDATA[
											$('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
										//]]>
										</script>
										<input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
									</div>
								</div>
							</li>
							<li class="fields">
								<div class="field">
									<label for="billing:telephone" class="required"><?php echo $this->__('Telephone') ?> <em>*</em></label>
									<div class="input-box">
										<input maxlength="10" type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
									</div>
								</div>
							</li>
							<?php if(!$this->isCustomerLoggedIn()): ?>

					<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
					<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
						<?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
							<li class="fields">
							<?php if ($_dob->isEnabled()): ?>
								<div class="field">
									<?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
								</div>
							<?php endif; ?>
							<?php if ($_gender->isEnabled()): ?>
								<div class="field">
									<?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
								</div>
							<?php endif ?>
							</li>
						<?php endif ?>

						<?php if ($this->isTaxvatEnabled()):?>
							<li><?php echo $this->getTaxvatHtml() ?></li>
						<?php endif; ?>

							<li class="fields" id="register-customer-password">
								<div class="field">
									<label for="billing:customer_password" class="required"><?php echo $this->__('Password') ?> <em>*</em></label>
									<div class="input-box">
										<input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
									</div>
								</div>
								<div class="field">
									<label for="billing:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?> <em>*</em></label>
									<div class="input-box">
										<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
									</div>
								</div>
							</li>
							<?php echo $this->getChildHtml('persistent.remember.me'); ?>
							<?php endif; ?>
							<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
								<li class="control">
									<input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
								</li>
							<?php else:?>
								<li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
							<?php endif; ?>
							<?php echo $this->getChildHtml('form.additional.info'); ?>
						</ul>
						<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
					</fieldset>
				 </li>
				</ul>
				<?php if (!$this->canShip()): ?>
					<input type="hidden" name="billing[use_for_shipping]" value="1" />
				<?php endif; ?>
			</fieldset>
		</div>
	</div>
    <div class="buttons-set clearfix" id="billing-buttons-container">
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button button-green pull-right" onclick="billing.save()"><?php echo $this->__('Continue') ?> <i class="fa fa-angle-right"></i></button>
        <div class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Un instant s\'il vous plaît...') ?>" title="<?php echo $this->__('Un instant s\'il vous plaît...') ?>" class="v-middle" /> <?php echo $this->__('Un instant s\'il vous plaît...') ?>
        </div>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }

	var shipping = new Shipping('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
	var shippingForm = new VarienForm('co-billing-form');
	shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
	$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

	var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
