<?php
/**
 *
 * @author    Pierre Mainguet
 */
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><strong><?php echo $_link->getLabel() ?></strong></a></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
     <div class="follow-us">
        <strong style="color:black"><span>Suivez-nous sur</span></strong>
    </div>
    <div class="order-account">
        <button type="button" title="Commandez de nouveau" onclick="parent.location='<?php echo Mage::getBaseUrl();?>'" class="button" value="Appliquer"><span>Commandez de nouveau</span></button>
    </div>
</div>
