<div class="page-header"><h1>Connexion</h1></div>
<div class="row">
  <div class="col-md-12">
<p>Si vous n'êtes pas encore inscrit, vous pouvez le faire en <a href="index.php?module=membres&amp;action=inscription">cliquant sur ce lien</a>.</p>

<?php

if (!empty($erreurs_connexion)) {

	echo '<ul>'."\n";
	
	foreach($erreurs_connexion as $e) {
	
		echo '	<li>'.$e.'</li>'."\n";
	}
	
	echo '</ul>';
}

    // generate output using a custom template
      $form_connexion->render();

?>
  </div>
</div>

