<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="page-header"><h2>Liste des Commerçants</h2></div>
      <div class="text_accueil">
	       <p>Cliquez sur un nom pour avoir accès à la fiche du commerçant</p>
      </div>  
      <div class="liste_commercant">
        <?php
          $cat=liste_commercant_id("store");
          $stores=list_rootcatid("name");
          foreach($cat as $store => $com):?>
              <h3><?php echo "Boutique ".$stores[$store];?></h3>
              <div id="liste-commercant-<?php echo $store;?>">
              <?php foreach($com as $id=>$info):?>
                  <a href="index.php?module=commercant&action=view&id=<?php echo $id;?>" target="_blank"><button type="button" class="btn btn-default btn-lg btn-block" style="margin-bottom:10px;"><?php echo $info["name"];?></button></a>
              <?php endforeach;?>      
            </div>
        <?php endforeach; ?>
      </div>
    </div>
    <div class="col-md-4"></div>
  </div>

<!--le div fermant le container se trouve dans le fichier footer.php-->