<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="page-header"><h2>Liste des Commerçants</h2></div>
      <div class="text_accueil">
	       <p>Cliquez sur un nom pour avoir accès à la fiche du commerçant</p>
      </div>  
      <div class="liste_commercant">
        <?php 

        //A modifier lorsque l'on aura plusieurs boutiques
        $cat=liste_commercant_id();
        foreach($cat as $id=>$name){
            $cat_id=0;
            $categories = Mage::getModel('catalog/category')->getCollection()->addAttributeToSelect('*');
            foreach ($categories as $category) {
              $categ = Mage::getModel("catalog/category")->load($category->getId());
              if($categ->getAttComId()==$id){
                $cat_id=$category->getId();
              }
            }
                ?>
                <a href="index.php?module=commercant&action=view&id=<?php echo $cat_id;?>" target="_blank"><button type="button" class="btn btn-default btn-lg btn-block" style="margin-bottom:10px;"><?php echo $name;?></button></a>
            <?php
          }
        ?>
      </div>
      </div>
    <div class="col-md-4"></div>
  </div>

<!--le div fermant le container se trouve dans le fichier footer.php-->