<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="page-header"><h2>Liste des Commerçants</h2></div>
      <div class="text_accueil">
	       <p>Cliquez sur un nom pour avoir accès à la liste des commandes par commerçant.</p>
      </div>
      <?php
          $cat=getShops(-1,"store");
          $stores=list_rootcatid("name");
          foreach($cat as $store => $com):?>
              <h3><?php echo "Boutique ".$stores[$store];?></h3>
              <center><a href="javascript:openall(<?php echo $store; ?>)" style="float:left;"><button id="all-button-<?php echo $store;?>" type="button" class="btn btn-success btn-lg" style="margin-bottom:10px;">Ouvrir tous</button></a></center>
              <div id="liste-commercant-<?php echo $store;?>">
              <?php foreach($com as $id=>$info):?>
                  <a href="index.php?module=commande&action=view&id=<?php echo $id;?>" target="_blank"><button type="button" class="btn btn-default btn-lg btn-block" style="margin-bottom:10px;"><?php echo $info["name"];?></button></a>
              <?php endforeach;?>      
            </div>
      <?php endforeach; ?>
    </div>
    <div class="col-md-4"></div>
  </div>
  <script type="text/javascript">
  function openall(store) {
    var links=$('#liste-commercant-'+store).find('a');
    var go = confirm("Ouvrir les "+links.length+" pages commerçant?");
      if (go) {
        links.each(function() {
           window.open($(this).attr('href'), '_blank');

        });
      }
  };
  </script>


<!--le div fermant le container se trouve dans le fichier footer.php-->