<?php $info=getShop($_GET['id'])?>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="page-header"><h2><?= $info["name"];?> <small>Fiche Profil</small></h2></div>
      <div class="info_commercant">
        <dl class="dl-horizontal">
          <dt>Adresse</dt>
          <dd><a href="<?= $info["url_adresse"];?>"><?= $info["adresse"];?></a></dd>
          <dt>Téléphone</dt>
          <dd><a href="tel:<?= $info["phone"];?>"><?= $info["phone"];?></a></dd>
          <dt>Site Internet</dt>
          <dd><a href="<?= $info["name"];?>"><?= $info["name"];?></a></dd>
          <dt>Nom du contact</dt>
          <dd><?= $info["name"];?></dd></dd>
          <dt>Email</dt>
          <dd><a href="mailto:<?= $info["name"];?>"><?= $info["name"];?></a></dd>
          <dt>Horaire d'ouverture</dt>
          <dd><?= $info["name"];?></dd>
          <dt>Jour dispo</dt>
          <dd><?= $info["name"];?></dd>
          <dt>Infos Complémentaires</dt>
          <dd><?= $info["name"];?></dd>
        </dl>
      </div>
      <div class="button_profil">
          <a id="liste_commande" href="index.php?module=commande&action=view&id=<?php echo $_GET['id'];?>"><button type="button" class="btn btn-success btn-lg">Liste des commandes</button></a>
          <a id="retour_liste" href="index.php?module=commercant&action=view"><button type="button" class="btn btn-default btn-block btn-lg">Retour à la liste des commerçants</button></a>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>

<!--le div fermant le container se trouve dans le fichier footer.php-->