<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="page-header"><h2><?php echo commercant($_GET['id'])->getName();?> <small>Fiche Profil</small></h2></div>
      <div class="info_commercant">
        <dl class="dl-horizontal">
          <dt>Adresse</dt>
          <dd><a href="http://maps.google.com/?q=<?php echo commercant($_GET['id'])->getData('adresse_commercant')?>"><?php echo commercant($_GET['id'])->getData('adresse_commercant')?></a></dd>
          <dt>Téléphone</dt>
          <dd><a href="tel:<?php echo commercant($_GET['id'])->getData('portable')?>"><?php echo commercant($_GET['id'])->getData('portable')?></a></dd>
          <dt>Site Internet</dt>
          <dd><a href="<?php echo commercant($_GET['id'])->getData('site_internet')?>"><?php echo commercant($_GET['id'])->getData('site_internet')?></a></dd>
          <dt>Nom du contact</dt>
          <dd><?php echo commercant($_GET['id'])->getData('nom_contact')?></dd></dd>
          <dt>Portable</dt>
          <dd><a href="tel:<?php echo commercant($_GET['id'])->getData('portable')?>"><?php echo commercant($_GET['id'])->getData('portable')?></a></dd>
          <dt>Email</dt>
          <dd><a href="mailto:<?php echo commercant($_GET['id'])->getData('mail_contact')?>"><?php echo commercant($_GET['id'])->getData('mail_contact')?></a></dd>
          <dt>Horaire d'ouverture</dt>
          <dd><?php echo commercant($_GET['id'])->getData('horaires_commercant')?></dd>
          <dt>Jour dispo</dt>
          <dd><?php echo commercant($_GET['id'])->getData('livraison_commercant')?></dd>
          <dt>Infos Complémentaires</dt>
          <dd><?php echo commercant($_GET['id'])->getData('infos_complementaires')?></dd>
        </dl>
      </div>
      <div class="button_profil">
          <a id="liste_commande" href="index.php?module=commande&action=view&id=<?php echo $_GET['id'];?>"><button type="button" class="btn btn-success btn-lg">Liste des commandes</button></a>
          <a id="retour_liste" href="index.php?module=commercant&action=view"><button type="button" class="btn btn-default btn-block btn-lg">Retour à la liste des commerçants</button></a>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>

<!--le div fermant le container se trouve dans le fichier footer.php-->