<?php

use Zend\Form\Form;

trait Forms {
	private function _getForm ($name) {
		$form = new Form($name);
		$form->setAttribute('method', 'POST');
		return $form;
	}

	private function _getForm_fromTo () {
		$form = $this->_getForm('fromto');
		$form->add([
			'type'		=>	'text',
			'name'		=>	'from',
			'options'	=>	[
				'label'	=>	'From: ',
			],
			'attributes'	=>	[
				'class'	=>	'form-control datepicker'
			]
		]);
		$form->add([
			'type'		=>	'text',
			'name'		=>	'to',
			'options'	=>	[
				'label'	=>	'To: ',
			],
			'attributes'	=>	[
				'class'	=>	'form-control datepicker'
			]
		]);

		return ($form);
	}

	private static function _addSubmit(Form $form, $value = 'Submit') {
		$form->add([
			'type'		=>	'submit',
			'name'		=>	'submit',
			'attributes'	=>	[
				'value'	=>	'Search',
				'class'	=>	'btn btn-default'
			]
		]);
		return $form;
	}

	public function getForm() {
		$form = $this->_getForm('from');
		$form->add([
			'type'		=>	'text',
			'name'		=>	'from',
			'options'	=>	[
				'label'	=>	'From: ',
			],
			'attributes'	=>	[
				'class'	=>	'form-control datepicker'
			]
		]);
		return (static::_addSubmit($form, 'Search'));
	}
	
	public function getForm_input() {
		$form = $this->_getForm('id');
		$form->add([
			'type'		=>	'text',
			'name'		=>	'id',
			'options'	=>	[
				'label'	=>	'Id: ',
			],
			'attributes'	=>	[
				'class'	=>	'form-control input'
			]
		]);
		return (static::_addSubmit($form, 'Search'));
	}

	public function getForm_fromTo () {
		$form = $this->_getForm_fromTo ();
		return (static::_addSubmit($form, 'Search'));
	}

	public function getForm_fromTo_select ($opt = [], $value = -1) {
		$form = $this->getForm_fromTo();
		$form->add([
			'type'	=>	'select',
			'name'	=>	'commercantId',
			'attributes'	=>	[
				'value'	=>	$value,
				'class'	=>	'form-control'
			],
			'options'	=>	$opt
		]);
		return (static::_addSubmit($form, 'Search'));
	}
}
