<script>
	function init() {
	    var imgDefer = document.getElementsByTagName('img');
	    for (var i=0; i<imgDefer.length; i++) {
	        if(imgDefer[i].getAttribute('data-src')) {
	            imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src'));
	        }
	    }
	    var vidDefer = document.getElementsByTagName('iframe');
	    for (var i=0; i<vidDefer.length; i++) {
	        if(vidDefer[i].getAttribute('data-src')) {
	            vidDefer[i].setAttribute('src',vidDefer[i].getAttribute('data-src'));
	        }
	    }
	}
	window.onload = init;
</script>
<script type="text/javascript">
	function downloadJSAtOnload() {
	    var jsArray = [
	        // "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'googleanalytics/ga.js'?>",
	        "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'tawkto/tawkto.js'?>",
	       	"<?php echo $this->getSkinUrl('js/custom.js');?>"
	        ];
	    var arrayLength = jsArray.length;
	    for (var i = 0; i < arrayLength; i++) {
	        var element = document.createElement("script");
	        element.src = jsArray[i];
	        document.body.appendChild(element);
	    }
	}
	if (window.addEventListener)
		window.addEventListener("load", downloadJSAtOnload, false);
	else if (window.attachEvent)
		window.attachEvent("onload", downloadJSAtOnload);
	else window.onload = downloadJSAtOnload;
</script>
<?php $key = Mage::getStoreConfig('api_key/google/google_nav'); ?>
<script type="text/javascript" src='https://maps.googleapis.com/maps/api/js?key=<?= $key ?>&libraries=places&callback=GoogleApiLandingpage'></script>
