<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" type="image/png" href="<?php echo $this->getSkinUrl('images/favicon-32x32.png').'?v=Ryo4wAQ5QR';?>" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo $this->getSkinUrl('images/favicon-16x16.png').'?v=Ryo4wAQ5QR';?>" sizes="16x16">
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/favicon.ico').'?v=Ryo4wAQ5QR';?>">
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->getIncludes() ?>