<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>" style="margin:40px 0;">
    <div class="page-title">
        <h1><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                <?php echo $this->__('Login or Create an Account') ?>
            <?php else: ?>
                <?php echo $this->__('Login'); ?>
            <?php endif; ?></h1>
    </div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="apdc-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6 registered-users">
                <?php echo $this->getMessagesBlock()->toHtml() ?>
                <div class="content fieldset">
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                         <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                         <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                        <div class="col-sm-12" style="text-align:center;">
                            <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><?php echo $this->__('Login') ?></span></button>
                            <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left" style="margin-left:20px;"><?php echo $this->__('Forgot Your Password?') ?></a>
                        </div>
                    </ul>  
                </div>
            </div>
             <div class="col-sm-3"></div>
        </div>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-6" style="text-align:center;">
                <p class="required">&nbsp;</p>
                <span>Pas encore de compte ? </span><a title="<?php echo $this->__('Register') ?>" class="button" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><span><?php echo $this->__('Register') ?></span></a>
            </div>
            <div class="col-sm-3"></div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
</div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>

