<?= $this->menu ?>
<div class="container">
	<?= $this->fromtoS ?>
	<hr>
	<?php foreach ($this->orders as $commercant_id => $commercant ) : ?>
		<div class="merchant">
			<label><?= $commercant['name'] ?></label><br />
			<?php foreach($commercant['orders'] as $order_id => $order) : ?>
				<?php $text = "{$order['first_name']} {$order['last_name']}"; ?>
				<table style="width: 100%">
					<tr>
						<td style="width: 40%">
							<a href="#<?= $order_id ?>" data-toggle="collapse">
								<label><?= "{$order_id} {$text}" ?></label>
							</a>
						</td>
						<td style="width: 30%">
							<label><?= "Nombre d'articles: {$order['Total quantite']}" ?></label>
						</td>
						<td style="width: 30%">
							<label><?= "Total: {$order['Total prix']}€"?></label>
						</td>
					<tr/>
					<tr>
						<td colspan="3">
							<div id="<?= $order_id ?>" class="order collapse">
								<table class="table" style="width: 50%">
									<tr>
										<td><b>Commande n°</b></td>
										<td><a href="/indi/orders/<?= $order_id ?>" target="_blanc"><?= $order_id ?></a></td>
									</tr>
									<tr>
										<td><b>Client</b></td>
										<td><?= "{$order['first_name']} {$order['last_name']}" ?></td>
									</tr>
									<tr>
										<td><b>Prise de commande</b></td>
										<td><?= $order['order_date'] ?></td>
									</tr>
									<tr>
										<td><b>Date de Livraison</b></td>
										<td><?= $order['delivery_date'] ?></td>
									</tr>
									<tr>
										<td><b>Creneau de Livraison</b></td>
										<td><?= $order['delivery_time'] ?></td>
									</tr>
									<tr>
										<td><b>Remplacement equivalent</b></td>
										<td><?= ($order['equivalent_replacement']) ? "oui" : "non" ?></td>
									</tr>
								</table>
								<table class="table table-striped">
									<tr>
										<th>Produit</th>
										<th>Quantite</th>
										<th>Description</th>
										<th>Prix</th>
										<th>Total</th>
										<th>Commentaire</th>
									</tr>
									<?php foreach($order['products'] as $product) : ?>
										<tr>
											<td><?= $product['nom'] ?></td>
											<td><?= $product['quantite'] ?></td>
											<td><?= $product['description'] ?></td>
											<td><?= "{$product['prix_kilo']}€ ({$product['prix_kilo']})" ?></td>
											<td><?= "{$product['prix_total']}€" ?></td>
											<td><?= $product['comment'] ?></td>
										</tr>
									<?php endforeach ?>
									<tr>
										<td><b>TOTAL</b></td>
										<td colspan="3"><b><?= $order['Total quantite'] ?></b></td>
										<td colspan="2"><b><?= "{$order['Total prix']}€" ?></b></td>
									</tr>
								</table>
							</div>
						</td>
					</tr>
				</table>
			<?php endforeach ?>
		</div>
	<?php endforeach ?>
</div>
