<?php $customerDefaultPostcode = Mage::helper('apdc_neighborhood')->getCustomerDefaultPostcode(); ?>
<div class="neighborhood_choose">
    <form action="<?php echo $this->getSaveUrl(); ?>" method="post" id="neighborhood-choose-form" class="apdc-form">
        <div class="form-group">
            <?php if ($customerDefaultPostcode) : ?>
                <p><?php echo $this->__('Merci de confirmer votre code postal afin de nous aider à sélectionner les commerçants proche de chez vous.'); ?></p>
            <?php else : ?>
                <p><?php echo $this->__('Merci d\'indiquer votre code postal afin de nous aider à sélectionner les commerçants proche de chez vous.'); ?></p>
            <?php endif; ?>
        </div>
        <div class="form-group">
            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($customerDefaultPostcode) ?>" id="postcode" class="input-text required-entry" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Code postal')) ?>" placeholder="Votre code postal" />
        </div>
        <div class="form-group">
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Valider')); ?>" class="button button-green"><span><span><?php echo $this->__('Valider'); ?></span></span></button>
        </div>
    </form>
</div>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('neighborhood-choose-form', true);
    $j('#neighborhood-choose-form').on('submit', function (e) {
      apdcLoginPopup.showLoading();
      try {
            tagmanager_event('validationInscription',{});
        } catch(e) {
            console.log(e);
        }
     });
//]]>
</script>    
