<?php $neighborhoods = $this->getNeighborhoods(); ?>
<ul id="my_neighborhood_choose_links" class="skip-content links">
    <li class="neighborhood_informations">
            <div class="neighborhood_informations_title"><?php echo $this->__('Vous avez le choix !'); ?></div>
            <p><?php echo $this->__('Merci de sélectionner le quartier dans lequel vous souhaitez commander.'); ?></p>
    </li>
    <?php foreach ($neighborhoods as $neighborhood) : ?>
        <li class="neighborhood_list choose" id="<?php echo $neighborhood->getWebsiteId();?>" style="display: none;">
            <?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($neighborhood->getImage(), array('width' => 50, 'height' => 50)); ?>
            <a href="<?php echo Mage::app()->getStore($neighborhood->getWebsiteId())->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>" title="<?php echo $this->__('Choose this neighborhood'); ?>">
                <img src="<?php echo $imageUrl; ?>" title="<?php echo $neighborhood->getName(); ?>" width="50" height="50" />
                <p>
                    <span><?php echo $neighborhood->getName(); ?></span>
                    <i><?php echo $this->__('Available for delivery addresses in %s', implode(', ', unserialize($neighborhood->getPostcodes()))); ?></i>
                </p>
            </a>
        </li>
    <?php endforeach; ?>
</ul>