<?php
	//Version for Amasty Delivery Module
	if(Mage::helper('core')->isModuleEnabled('amdeliverydate')){
		$hlp = Mage::helper('amdeliverydate');
		$storeId = $this->getCurrentStore();
		$options = $hlp->getTIntervals($storeId);
		$count=1;
		foreach($options as $timeint){
			if($timeint<>''){
				if($count%2<>1){
					echo $timeint.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
				}else{
					echo $timeint.'</br>';
				}
			}
			$count+=1;
		}
	}

	//Version for Mage World Delivery Module
	if(Mage::helper('core')->isModuleEnabled('MW_Ddate')){
		$hlp = Mage::helper('ddate');
		$storeId = $this->getCurrentStore();
		$timeObjs = $hlp->getDtime($storeId);
		$dTstr_tab = [];
		$html = '';

		foreach($timeObjs as $tObj){
			$dTstr = $tObj->getInterval();
			if ($dTstr <> '')
				$dTstr_tab[] = $dTstr;
		}
		uasort($dTstr_tab, function ($dTlhs, $dTrhs) {
			return strcmp($dTlhs, $dTrhs);
		});

		foreach($dTstr_tab as $dTstr){
			$html .= <<<END
<span style="display:block;float:left;width:50%;padding-top:5px;padding-bottom:0px;">$dTstr</span>
END;
		}
		echo $html;
	}
?>
