<div class="row homepage-reassurance">
	<div class="col-xs-12">
	<div class="title-block">Comment ça marche</div>
		<div class="colored-line"></div>
	    <div id="carrousel-reassurance" class="owl-carousel">
			<div>
				<div class="reassurance-outer first-item">
					<div class="reassurance-inner">
						<i class="fa fa-eur reassurance-icon fa-2x" style="padding-top: 20px;"></i>
						<span><strong>COMMANDEZ EN LIGNE</strong><br/>en une seule fois<br/>aux mêmes prix qu'en magasin</span>
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer second-item">
					<div class="reassurance-inner">
						<i class="fa fa-clock-o reassurance-icon fa-2x"></i>
						<span><strong>NOS CRENEAUX DE LIVRAISON</strong><br/>
						<?= $this->getChildHtml('deliverytime-home') ?>
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer third-item">
					<div class="reassurance-inner">
						<i class="fa fa-calendar reassurance-icon fa-2x"></i>
						<span><strong>DU MARDI AU VENDREDI</strong><br>Livraison le jour même pour une commande avant 15h.</span>
					</div>
				</div>
			</div>
			<div>
				<div class="reassurance-outer fourth-item">
						<div class="reassurance-inner">
							<span class="icone-reassurance">10€</span>
							<a href="https://www.aupasdecourses.com/batignolles/aworewards/invitation/">
								<span><strong>EN BON D'ACHAT</strong><br>En parrainant vos proches </br><i>Cliquez pour en savoir plus</i></span>
							</a>
						</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 livraison-countdown" id="#livraison-countdown">
		<div id="countdown"></div>
	</div>
</div>
