<div class="account-lostpassword-container">
    <div class="back-link">
        <a href="#" data-login-view="<?php echo $this->getUrl('apdc-customer/account/ajaxPopupView');?>" role="button" class="to-login-form">
            <small>« </small>
            <?php echo $this->__('Back'); ?>
        </a>
    </div>
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getUrl('apdc-customer/account/ajaxForgotPassword');?>" method="post" id="password-form" class="scaffold-form">
        <div class="form-group">
            <p class="form-instructions"><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        </div>
        <div class="form-group">
            <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" alt="email" id="email_address" class="input-text required-entry validate-email form-control" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" placeholder="<?php echo $this->__('Email Address') ?>"/>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="form-group">
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button button-green"><span><span><?php echo $this->__('Submit') ?></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('password-form', true);
    //]]>
    </script>
</div>
