<?php
/**
 *
 * @author    Pierre Mainguet
 */
?>
<div class="row">
    <div class="block block-account col-md-4">
        <div class="block-content">
            <ul class="menu-account">
                <?php $_links = $this->getLinks(); ?>
                <?php $_index = 1; ?>
                <?php $_count = count($_links); ?>
                <?php foreach ($_links as $_link): ?>
                    <?php $_last = ($_index++ >= $_count); ?>
                    <?php if ($this->isActive($_link)): ?>
                        <li class="current<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><strong><?php echo $_link->getLabel() ?> <i class="fa fa-angle-right fa-2x pull-right"></i></strong></a></li>
                    <?php else: ?>
                        <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
