<?php
/**
 * @package		AwoDev_AwoRewards
 * @copyright	Copyright (C) Seyi Awofadeju - All rights reserved.
 * @website		http://awodev.com
 * @license		http://awodev.com/content/magento-license
 **/

$_menu = Mage::helper("awodev_aworewards")->getMenu();
?>

<ul class="links">
	<?php 
	$is_first = true;
	foreach($_menu as $item) {
		$first_html = '';
		if($is_first) {
			$is_first = false;
			$first_html = 'class="first"';
		}
		echo '<li '.$first_html.'>
				'.(!$item['is_current'] ? '<a href="'.$item['url'].'">' : '').'
					'.$item['label'].'
				'.(!$item['is_current'] ? '</a>' : '').'
			</li>';
	}
	?>
</ul>
<div style="clear:both;"></div>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
