<div class="flexbox flexbox--vertical">
	<div class="flexbox__item">
		<div class="page-header page-boundary container">
			<div class="page-container text--center">
				<div class="icon icon_uber">
				</div>
			</div>
		</div>
	</div>
	<div class="flexbox__item flexbox__item--expand">
		<div class="page-content">
			<div class="page-lead trip-feedback-receipt flexbox">
				<div class="flexbox__item">
					<h1 class="trip-feedback-receipt__header color--white soft--bottom">Merci
					</h1>
					<h4 class="gamma soft--top color--neutral">Vous avez attribué 2 étoiles à votre chauffeur
					</h4>
					<i class="icon icon_star star star--active star--large soft-half">
					</i>
					<i class="icon icon_star star star--active star--large soft-half">
					</i>
					<i class="icon icon_star star star--not-chosen star--large soft-half">
					</i>
					<i class="icon icon_star star star--not-chosen star--large soft-half">
					</i>
					<i class="icon icon_star star star--not-chosen star--large soft-half">
					</i>
					<div class="soft--top color--neutral">Nous sommes vraiment désolés de cette mauvaise expérience. N'hésitez pas à vous rendre sur 
						<a href="https://help.uber.com">help.uber.com
						</a> pour nous en dire plus.
					</div>
					<div class="center-block trip-feedback__button-container">
						<a href="/trips/bd47fdd2-85d5-403e-b9d4-e31db96f5b6b" class="btn trip-feedback__button">Course
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="flexbox__item">
		<div class="page-footer page-boundary container">
			<div class="page-container">
				<div class="flexbox">
					<div class="flexbox__item one-third">
						<ul class="nav nav--block flush">
							<li>
								<a href="https://twitter.com/uber" class="link--immutable">
									<span class="icon icon--circle icon_twitter">
									</span>
								</a>
							</li>
							<li>
								<a href="https://www.facebook.com/uber" class="link--immutable">
									<span class="icon icon--circle icon_facebook">
									</span>
								</a>
							</li>
							<li>
								<a href="http://www.linkedin.com/company/uber.com" class="link--immutable">
									<span class="icon icon--circle icon_linkedin">
									</span>
								</a>
							</li>
						</ul>
					</div>
					<div class="flexbox__item one-third text--center brand-face hidden--portable">
						<ul class="nav gamma text--uppercase push-half--bottom">
							<li>
								<a href="https://www.uber.com/">Accueil
								</a>
							</li>
							<li class="soft--sides">&bull;
							</li>
							<li>
								<a href="https://www.uber.com/cities">Villes
								</a>
							</li>
							<li class="soft--sides">&bull;
							</li>
							<li>
								<a href="https://www.uber.com/drivers">Chauffeurs
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>