<?php
	$shops = $this->getListShops();
	$nbShops = count($shops);
?>
<div id="commercants-block" class="row hp-section commercants-block container-fluid">
	<div class="commercants-list col-md-12">
		<h2 class="title-block">Vos Commer&ccedil;ants</h2>
		<div class="colored-line"></div>
		<div class="row">
			<div class="commercants-main products-grid col-md-12">
				<div id="carrousel-commercants" class="owl-carousel">
					<?php
						$i = 0;
						$j = 0;
						foreach ($shops as $shop):
							if($i == 0 || $i%6 == 0) {
								$j = 0;
								$class = '';
								if($i > 0) {
									$class = ' no-first';
								}
								echo '<div class="commercant-item'.$class.'">' ;
							}
							if($j < 3) {
								?>
									<div class="commercant-info-img">
										<div class="commercant-info">
											<div>
												<h3 class="product-name"><?= $shop['name'];?></h3>
												<span><?= $shop['adresse'];?></span>
											</div>
										</div>
										<div class="commercant-img">
											<a class="product-image" href="<?= $shop['url'];?>" title="<?= $shop['name'];?>">
												<!--<img src="<?= $shop['src'];?>" width="100%" alt="<?= $shop['name'];?>" title="<?= $shop['name'];?>" />-->
												<img src="<?php echo Mage::getBaseUrl().'../skin/frontend/boilerplate/default/dist/images/img-commercants.jpg'?>" width="100%" alt="" title="" />
											</a>
										</div>
									</div>
								<?php
							}
							else {
								?>
									<div class="commercant-img-info">
										<div class="commercant-img">
											<a class="product-image" href="<?= $shop['url'];?>" title="<?= $shop['name'];?>">
												<!--<img src="<?= $shop['src'];?>" width="100%" alt="<?= $shop['name'];?>" title="<?= $shop['name'];?>" />-->
												<img src="<?php echo Mage::getBaseUrl().'../skin/frontend/boilerplate/default/dist/images/img-commercants.jpg'?>" width="100%" alt="" title="" />
											</a>
										</div>
										<div class="commercant-info">
											<div>
												<h3 class="product-name"><?= $shop['name'];?></h3>
												<span><?= $shop['adresse'];?></span>
											</div>
										</div>
									</div>
								<?php
							}
							if((($i+1)%6 == 0 && $i != 0) || $i == $nbShops) {
								echo '</div>' ;
							}
							$i ++;
							$j ++;
						endforeach;
					?>
						<!--<div class="commercant-item">
				            <a class="product-image" href="<?php echo Mage::getUrl('formulaire/index/commercantsmanquants')?>" title="A venir">
				                <img src="<?php echo Mage::getBaseUrl('media').'resource/commerçant_dummy.png'?>" width="100%" alt="" title="" />
				            </a>
				            <h3 class="product-name" style="text-align:center;"><a href="<?php echo Mage::getBaseUrl().'commercant-form/'?>">Suggérez nous votre commerçant, Cliquez ici!</a></h3>
				        </div>-->
				</div>
			</div>
		</div>
	</div>
</div>
<script>
    $j(document).ready(function() {
      $j("#carrousel-commercants").owlCarousel({
            items:1,
            itemsScaleUp : true,
			itemsDesktop : [1199,3],
			itemsTablet : [720,1],
            pagination:false,
            autoPlay : false,
            slideSpeed : 800,
            navigation : true,
            navigationText : ['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>']
      });
    });
</script>
