<?php
	$current_cat_Id=Mage::registry('current_category')->getId();
	$childrenCat = Mage::getResourceModel('catalog/category_collection')
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('is_active', 1)
    ->addAttributeToFilter('parent_id', $current_cat_Id)
    ->addAttributeToSort('position');
?>
<div class="commercant_product_cat commercant-selection">
	<h2 class="title-block" style="width:300px">Les rayons</h2>
	<div class="colored-line"></div>
	<div class="col-md-12">
		    <div id="carrousel-cats" class="owl-carousel">
				<?php foreach ($childrenCat as $cat):
					  $cat=Mage::getModel('catalog/category')->load($cat->getId());
					  $cat_name=$this->htmlEscape($cat->getName());
				?>
							<div class="linkcat">
								<a href="<?= $cat->getUrl()?>">
								<div class="img-wrapper">
								    <img class="img-responsive img-thumbnail" src="<?php echo Mage::helper('apdc_catalog/category')->getThumbnailImageUrl($cat); ?>" alt="<?=$cat_name?>" title="<?=$cat_name?>" />
								    <div class="description">
								    		<span><?=$cat_name?></span>
								    </div>
								</div>
								</a>
						    </div>
				<?php endforeach;
					//Reset the category to the current category, otherwise use last category data in foreach loop
					Mage::getSingleton('catalog/layer')->setCurrentCategory($current_cat_Id);  
				?>
			</div>
	</div>
</div>
<script>
    $j(document).ready(function() {
     
      $j("#carrousel-cats").owlCarousel({
            items:4,
            pagination:false,
            autoPlay : false,
            navigation : true
      });
     
    });
</script>
