<?php
    $shop_info=$this->getInfoShop();
 ?>
<div class="row">
	<div class="page-title category-title col-xs-12">
	    <h1 class="subtitle commercant_name"><?= $shop_info['name'] ?></h1>
	</div>
</div>
<div class="row">
	<div class="col-md-12 commercant-bottom-margin">
		<div class="row">
			<div class="col-md-6" style="z-index:9;">
				<div class="photo-commercant">
					<img class="img-responsive img-thumbnail" src="<?= $shop_info["image"] ?>">
				</div>
			</div>
			<div class="col-md-6 commercant-selection">
				<h2 class="title-block" style="width:300px">La petite histoire</h2>
				<div class="colored-line"></div>
				<div class="desc-commercant">
					<p><?= $shop_info['description'] ?></p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="row commercant-selection">
			<h2 class="title-block" style="width:300px">Les infos pratiques</h2>
			<div class="colored-line"></div>
			<div class="col-md-6">
				<dl class="dl-horizontal infos-commercant">
				  <dt>Adresse</dt>
				  	<dd>
				  		<a href="$url_adresse" target="_blank"><?= $shop_info['adresse'];?></a>
				  		<iframe class="map-commercant" src="https://www.google.com/maps?q=<?= $shop_info['adresse'];?>&output=embed"></iframe>
				  	</dd>
				</dl>
			</div>
			<div class="col-md-6">
				<dl class="dl-horizontal infos-commercant">
				  <dt>Jour livraisons</dt><dd><?= $shop_info['delivery_days'] ?></dd>
				  <dt>Horaires du magasin</dt><dd><?= $shop_info['timetable']?></dd>
				</dl>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<?php echo $this->getLayout()->getBlock("breadcrumbs")->toHtml()?>
</div>
<div class="row">
	<?php echo $this->getChildHtml("commercant-categories");?>
</div>
<div class="row">
	<div class="col-sm-12 block_selection">
		<?php echo $this->getChildHtml('blockselection')?>
	</div>
</div>