<?php $shop_info = $this->getInfoShop(); ?>
<?php $shopAvailability = $this->getShopAvailability(); ?>
<?php if (!empty($shop_info)) : ?>
<div class="container-fluid commercant-collapse">
    <div class="row">
        <div class="col-md-12 commercant-info">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-7" style="z-index:9;">
                    <div class="photo-commercant">
                        <img class="img-responsive" src="<?= $shop_info["thumbnail_image"] ?>">
                    </div>
                    <div class="commercant-name">
                        <h1 class="subtitle"><a href="<?php echo $shop_info['url']; ?>" title="<?= $shop_info['name'] ?>"><?= $shop_info['name'] ?></a></h1>
                        <i class="fa fa-map-marker"></i> <?= $shop_info['adresse'];?>
                    </div>
                </div>
                <?php echo $this->getChildHtml('apdc_catalog_shop_availability'); ?>
                <div class="col-xs-12 col-sm-1 text-right text-center">
                    <div class="open-collapse">
                        <i class="fa fa-angle-down"></i>
                    </div>
                </div>
            </div>
            <?php if (!empty($shopAvailability) && $shopAvailability['status'] > 1) : ?>
                <div class="row shop-availability">
                    <div class="col-xs-12 text-center">
                        <div class="shop-availability-container">
                            <div class="shop-availability-icon cell">
                                <i class="fa fa-info-circle"></i>
                            </div>
                            <div class="shop-availability-content cell">
                                <p class="shop-availability-message"><?php echo $shopAvailability['message']; ?></p>
                                <span><?php echo $this->__('Commerçant non disponible pour le créneau que vous avez sélectionné'); ?></span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-md-12 collapse-wrapper">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 commercant-opening">
                    <h2>Horaires de la boutique</h2>
                    <div><?= $shop_info['timetable']?></div>
                    <?php if (!empty($shop_info)) : ?>
                    <?php $header = ''; ?>
                    <?php $body = ''; ?>
                    <div class="delivery_days">
                        <h3 class="delivery_days_title"><?php echo $this->__('Livraison possible le'); ?></h3>
                        <?php foreach(Mage::helper('apdc_commercant')->getWeekDays() as $weekDay): ?>
                            <?php if (is_null($weekDay['value']) || !in_array($weekDay['value'], $shop_info['delivery_days'])) : ?>
                                <?php $classHeader = 'no'; ?>
                                <?php $body .= '<td><i class="fa fa-close"></i></td>'; ?>
                            <?php else : ?>
                                <?php $classHeader = 'yes'; ?>
                                <?php $body .= '<td><i class="fa fa-check"></i></td>'; ?>
                            <?php endif; ?>
                            <?php $header .= '<th class="' . $classHeader . '">' . $weekDay['label'] . '</th>'; ?> 
                        <?php endforeach; ?>
                        <div>
                            <table>
                                <thead>
                                    <tr><?php echo $header; ?></tr>
                                </thead>
                                <tbody>
                                    <tr><?php echo $body; ?></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endif; ?>
                </div>
                <div class="col-md-4 col-sm-4 commercant-img">
                    <img class="img-responsive" src="<?= $shop_info["image"] ?>">
                </div>
                <div class="col-lg-4 col-md-5 col-sm-4 col-lg-offset-1 desc-commercant">
                    <h2 class="title-block">La petite histoire</h2>
                    <p><?= $shop_info['description'] ?></p>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="block_selection">
    <?php echo $this->getLayout()->getBlock("breadcrumbs")->toHtml(); ?>
	<?php
		$currentcat = Mage::getSingleton('catalog/layer')->getCurrentCategory();
		if($currentcat->getLevel()== 3 && $this->getChild("blockselection")){
			$this->getChild("blockselection")->setData("shop_info", $shop_info);
			echo $this->getChildHtml('blockselection', false);
		}
	?>
</div>

<script type="text/javascript">
    $j(window).ready(function(){
        
        $j('.open-collapse').on('click', function(){
            if($j(this).hasClass('open')){
                $j('.collapse-wrapper').hide().removeClass('open');
                $j(this).removeClass('open');
                $j('i', this).removeClass('fa-angle-up').addClass('fa-angle-down');
            }
            else{
                $j('.collapse-wrapper').show().addClass('open');
                $j(this).addClass('open');
                $j('i', this).removeClass('fa-angle-down').addClass('fa-angle-up');
            }
        });
        <?php if ($currentcat->getLevel() == 3) : ?>
            $j('.open-collapse').click();
        <?php endif; ?>
    })
</script>
