<?php
    //$shop_info=$this->getInfoShop();
	$shop_info = Mage::helper('apdc_commercant')->getInfoShop();
	$delivery_days = $shop_info['delivery_days'];
 ?>
<div class="container-fluid commercant-collapse">
    <div class="row">
        <div class="col-md-12 commercant-info">
            <div class="row">
                <div class="col-md-6" style="z-index:9;">
                    <div class="photo-commercant">
                        <img class="img-responsive" src="<?= $shop_info["thumbnail_image"] ?>">
                    </div>
                    <div class="commercant-name">
                        <h1 class="subtitle"><a href="<?php echo $shop_info['url']; ?>" title="<?= $shop_info['name'] ?>"><?= $shop_info['name'] ?></a></h1>
                        <i class="fa fa-map-marker"></i> <?= $shop_info['adresse'];?>
                    </div>
                </div>
                <div class="col-md-5 text-right delivery-days">
                    <h2>Livraison disponible le</h2>
					<div>
						<table>
							<thead>
								<?php
									foreach($delivery_days as $key => $value) {
										$class = '';
										if($value == 1) {
											$class = 'no';
										}
										else {
											$class = 'yes';
										}
										echo '<th class="'.$class.'">'.$key.'</th>';
									}
								?>
							</thead>
							<tbody>
								<?php
									foreach($delivery_days as $key => $value) {
										if($value == 1) {
											echo '<td><i class="fa fa-close"></i></td>';
										}
										else {
											echo '<td><i class="fa fa-check"></i></td>';
										}
									}
								?>
							</tbody>
						</table>
					</div>
                </div>
                <div class="col-md-1 text-right text-center">
                    <div class="open-collapse">
                        <i class="fa fa-angle-down"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 collapse-wrapper">
            <div class="row">
                <div class="col-md-3 col-sm-4 commercant-opening">
                    <h2>Horaires de la boutique</h2>
                    <div><?= $shop_info['timetable']?></div>
                </div>
                <div class="col-md-4 col-sm-4 commercant-img">
                    <img class="img-responsive" src="<?= $shop_info["image"] ?>">
                </div>
                <div class="col-md-4 col-sm-4 col-md-offset-1 desc-commercant">
                    <h2 class="title-block">La petite histoire</h2>
                    <p><?= $shop_info['description'] ?></p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
	<?php echo $this->getChildHtml("commercant-categories");?>
</div>
<div class="block_selection">
    <?php echo $this->getLayout()->getBlock("breadcrumbs")->toHtml(); ?>
	<?php
		$currentcat = Mage::getSingleton('catalog/layer')->getCurrentCategory();
		if($currentcat->getLevel()== 3){
			$this->getChild("blockselection")->setData("shop_info", $shop_info);
			echo $this->getChildHtml('blockselection', false);
		}
	?>
</div>


<script type="text/javascript">
    $j(window).ready(function(){
        
        $j('.open-collapse').click(function(){
            if($j(this).hasClass('open')){
                $j('.collapse-wrapper').hide().removeClass('open');
                $j(this).removeClass('open');
                $j('i', this).removeClass('fa-angle-up').addClass('fa-angle-down');
            }
            else{
                $j('.collapse-wrapper').show().addClass('open');
                $j(this).addClass('open');
                $j('i', this).removeClass('fa-angle-down').addClass('fa-angle-up');
            }
        });
    })
</script>