<?php $_product = $this->getProduct(); ?>
<div class="actions">
    <div class="action-group">
        <div class="action-loading">
            <div class="loader"></div>
        </div>
        <div class="pull-left">
            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="btn show-product-popup" href="<?php echo $_product->getProductUrl() ?>" data-ajax-product-popup="<?php echo $this->getUrl('catalog/product/ajaxQuickView', array('form_key' => $this->getFormKey())); ?>"><i class="fa fa-eye"></i> <?php echo $this->__('View Details') ?></a>
        </div>

        <?php if ($_product->isSaleable()): ?>
        <div class="pull-right">
            <input type="hidden" class="selected-optionKey-<?php echo $_product->getId(); ?>" />
            <button type="submit" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart simple-add-to-cart-button"><span><span><i class="fa fa-cart-plus"></i> <?php echo $this->__('Add to Cart') ?></span></span></button>
            <div class="qty-buttons">
                <button type="submit" value="btn-cart-qty-minus" title="<?php echo $this->quoteEscape($this->__('Remove one product')); ?>" class="button btn-cart btn-cart-qty-minus"><span><span><i class="fa fa-minus"></i></span></span></button>
                <button type="submit" value="btn-cart-remove" title="<?php echo $this->quoteEscape($this->__('Remove product from cart')); ?>" class="button btn-cart btn-cart-remove"><span><span><i class="fa fa-trash"></i></span></span></button>
                <span class="added-qty">0</span>
                <button type="submit" value="btn-cart-qty-plus" title="<?php echo $this->quoteEscape($this->__('Add one product')); ?>" class="button btn-cart btn-cart-qty-plus"><span><span><i class="fa fa-plus"></i></span></span></button>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
