<?php $_product = $this->getProduct(); ?>
<div class="actions row">
    <div class="action-group">
        <div class="loader"></div>
        <?php if ($_product->isSaleable()): ?>
            <input type="hidden" id="selected-optionKey-<?php echo $_product->getId(); ?>" />
            <button type="submit" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart simple-add-to-cart-button"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <div class="qty-buttons">
                <button type="submit" value="btn-cart-qty-minus" title="<?php echo $this->quoteEscape($this->__('Remove one product')); ?>" class="button btn-cart btn-cart-qty-minus"><span><span><i class="fa fa-minus"></i></span></span></button>
                <button type="submit" value="btn-cart-remove" title="<?php echo $this->quoteEscape($this->__('Remove product from cart')); ?>" class="button btn-cart btn-cart-remove"><span><span><i class="fa fa-trash"></i></span></span></button>
                <span class="added-qty">0</span>
                <button type="submit" value="btn-cart-qty-plus" title="<?php echo $this->quoteEscape($this->__('Add one product')); ?>" class="button btn-cart btn-cart-qty-plus"><span><span><i class="fa fa-plus"></i></span></span></button>
            </div>
        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
        <?php endif; ?>
    </div>
</div>
