<?php $header = ''; ?>
<?php $body = ''; ?>
<?php $availability = $this->getAvailability($this->getProduct()); ?>

<div class="product-availability">
    <div class="hover-title product-availability-title"><?php echo $this->__('Livré le:'); ?></div>
    <?php foreach($this->getWeekDays() as $weekDay): ?>

        <?php if (in_array($weekDay['value'], $availability)) : ?>
            <?php $body .= '<td><i class="fa fa-check"></i></td>'; ?>
            <?php $classHeader = 'available'; ?>
        <?php else : ?>
            <?php $body .= '<td>-</td>'; ?>
            <?php $classHeader = ''; ?>
        <?php endif; ?>
        <?php $header .= '<th class="' . $classHeader . '">' . $weekDay['label'] . '</th>'; ?> 
    <?php endforeach; ?>
    <table class="table">
        <thead>
            <tr><?php echo $header; ?></tr>
        </thead>
        <tbody>
            <tr><?php echo $body; ?></tr>
        </tbody>
    </table>
</div>
