<?php if ($this->getProduct()) : ?>
    <?php $productLabels = $this->getAllProductLabels(); ?>
    <?php if (!empty($productLabels)) : ?>
        <ul class="product-labels">
            <?php $cpt=0; foreach ($productLabels as $label) : ?>

                <li>
                    <?php if (isset($label['icon'])) : ?>
                        <span class="label-icon">
                            <img src="<?php echo $label['icon']; ?>" alt="<?php echo $label['text']; ?>" title="<?php echo $label['text']; ?>" />
                        </span>
                    <?php else : ?>
                         <span class="label-text">
                            <?php echo $label['text']; ?>
                        </span>
                    <?php endif; ?>
                </li>




            <?php $cpt++; ?>
            <?php if ($cpt >= $this->getMaxProductLabels()) : ?>
                <?php break; ?>
            <?php endif; ?>

            <?php endforeach; ?>
        </ul>

    <?php endif; ?>
<?php endif; ?>
