<?php
$_quote = $this->getQuote();
?>

<?php if (is_object($_quote)) : ?>
    <?php $_items = $_order->getAllItems(); ?>
    <?php $_itemCount = count($_items); ?>
    <table class="items" cellpadding="5" cellspacing="0" style="width:100%;border-collapse:collapse;">
        <thead>
            <tr>
                <th class="cell-name" style="width:60%;">
                    <?php if($_itemCount > 1): ?>
                        <!--<?php echo $this->__('Produits dans votre panier'); ?>-->
                        Produits commandés
                    <?php else: ?>
                        <!--<?php echo $this->__('Produit dans votre panier'); ?>-->
                        Produit commandé
                    <?php endif; ?>
                </th>
                <th class="cell-name align-center" style="width:20%;">
                    <?php echo $this->__('Quantité'); ?>
                </th>
                <th class="cell-name align-right" style="width:20%;">
                    <?php echo $this->__('Prix'); ?>
                </th>
            </tr>
        </thead>
        <tbody>
        <?php $i = 0;
        foreach ($_quote->getAllItems() as $_item): ?>
            <?php if ($_item->getParentItemId()) continue; else $i++; ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        </tbody>
    </table>