<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="page-header"><h2>Cartes</h2></div>
    <div class="button_accueil">
      <a href="index.php?module=carte&action=view&carte=livraison"><button type="button" class="btn btn-primary btn-lg btn-block">Cartes livraisons</button></a>
    </div>
    <div class="button_accueil">
	     <a href=""><button type="button" class="btn btn-primary btn-lg btn-block">Carte commerçants</button></a>
    </div>
    <div class="button_accueil">
	     <a href="index.php?module=carte&action=view&carte=clients"><button type="button" class="btn btn-primary btn-lg btn-block">Carte clients</button></a>
    </div>
    <div class="button_accueil">
        <a href="index.php"><button type="button" class="btn btn-default btn-lg btn-block">Retour</button></a>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>