<?php $refund_totals=Mage::helper('pmainguet_delivery')->getRefundorderdata($this->getOrder());
	$total=0;
	$_order=$this->getOrder();
?>
<!--<div class="row">
	<div class="col-sm-12">
	    <h2 class="table-caption"><?php echo $this->__('Vos remboursements') ?></h2>
		<table class="table data-table" id="my-orders-table">
		    <?php foreach($refund_totals as $refund):?>
		        <tr>
		        	<td><?php echo $refund["commercant"];?></td>
		        	<td><?php echo $_order->formatPrice($refund["del_amount_refunded"]);?></td>
		        </tr>
		        <?php $total+=$refund["del_amount_refunded"];?>
		    <?php endforeach;?>
		     <tr>
		        <td><em>TOTAL</em></td>
		        <td><em><?php echo $_order->formatPrice($total) ?></em></td>
		     </tr>
		     <tr>
		        <td><strong>MONTANT REMBOURSÉ</strong></td>
		        <td>
		        	<strong>
			        <?php
			        	if($total<0){
			        		$total=0;
			        	}
			        	echo $_order->formatPrice($total);
			        ?>
		           	</strong>
		        </td>
		     </tr>
		</table>
		<?php echo $this->getChildHtml('amorderattach.attachment2');?>
		<?php echo $this->getChildHtml('footer_orderview');?>
	 </div>
</div>-->


<?php echo $this->getChildHtml('amorderattach.attachment2');?>