<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
   <h3><?php echo $this->__('En cas de non disponibilité') ?></h3>
    <div id="amorderattr" class="form-horizontal">
        <label for="produit_equivalent" class="label-checkout">Je fais confiance aux commerçants pour trouver un produit équivalent</label>
        <select id="produit_equivalent" name="amorderattr[produit_equivalent]" class="required-entry required-entry select">
            <option value="1" selected="selected">Oui</option>
            <option value="0">Non</option>
        </select>
        <div type="anchor" id="anchor_produit_equivalent"></div><div style="padding: 4px;"></div>
    </div>
    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead class="checkout-review-table-collapse" style="border-bottom:solid 1px #CCC">
            <tr>
                <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody style="border-bottom:solid 1px #CCC">
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<script>
$j(function() {
  $j("a").click(function(e) {
    var target = $j(this).data("target");
    var isTargetExpanded = $j(target).hasClass('in');
    //$j('.checkout-review-table-collapse').addClass('collapse').removeClass('in'); // collapse all before expading clicked target
    /*if (isTargetExpanded) {
      $j('.icon-collapse').removeClass('glyphicon-collapse-up').addClass('glyphicon-collapse-down');
      $j(target).addClass('collapse').removeClass("in"); // collapse clicked target
    } else {
      $j('.icon-collapse').removeClass('glyphicon-collapse-down').addClass('glyphicon-collapse-up');
      $j(target).removeClass('collapse').addClass("in"); // expand clicked target
    }*/
  });
});
</script>