<?php foreach ($this->getAllCats() as $category) : ?>
    <li class="<?php echo $this->getClasses($category); ?>">
        <a href="<?php echo $category->getUrl(); ?>" title="<?php echo $category->getName(); ?>"><?php echo $category->getName(); ?></a>
        <?php if ($subcats = $category->getChildren()): ?>
            <ul class="sub-cat-list">
                <?php echo $this->getTreeCategories($category->getId(), true); ?>
            </ul>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
