<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <ul class="social-icons">
                    <li><a href="https://www.facebook.com/aupasdecourses" title="Facebook" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="https://twitter.com/aupasdecourses" title="Twitter" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="https://instagram.com/aupasdecourses/" title="Instagram" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <p class="copyright text-center">
                    ©<?php echo date("Y");?> Au Pas De Courses, tous droits réservés.
                </p>
                <ul class="nav text-center" role="navigation">
                    <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Mentions légales">Mentions légales</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Conditions générales d'utilisation">Conditions générales d'utilisation</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Tarifs">Tarifs</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl().'../blog';?>" title="Blog">Blog</a></li>
                    <li><a href="https://partenaires.aupasdecourses.com" title="Partenaires">Accès Partenaires</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>