<?php $isCheckout = ((!$this->getData('isCheckout') && $this->getData('isCheckout') != 1) ? false : true); ?>
<?php $isRedirectPayment = ((!$this->getData('isRedirectPayment') && $this->getData('isRedirectPayment') != 1) ? false : true); ?>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <?php if(!$isCheckout && !$isRedirectPayment):?>
                    <ul class="social-icons">
                        <li><a href="https://www.facebook.com/aupasdecourses" title="Facebook" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="https://twitter.com/aupasdecourses" title="Twitter" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="https://instagram.com/aupasdecourses/" title="Instagram" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                <?php endif;?>
            </div>
            <div class="col-md-6">
                <p class="copyright text-center">
                    ©<?php echo date("Y");?> Au Pas De Courses, tous droits réservés.
                </p>
                <?php if(!$isCheckout && !$isRedirectPayment):?>
                    <ul class="nav text-center" role="navigation">
                        <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Mentions légales" target="_blank">Mentions légales</a></li>
                        <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Conditions générales d'utilisation" target="_blank">Conditions générales d'utilisation</a></li>
                        <li><a href="<?php echo Mage::getBaseUrl().'../faq';?>" title="Tarifs" target="_blank">Tarifs</a></li>
                        <li><a href="<?php echo Mage::getBaseUrl().'../blog';?>" title="Blog" target="_blank">Blog</a></li>
                        <li><a href="https://partenaires.aupasdecourses.com" title="Partenaires" target="_blank">Accès Partenaires</a></li>
                    </ul>
                <?php endif;?>
            </div>
        </div>
    </div>
</footer>