<header id="header" class="container-fluid">
    <!--<div id="logo_smalldisplay">
        <a class="logo-link" href="<?php echo $this->getUrl('../') ?>">
            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
        </a>
    </div>-->
    <div class="page-header-container row">
            <div class="logo col-md-1 col-sm-12">
                <a class="logo-link" href="<?php echo Mage::getUrl('../');?>">
                    <img src="<?php echo Mage::getBaseUrl();?>../skin/frontend/rwd/commis/images/logo-green.png" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
                </a>
            </div>
	         <!-- Skip Links -->
	         <div class="skip-links pull-right">
                <div class="row">
                    <div class="skip-container skip-container-header-nav hide">
                        <a href="#header-nav" class="skip-link skip-nav">
                            <i class="fa fa-bars"></i>
                            <span class="label"><?php echo $this->__('Menu'); ?></span>
                        </a>
                    </div>

                    <div class="skip-container skip-container-header-search col-md-4 col-sm-12">
                        <input type="text" placeholder="<?php echo $this->__('Your research here'); ?>">
                        <i class="fa fa-search"></i>

                        <!-- Search -->
                        <div id="header-search" class="dropdown-menu skip-content">
                            <?php echo $this->getChildHtml('topSearch') ?>
                        </div>
                    </div>

                    <?php $session = Mage::getSingleton('customer/session', array('name'=>'frontend')); ?>
                    <?php if($session->isLoggedIn()) : ?>
                        <div class="skip-container hidden-sm">
                            <a href="" onclick="location.href='<?php echo Mage::getBaseUrl();?>sponsorship/';" class="skip-link skip-referral">
                                <i class="fa fa-bullhorn"></i>
                                <span class="label">Parrainez</span>
                            </a>
                        </div>
                    <?php endif; ?>

                    <div class="col-md-6 col-md-offset-2 col-sm-12 text-right">

                        <div class="header-delivery-container skip-container">
                             <a href="#" title="Livraison">
								<i class="fa fa-list-ul"></i>
								<span class="label"><?php echo $this->__('Delivery') ?> <i class="fa fa-angle-down"></i></span>
								
							 </a>
							<div class="block block-delivery" id="header-delivery">
								<div class="apdc-popup-content">
									<?php echo $this->getChildHtml('header.delivery') ?>
								</div>
							</div>
                        </div>
						
                        <div class="skip-help skip-container">
                            <a id="dLabel" data-target="#" href="#header-help" class="skip-link skip-help">
                                <span class="label">Aide</span>
                            </a>
                            <ul id="header-help" class="dropdown-menu skip-content links" aria-labelledby="dLabel">
                                <li class="first"><a href="<?php echo Mage::getBaseUrl();?>besoin-d-aide">Besoin d'aide ?</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl();?>zone-et-horaire">Zone & horaires</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl();?>tarifs-livraison">Tarifs</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl();?>formulaire/index/commercantsmanquants/">Commerce manquant</a></li>
                                <li class="last"><a href="<?php echo Mage::getBaseUrl();?>formulaire/index/produitsmanquants/">Produit manquant</a></li>
                            </ul>
                        </div>

                        <div class="header-account-container skip-container">
                            <?php if($this->helper('customer')->isLoggedIn()) : ?>
                                <span class="label"><?php echo $this->__('Account'); ?></span>
                                <i class="fa fa-check account-connected"></i>
                            <?php else : ?>
                                <a href="#" title="Connexion"><i class="fa fa-user"></i> <span class="label">Connexion <i class="fa fa-angle-down"></i></span></a>
                            <?php endif; ?>
                            <div class="block block-login" id="login-form-header_popup">
								<div class="apdc-popup-content">
									<?php if($this->helper('customer')->isLoggedIn()) : ?>
										<?php echo $this->getChildHtml('topLinks') ?>
									<?php else : ?>
										<?php echo $this->getChildHtml('customer_login') ?>
									<?php endif; ?>
								</div>
							</div>
                        </div>

                        <!-- Cart -->
                        <div class="header-minicart skip-container">
                            <?php echo $this->getChildHtml('minicart_head'); ?>
                        </div>
                    </div>
                </div>
	        </div>
    </div>
    <div id="topmenu" class="row">
            <!-- Navigation -->

        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
	</div>
</header>
<?php echo $this->getChildHtml('topContainer'); ?>
<?php echo $this->getChildHtml('page_content_heading'); ?>
<script>
	$j(document).ready(function(){
		
		$j('.header-account-container a').click(function(evt){
			if($j(this).parent().find('.block-login').hasClass('open') ){
				$j(this).parent().find('.block-login').removeClass('open');
				$j(this).parent().find('.label i').removeClass('fa-angle-up').addClass('fa-angle-down');
			}
			else{
				$j(this).parent().find('.block-login').addClass('open');
				$j(this).parent().find('.label i').removeClass('fa-angle-down').addClass('fa-angle-up');
			}
		});
		
		$j('.header-delivery-container a').click(function(evt){
			if($j(this).parent().find('.block-delivery').hasClass('open') ){
				$j(this).parent().find('.block-delivery').removeClass('open');
				$j(this).parent().find('.label i').removeClass('fa-angle-up').addClass('fa-angle-down');
			}
			else{
				$j(this).parent().find('.block-delivery').addClass('open');
				$j(this).parent().find('.label i').removeClass('fa-angle-down').addClass('fa-angle-up');
			}
		});
		
	});
</script>
