<script>
	$j('a').click(function(e) {
	    e.preventDefault();
	    //do other stuff when a click happens
	});
</script>
<div class="hipay_centered_content">
	<div class="hipay_redirect_infobox_content">
		<?php $neighborhood = Mage::helper('apdc_neighborhood')->getNeighborhoodVisiting();?>
		<?php $image = ($neighborhood->getImageBanner() ? $neighborhood->getImageBanner() : $neighborhood->getImage()); ?>
		<?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($image); ?>
		<div class="page-title" style="background-image: url('<?php echo $imageUrl; ?>');">
		    <h1><span><span <?php if(!empty($paymentUrl)) { ?>class="show_loader_image"<?php }; ?>></span> Un instant s'il vous plaît ...</span></h1>
		</div>
		<div class="main_redirect container">
			<p>Vous allez être redirigé vers la page de paiement de notre partenaire</p>
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/images/himediapayments/hipay/hipay_wallet_mg_logo.jpg" />
			<p>Merci de ne pas fermer cette page et de ne pas revenir en arrière.</p>
		</div>
	</div>
</div>

<?php if(!empty($paymentUrl)) { ?>
	<script type="text/javascript">parent.location.href="<?php echo $paymentUrl ?>";</script>
<?php }; ?>