<?php
/**
 * Hipay
 *
 * NOTICE OF LICENSE
 *
 * Copyright (c) 2010, HPME - HI-MEDIA PORTE MONNAIE ELECTRONIQUE (Groupe Hi-Media, Seed Factory, 19 Avenue des Volontaires, 1160 Bruxelles - Belgium)
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 *  - Redistributions of source code must retain the above copyright notice, 
 *    this list of conditions and the following disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 *  - Neither the name of the Hipay and HPME - HI-MEDIA PORTE MONNAIE ELECTRONIQUE 
 *    nor the names of its contributors may be used to endorse or promote products 
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   Paymentnetwork
 * @package    Paymentnetwork_Hipay
 * @copyright  Copyright (c) 2010 HPME - HI-MEDIA PORTE MONNAIE ELECTRONIQUE
 * @license    http://www.opensource.org/licenses/bsd-license.php  The BSD License
 */ 
?>
<script>
	$j('a').click(function(e) {
	    e.preventDefault();
	    //do other stuff when a click happens
	});
</script>
<div class="hipay_centered_content">
	<div class="hipay_redirect_infobox_content">
		<?php $neighborhood = Mage::helper('apdc_neighborhood')->getNeighborhoodVisiting();?>
		<?php $image = ($neighborhood->getImageBanner() ? $neighborhood->getImageBanner() : $neighborhood->getImage()); ?>
		<?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($image); ?>
		<div class="page-title" style="background-image: url('<?php echo $imageUrl; ?>');">
		    <h1><span><span <?php if(!empty($paymentUrl)) { ?>class="show_loader_image"<?php }; ?>></span> Un instant s'il vous plaît ...</span></h1>
		</div>
		<div class="main_redirect">
			<p class="main_message"></p>
			<p>Vous allez être redirigé vers la page de paiement de notre partenaire</p>
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/images/himediapayments/hipay/hipay_wallet_mg_logo.jpg" />
			<p class="subtitle">Merci de ne pas fermer cette page et de ne pas revenir en arrière.</p>
		</div>
	</div>
</div>

<?php if(!empty($paymentUrl)) { ?>
	<script type="text/javascript">parent.location.href="<?php echo $paymentUrl ?>";</script>
<?php }; ?>