<?php

class Apdc_Catalog_Helper_Product_Labels extends Mage_Core_Helper_Abstract
{
	public function getImageLabels(){
		return array(
			"Produit Bio" => $this->getLabelBio(),
			"Produit De Saison" => $this->getLabelSaison(),
			"Nouveau Produit" => $this->getLabelNew(),
		);
	}

	public function getAuthorizeLabels(){
		return [
            'AOC' => 'images/labels/AOC.png',
            'DOC' => 'images/labels/AOC.png',
            'DOP' => 'images/labels/AOC.png',
            'AOP' => 'images/labels/AOC.png',
            'IGP' => 'images/labels/AOC.png',
            'Demeter' => 'images/labels/demeter.png',
            'Label Rouge' => 'images/labels/labelrouge.png',
            'Bleu blanc coeur' => 'images/labels/bleublanccoeur.png',
            'Bleu Blanc Coeur' => 'images/labels/bleublanccoeur.png',
            'Commerce équitable' => 'images/labels/fairtrade.png',
            'Commerce Equitable' => 'images/labels/fairtrade.png',
            'Casher' => 'images/labels/casher.png',
            'Kasher' => 'images/labels/casher.png',
            'Halal' => 'images/labels/halal.png',
            'Sans Gluten' => 'images/labels/sansgluten.png'
        ];
	}

	public function getAuthorizeOrigine(){
        return [
                'Abkhazie'=>'abkhazia.png',
                'Açores'=>'azores-islands.png',
                'Afghanistan'=>'afghanistan.png',
                'Afrique du Sud'=>'south-africa.png',
                'Albanie'=>'albania.png',
                'Algérie'=>'algeria.png',
                'Allemagne'=>'germany.png',
                'Andorre'=>'andorra.png',
                'Angleterre'=>'england.png',
                'Angola'=>'angola.png',
                'Anguilla'=>'anguilla.png',
                'Antigua-Et-Barbuda'=>'antigua-and-barbuda.png',
                'Arabie Saoudite'=>'saudi-arabia.png',
                'Argentine'=>'argentina.png',
                'Arménie'=>'armenia.png',
                'Aruba'=>'aruba.png',
                'Australie'=>'australia.png',
                'Autriche'=>'austria.png',
                'Azerbaïdjan'=>'azerbaijan.png',
                'Bahamas'=>'bahamas.png',
                'Bahrain'=>'bahrain.png',
                'Bangladesh'=>'bangladesh.png',
                'Barbade'=>'barbados.png',
                'Belgique'=>'belgium.png',
                'Belize'=>'belize.png',
                'Bénin'=>'benin.png',
                'Bermudes'=>'bermuda.png',
                'Bhutan'=>'bhutan.png',
                'Bhutan-1'=>'bhutan-1.png',
                'Biélorussie'=>'belarus.png',
                'Birmanie'=>'myanmar.png',
                'Bolivie'=>'bolivia.png',
                'Bonaire'=>'bonaire.png',
                'Bosnie Herzégovine'=>'bosnia-and-herzegovina.png',
                'Botswana'=>'botswana.png',
                'Brésil'=>'brazil.png',
                'Brunei'=>'brunei.png',
                'Bulgarie'=>'bulgaria.png',
                'Burkina Faso'=>'burkina-faso.png',
                'Burundi'=>'burundi.png',
                'Cambodge'=>'cambodia.png',
                'Cameroun'=>'cameroon.png',
                'Canada'=>'canada.png',
                'Cap-Vert'=>'cape-verde.png',
                'Chili'=>'chile.png',
                'Chine'=>'china.png',
                'Christmas Island'=>'christmas-island.png',
                'Chypre'=>'cyprus.png',
                'Cité Du Vatican'=>'vatican-city.png',
                'Cocos-Île'=>'cocos-island.png',
                'Colombie'=>'colombia.png',
                'Colombie Britannique'=>'british-columbia.png',
                'Comores'=>'comoros.png',
                'Corée Du Nord'=>'north-korea.png',
                'Corée Du Sud'=>'south-korea.png',
                'Corse'=>'corsica.png',
                'Costa Rica'=>'costa-rica.png',
                'Côte d\'Ivoire'=>'ivory-coast.png',
                'Crète'=>'greece.png',
                'Croatie'=>'croatia.png',
                'Cuba'=>'cuba.png',
                'Curacao'=>'curacao.png',
                'Danemark'=>'denmark.png',
                'Djibouti'=>'djibouti.png',
                'Dominica'=>'dominica.png',
                'Ecosse'=>'scotland.png',
                'Egypte'=>'egypt.png',
                'Emirats Arabes Unis'=>'united-arab-emirates.png',
                'Equateur'=>'ecuador.png',
                'Érythrée'=>'eritrea.png',
                'Espagne'=>'spain.png',
                'Estonie'=>'estonia.png',
                'États-Unis d\'Amérique'=>'united-states-of-america.png',
                'Ethiopie'=>'ethiopia.png',
                'Europe'=>'europe.png',
                'Fidji'=>'fiji.png',
                'Finlande'=>'finland.png',
                'France'=>'france.png',
                'Gabon'=>'gabon.png',
                'Gambie'=>'gambia.png',
                'Géorgie'=>'georgia.png',
                'Ghana'=>'ghana.png',
                'Gibraltar'=>'gibraltar.png',
                'Grande Bretagne'=>'united-kingdom.png',
                'Grèce'=>'greece.png',
                'Hollande'=>'netherlands.png',
                'Honduras'=>'honduras.png',
                'Ile Maurice'=>'mauritius.png',
                'Iran'=>'iran.png',
                'Irlande'=>'ireland.png',
                'Islande '=>'iceland.png',
                'Israël'=>'israel.png',
                'Italie '=>'italy.png',
                'Japon'=>'japan.png',
                'Jordanie'=>'jordan.png',
                'Kenya'=>'kenya.png',
                'La Réunion'=>'france.png',
                'Lituanie'=>'lithuania.png',
                'Madagascar'=>'madagascar.png',
                'Maroc'=>'morocco.png',
                'Martinique'=>'france.png',
                'Mexique'=>'mexico.png',
                'Norvège'=>'norway.png',
                'Nouvelle-Zélande'=>'new-zealand.png',
                'Ouganda'=>'uganda.png',
                'Pays-Bas'=>'netherlands.png',
                'Pérou'=>'peru.png',
                'Pologne'=>'republic-of-poland.png',
                'Portugal'=>'portugal.png',
                'République Dominicaine'=>'dominican-republic.png',
                'République Tchèque'=>'czech-republic.png',
                'Russie'=>'russia.png',
                'Samoa Américaines'=>'american-samoa.png',
                'Sardaigne'=>'sardinia.png',
                'Sénégal'=>'senegal.png',
                'Suisse'=>'switzerland.png',
                'Togo'=>'togo.png',
                'Tunisie'=>'tunisia.png',
                'Turquie'=>'turkey.png',
                'Uruguay'=>'uruguay.png',
                'Venezuela'=>'venezuela.png',
                'Vietnam'=>'vietnam.png',
                'Grenada'=>'grenada.png',
                'Groenland'=>'greenland.png',
                'Guam'=>'guam.png',
                'Guatemala'=>'guatemala.png',
                'Guernsey'=>'guernsey.png',
                'Guinée'=>'guinea.png',
                'Guinée Équatoriale'=>'equatorial-guinea.png',
                'Guinée-Bissau'=>'guinea-bissau.png',
                'Guyane'=>'guyana.png',
                'Haïti'=>'haiti.png',
                'Hawaii'=>'hawaii.png',
                'Hong Kong'=>'hong-kong.png',
                'Hongrie'=>'hungary.png',
                'Ile De Norfolk'=>'norfolk-island.png',
                'Iles Aland'=>'aland-islands.png',
                'Îles Baléares'=>'balearic-islands.png',
                'Îles Caïmans'=>'cayman-islands.png',
                'Îles Canaries'=>'canary-islands.png',
                'Îles Cook'=>'cook-islands.png',
                'Îles Falkland'=>'falkland-islands.png',
                'Îles Féroé'=>'faroe-islands.png',
                'Îles Galapagos'=>'galapagos-islands.png',
                'Îles Salomon'=>'solomon-islands.png',
                'Îles Turques Et Caïques'=>'turks-and-caicos.png',
                'Iles Vierges'=>'virgin-islands.png',
                'Îles Vierges Britanniques'=>'british-virgin-islands.png',
                'Inde'=>'india.png',
                'Indonésie'=>'indonesia.png',
                'Irak'=>'iraq.png',
                'Isle-Of-Man'=>'isle-of-man.png',
                'Jamaïque'=>'jamaica.png',
                'Jersey'=>'jersey.png',
                'Kazakhstan'=>'kazakhstan.png',
                'Kiribati'=>'kiribati.png',
                'Kosovo'=>'kosovo.png',
                'Koweit'=>'kuwait.png',
                'Kyrgyzstan'=>'kyrgyzstan.png',
                'Laos'=>'laos.png',
                'Les Seychelles'=>'seychelles.png',
                'Lesotho'=>'lesotho.png',
                'Lettonie'=>'latvia.png',
                'Liban'=>'lebanon.png',
                'Libéria'=>'liberia.png',
                'Libye'=>'libya.png',
                'Liechtenstein'=>'liechtenstein.png',
                'Luxembourg'=>'luxembourg.png',
                'Macao'=>'macao.png',
                'Madère'=>'madeira.png',
                'Malaisie'=>'malaysia.png',
                'Malawi'=>'malawi.png',
                'Maldives'=>'maldives.png',
                'Mali'=>'mali.png',
                'Malte'=>'malta.png',
                'Marshall-Île'=>'marshall-island.png',
                'Mauritanie'=>'mauritania.png',
                'Melilla'=>'melilla.png',
                'Micronesia'=>'micronesia.png',
                'Moldova'=>'moldova.png',
                'Monaco'=>'monaco.png',
                'Mongolie'=>'mongolia.png',
                'Monténégro'=>'montenegro.png',
                'Montserrat'=>'montserrat.png',
                'Mozambique'=>'mozambique.png',
                'Namibie'=>'namibia.png',
                'Nations Unies'=>'united-nations.png',
                'Nato'=>'nato.png',
                'Nauru'=>'nauru.png',
                'Népal'=>'nepal.png',
                'Nicaragua'=>'nicaragua.png',
                'Niger'=>'niger.png',
                'Nigeria'=>'nigeria.png',
                'Niue'=>'niue.png',
                'Nord-Marianas-Îles'=>'northern-marianas-islands.png',
                'Northen-Chypre'=>'northen-cyprus.png',
                'Oman'=>'oman.png',
                'Orcades-Îles'=>'orkney-islands.png',
                'Ossétie'=>'ossetia.png',
                'Pakistan'=>'pakistan.png',
                'Palau'=>'palau.png',
                'Palestine'=>'palestine.png',
                'Panama'=>'panama.png',
                'Papouasie Nouvelle Guinée'=>'papua-new-guinea.png',
                'Paraguay'=>'paraguay.png',
                'Pays Basque'=>'basque-country.png',
                'Pays De Galles'=>'wales.png',
                'Philippines'=>'philippines.png',
                'Pitcairn-Îles'=>'pitcairn-islands.png',
                'Polynésie Française'=>'french-polynesia.png',
                'Puerto-Rico'=>'puerto-rico.png',
                'Qatar'=>'qatar.png',
                'Rapa Nui'=>'rapa-nui.png',
                'Redimensionner'=>'resize.sh',
                'République Centrafricaine'=>'central-african-republic.png',
                'République Démocratique Du Congo'=>'democratic-republic-of-congo.png',
                'République-De-Macédoine'=>'republic-of-macedonia.png',
                'République-Of-The-Congo'=>'republic-of-the-congo.png',
                'Roumanie'=>'romania.png',
                'Rwanda'=>'rwanda.png',
                'Saba-Île'=>'saba-island.png',
                'Sahara Occidental'=>'western-sahara.png',
                'Saint Marin'=>'san-marino.png',
                'Saint-Christophe-Et-Niévès'=>'saint-kitts-and-nevis.png',
                'Sainte Lucie'=>'st-lucia.png',
                'Salvador'=>'salvador.png',
                'Samoa'=>'samoa.png',
                'Sao-Tome-Et-Principe'=>'sao-tome-and-principe.png',
                'Serbie'=>'serbia.png',
                'Sierra Leone'=>'sierra-leone.png',
                'Singapour'=>'singapore.png',
                'Sint-Eustatius'=>'sint-eustatius.png',
                'Sint-Maarten'=>'sint-maarten.png',
                'Slovaquie'=>'slovakia.png',
                'Slovénie'=>'slovenia.png',
                'Somalie'=>'somalia.png',
                'Somaliland'=>'somaliland.png',
                'Soudan'=>'sudan.png',
                'Soudan Du Sud'=>'south-sudan.png',
                'Sri-Lanka'=>'sri-lanka.png',
                'St-Barth'=>'st-barts.png',
                'St-Vincent-Et-Les-Grenadines'=>'st-vincent-and-the-grenadines.png',
                'Suède'=>'sweden.png',
                'Suriname'=>'suriname.png',
                'Swaziland'=>'swaziland.png',
                'Syrie'=>'syria.png',
                'Taïwan'=>'taiwan.png',
                'Tajikistan'=>'tajikistan.png',
                'Tanzanie'=>'tanzania.png',
                'Tchad'=>'chad.png',
                'Territoire-Océan Indien-Britannique'=>'british-indian-ocean-territory.png',
                'Thaïlande'=>'thailand.png',
                'Tibet'=>'tibet.png',
                'Timor Oriental'=>'east-timor.png',
                'Tokelau'=>'tokelau.png',
                'Tonga'=>'tonga.png',
                'Transnistrie'=>'transnistria.png',
                'Trinité-Et-Tobago'=>'trinidad-and-tobago.png',
                'Turkmenistan'=>'turkmenistan.png',
                'Tuvalu'=>'tuvalu.png',
                'Ukraine'=>'ukraine.png',
                'Union Européenne'=>'european-union.png',
                'Ouzbekistan'=>'uzbekistn.png',
                'Vanuatu'=>'vanuatu.png',
                'Yémen'=>'yemen.png',
                'Zambie'=>'zambia.png',
                'Zimbabwe'=>'zimbabwe.png',
        ];
     }

     public function getLabelNew(){
     	return 'images/labels/new.png';
     }

     public function getLabelBio(){
     	return 'images/labels/bio.png';
     }

     public function getLabelSaison(){
     	return 'images/labels/saison.png';
     }

     public function getLabelRupture(){
     	return 'images/labels/rutpure.png';
     }
}