<?php

function ol($merchant, $order) {
	$ol = [
		1 => 'OL',
		2 => 'APDC5322',
		3 => '',
		4 => $order['customer_id'],
		5 => '',
		6 => "{$order['first_name']} {$order['last_name']}",
		7 => '',
		8 => '',
		9 => $order['address'],
		10 => preg_split("/\s(\d{5})\s/", $order['address'], -1, PREG_SPLIT_DELIM_CAPTURE)[1],
		11 => preg_split("/\s(\d{5})\s/", $order['address'], -1, PREG_SPLIT_DELIM_CAPTURE)[2],
		12 => 'FR',
		13 => 'FRANCE',
		14 => preg_replace(' ', '', $order['phone']),
		15 => '',
		16 => '',
		17 => 'voir info',
		18 => '',
		19 => 'N',
		20 => '',
		21 => '',
		22 => "{$order['id']}-{$merchant['id']}",
		23 => split('-', $order['delivery_time'])[0],
		24 => split('-', $order['delivery_time'])[1],
		25 => '',
		26 => '',
		27 => '',
		28 => '',
		29 => '',
		30 => '',
		31 => '18/10/2016',
//		31 => split('-', $order['delivery_date'])[2] .'/'. split('-', $order['delivery_date'])[1] .'/'. split('-', $order['delivery_date'])[0],
		32 => '',
		33 => '',
		34 => 'TRAD',
		35 => 'C',
		36 => "{$order['info']} | Autre Contact: {$order['contact']} {$order['contact_phone']}",
		37 => '',
		38 => $order['id'],
		39 => '',
		40 => '',
		41 => '',
		42 => '',
		43 => '',
		44 => '',
		45 => '',
		46 => '',
		47 => '',
		48 => '',
		49 => '',
		50 => '',
		51 => '',
		52 => '',
		53 => 'LPR',
		54 => '',
		55 => '',
	];

	return implode(';', $ol);
}
