<?php
/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */

$html = '';
$children = $menuTree->getChildren();
$menuTree->setCounter(1);

$shop = $this->getShopByCategoryId(str_replace('category-node-', '', $menuTree->getId()));

if ($shop->getShopUrl() || $shop->getAllProductsLink()) {
    $html .= '<li class="template-line common-links">';
    $html .= '<ul>';
    if ($shop->getShopUrl()) {
        $html .= '<li class="level2 first template-column">';
        $html .=    '<a href="' . $shop->getShopUrl() . '" class="">';
        $html .=        '<span class="cat-name">' . $this->__('En savoir plus sur %s', $shop->getName()) . '</span>';
        $html .=    '</a>';
        $html .= '</li>';
    }
    if ($shop->getAllProductsLink()) {
        $html .= '<li class="level2 last template-column">';
        $html .=    '<a href="' . $shop->getAllProductsLink() . '" class="">';
        $html .=        '<span class="cat-name">' . $this->__('Tous les produits de %s', $shop->getName()) . '</span>';
        $html .=    '</a>';
        $html .= '</li>';
    }
    $html .= '</ul>';
    $html .= '</li>';
    $html .= '<li class="template-line separator"></li>';
}

$html .= '<li class="template-line">';
$html .= '<ul>';
$cpt = 0;
foreach ($children as $child) {
    if ($cpt > 0 && $cpt % 4 == 0) {
        $html .= '</ul>';
        $html .= '<ul>';
    }

    $this->initChild($child, $menuTree);

    $html .= '<li '. $this->_getRenderedMenuItemAttributes($child) .'>';

    if ($child->getIsClickable()) {
        $html .= '<a style="' . $child->getLinkStyle() . '" href="'. $child->getUrl() .'" class="'. $child->getLinkClasses() .'">';
        $html .= '<div class="cat-thumbnail">';
        if ($child->getThumbnail()) {
            $thumbnail = $this->getResizedImage($child->getThumbnail(), 100,100);
            $html .= '<img src="' . $thumbnail . '"/>';
        }
        $html .= '</div>';
        $html .= '<span class="cat-name">'.$this->escapeHtml($this->__($child->getName())).'</span>';
        if ($child->hasChildren()) {
            $html .= '<div class="deploy-menu-button"><i class="fa fa-caret-down"></i></div>';
        }
        $html .= '</a>';
    } else {
        $html .= '<span class="template-column-title" style="' . $child->getLinkStyle() . '" class="'. $child->getLinkClasses() .'">';
        $html .= $this->escapeHtml($this->__($child->getName()));
        if ($child->hasChildren()) {
            $html .= '<div class="deploy-menu-button"><i class="fa fa-caret-down"></i></div>';
        }
        $html .= '</span>';
    }

    if ($child->hasChildren()) {
        $html .= '<ul class="' . $child->getSubMenuClasses() . '">';
        foreach ($child->getChildren() as $subChild) {
            $html .= '<li '. $this->_getRenderedMenuItemAttributes($subChild) .'>';
            if ($subChild->getIsClickable()) {
                $html .= '<a style="' . $subChild->getLinkStyle() . '" href="'. $subChild->getUrl() .'" class="'. $subChild->getLinkClasses() .'"><i class="fa fa-angle-right"></i>'. $this->escapeHtml($this->__($subChild->getName())) .'</a>';
            } else {
                $html .= '<span style="' . $subChild->getLinkStyle() . '" class="'. $subChild->getLinkClasses() .'"><i class="fa fa-angle-right"></i>'. $this->escapeHtml($this->__($subChild->getName())) .'</span>';
            }
            $html .= '</li>';
        }
        $html .= '</ul>';
    }

    $html .= '</li>';

    $counter = $menuTree->getCounter();
    $counter++;
    $menuTree->setCounter($counter);
    $cpt++;
}
$html .= '</ul>';
$html .= '</li>';

return $html;
