<?php $neighborhoods = $this->getNeighborhoods(); ?>
<?php $currentNeighborhood = $this->getCurrentNeighborhood(); ?>
<?php $informationType = $this->getInformationsType(); ?>
<a id="my_neighborhood_menu" data-target="#" href="#my_neighborhood_menu_links" class="skip-link skip-help">
    <i class="fa fa-home"></i>
    <span class="label"><?php echo $this->__('Neighborhood'); ?></span>
    <?php if ($informationType) : ?>
        <span class="count">1</span>
    <?php endif; ?>
</a>
<ul id="my_neighborhood_menu_links" class="dropdown-menu skip-content links" aria-labelledby="my_neighborhood_menu">
    <?php if ($informationType) : ?>
        <li class="neighborhood_informations">
            <?php if ($informationType == 'new_neighborhood'): ?>
                <div class="neighborhood_informations_title"><?php echo $this->__('New!'); ?></div>
                <p><?php echo $this->__('You can now switch between neighborhoods. So it\'s easier if you move or want to delivery at work or to your friends.'); ?></p>
                <ul>
                    <li><i class="fa fa-eye"></i> <?php echo $this->__('Clicking this icon you can visit the neighborhood and check the shopkeeper and the products of the neighborhood'); ?></li>
                    <li><i class="fa fa-save"></i> <?php echo $this->__('Clicking this icon you set the neighborhood as your new neighborhood'); ?></li>
                </ul>
                <div class="neighborhood_ok">
                    <button id="neighborhood_ok" class="button"><span><?php echo $this->__('I Understood'); ?></span></button>
                </div>
                
            <?php elseif ($informationType == 'no_neighborhood') : ?>
                <div class="neighborhood_informations_title"><?php echo $this->__('Warning!'); ?></div>
                <p><?php echo $this->__('You have not set your neighborhood yet. Please choose your neighborhood by clicking on %s icon', '<i class="fa fa-save"></i>'); ?></p>
            <?php elseif ($informationType == 'not_same_website') : ?>
                <div class="neighborhood_informations_title"><?php echo $this->__('Information'); ?></div>
                <p>
                    <?php echo $this->__('You are visiting a different neighborhood. Do you want to set this neighborhood as your neighborhood?'); ?>
                    <div class="neighborhood_ok">
                        <a href="<?php echo $this->getSaveVisitUrl(); ?>" class="button"><i class="fa fa-save"></i> <?php echo $this->__('Switch to %s', $this->getVisitingNeighborhood()->getName()); ?></a>
                    </div>
                </p>
            <?php endif; ?>
        </li>
    <?php endif; ?>
    <?php if ($currentNeighborhood && $currentNeighborhood->getId()) :  ?>
        <li class="neighborhood_title">
            <?php echo $this->__('Your Neighborhood'); ?>
        </li>
        <?php if ($this->getVisitingNeighborhood() && $this->getVisitingNeighborhood()->getId() != $currentNeighborhood->getId()): ?>
            <li class="neighborhood_list selected">
                <?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($currentNeighborhood->getImage(), array('width' => 50, 'height' => 50)); ?>
                <img src="<?php echo $imageUrl; ?>" title="<?php echo $currentNeighborhood->getName(); ?>" width="50" height="50" />
                <span><?php echo $currentNeighborhood->getName(); ?></span>
                <ul class="neighborhood_actions">
                    <li><a href="<?php echo $this->getVisitUrl($currentNeighborhood); ?>" title="<?php echo $this->__('Visit this currentNeighborhood'); ?>"><i class="fa fa-eye"></i></a></li>
                </ul>
            </li>
        <?php else : ?>
            <li class="neighborhood_list selected">
                <?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($currentNeighborhood->getImage(), array('width' => 50, 'height' => 50)); ?>
                <img src="<?php echo $imageUrl; ?>" title="<?php echo $currentNeighborhood->getName(); ?>" width="50" height="50" />
                <span><?php echo $currentNeighborhood->getName(); ?></span>
            </li>
        <?php endif; ?>
    <?php endif; ?>

    <li class="neighborhood_title">
        <?php if ($informationType && ($informationType == 'no_neighborhood' || $informationType == 'new_neighborhood')) : ?>
            <?php echo $this->__('Choose Your Neighborhood'); ?>
        <?php else : ?>
            <?php echo $this->__('Choose Another Neighborhood'); ?>
        <?php endif; ?>
    </li>
    <?php foreach ($neighborhoods as $neighborhood) : ?>
        <?php if ($currentNeighborhood && $currentNeighborhood->getId() == $neighborhood->getId()) : ?>
            <?php continue; ?>
        <?php endif; ?>
        <li class="neighborhood_list choose">
            <?php $imageUrl = Mage::helper('apdc_neighborhood/media')->getMediaUrl($neighborhood->getImage(), array('width' => 50, 'height' => 50)); ?>
            <img src="<?php echo $imageUrl; ?>" title="<?php echo $neighborhood->getName(); ?>" width="50" height="50" />
            <span><?php echo $neighborhood->getName(); ?></span>
            <ul class="neighborhood_actions">
                <li><a href="<?php echo $this->getVisitUrl($neighborhood); ?>" title="<?php echo $this->__('Visit this neighborhood'); ?>"><i class="fa fa-eye"></i></a></li>
                <?php if ($this->getSession()->isLoggedIn()) : ?>
                    <li><a href="<?php echo $this->getSaveUrl($neighborhood); ?>" title="<?php echo $this->__('Set this neighborhood as my new neighborhood'); ?>"><i class="fa fa-save"></i></a></li>
                <?php endif; ?>
            </ul>
        </li>
    <?php endforeach; ?>
</ul>
<script type="text/javascript">
    var neighborhoodIUnderstoodUrl = '<?php echo $this->getNeighborhoodIUnderstoodUrl(); ?>';
</script>
