<?php $availability = $this->getAvailability(); ?>
<?php if (!$availability['is_available']) : ?>
    <div class="product_availability_message">
        <p>
            <?php echo $this->helper('apdc_catalog')->__('Non disponible pour le créneau sélectionné :%s', ' <br /><strong>' . $availability['message']) . '</strong>'; ?>
            <?php $specific = $this->getSpecificMessages(); ?>
            <?php if ($specific != '') : ?>
                <br /><a href="#" class="tooltip-product-availability" data-toggle="tooltip" data-placement="bottom" data-html="true" title="<?php echo $specific; ?>"><i class="fa fa-info-circle"></i></a>
            <?php endif; ?>
        </p>
    </div>
<?php elseif (!$availability['can_order']) : ?>
    <div class="product_availability_message">
        <p>
            <?php echo $this->helper('apdc_catalog')->__('Non disponible aujourd\'hui : %s', ' <br /><strong>' . $availability['message']) . '</strong>'; ?>
            <?php $specific = $this->getSpecificMessages(); ?>
            <?php if ($specific != '') : ?>
                <br /><a href="#" class="tooltip-product-availability" data-toggle="tooltip" data-placement="bottom" data-html="true" title="<?php echo $specific; ?>"><i class="fa fa-info-circle"></i></a>
            <?php endif; ?>
        </p>
    </div>
<?php endif; ?>
