<!DOCTYPE html>
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="fr" id="top" class="no-js"> <!--<![endif]-->

<head>
<title><?php echo Mage::getSingleton("cms/page")->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars(Mage::getSingleton("cms/page")->getMetaDescription()) ?>" />
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col1-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('messages') ?>
                <div class="cms-content block-promos container">
                    <div class="border-container"></div>
                    <div class="content">
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>